// Copyright (c) Matt Campbell
// MIT license (see License.txt)

// AUTOGENERATED FILE - DO NOT EDIT

// clang-format off

#include "bboxtolog_json_generated.h"
#include "bb_array.h"
#include "bb_string.h"
#include "json_utils.h"
#include "va.h"

#include "bbstats.h"
#include "sb.h"
#include "sdict.h"
#include "uuid_rfc4122/sysdep.h"
#include "view_filter.h"

//////////////////////////////////////////////////////////////////////////

//////////////////////////////////////////////////////////////////////////

//////////////////////////////////////////////////////////////////////////

vfilter_type_e json_deserialize_vfilter_type_e(JSON_Value *src)
{
	vfilter_type_e dst = kVF_Count;
	if(src) {
		const char *str = json_value_get_string(src);
		if(str) {
			if(!bb_stricmp(str, "kVF_Standard")) { dst = kVF_Standard; }
			if(!bb_stricmp(str, "kVF_SQL")) { dst = kVF_SQL; }
			if(!bb_stricmp(str, "kVF_Legacy")) { dst = kVF_Legacy; }
			if(!bb_stricmp(str, "kVF_Count")) { dst = kVF_Count; }
		}
	}
	return dst;
}

vfilter_token_type_e json_deserialize_vfilter_token_type_e(JSON_Value *src)
{
	vfilter_token_type_e dst = kVFT_Count;
	if(src) {
		const char *str = json_value_get_string(src);
		if(str) {
			if(!bb_stricmp(str, "kVFT_Invalid")) { dst = kVFT_Invalid; }
			if(!bb_stricmp(str, "kVFT_OpenParen")) { dst = kVFT_OpenParen; }
			if(!bb_stricmp(str, "kVFT_CloseParen")) { dst = kVFT_CloseParen; }
			if(!bb_stricmp(str, "kVFT_String")) { dst = kVFT_String; }
			if(!bb_stricmp(str, "kVFT_LessThan")) { dst = kVFT_LessThan; }
			if(!bb_stricmp(str, "kVFT_LessThanEquals")) { dst = kVFT_LessThanEquals; }
			if(!bb_stricmp(str, "kVFT_Equals")) { dst = kVFT_Equals; }
			if(!bb_stricmp(str, "kVFT_NotEquals")) { dst = kVFT_NotEquals; }
			if(!bb_stricmp(str, "kVFT_GreaterThan")) { dst = kVFT_GreaterThan; }
			if(!bb_stricmp(str, "kVFT_GreaterThanEquals")) { dst = kVFT_GreaterThanEquals; }
			if(!bb_stricmp(str, "kVFT_Matches")) { dst = kVFT_Matches; }
			if(!bb_stricmp(str, "kVFT_And")) { dst = kVFT_And; }
			if(!bb_stricmp(str, "kVFT_Or")) { dst = kVFT_Or; }
			if(!bb_stricmp(str, "kVFT_Not")) { dst = kVFT_Not; }
			if(!bb_stricmp(str, "kVFT_Contains")) { dst = kVFT_Contains; }
			if(!bb_stricmp(str, "kVFT_StartsWith")) { dst = kVFT_StartsWith; }
			if(!bb_stricmp(str, "kVFT_EndsWith")) { dst = kVFT_EndsWith; }
			if(!bb_stricmp(str, "kVFT_DeltaMillisecondsAbsolute")) { dst = kVFT_DeltaMillisecondsAbsolute; }
			if(!bb_stricmp(str, "kVFT_DeltaMillisecondsViewRelative")) { dst = kVFT_DeltaMillisecondsViewRelative; }
			if(!bb_stricmp(str, "kVFT_Filename")) { dst = kVFT_Filename; }
			if(!bb_stricmp(str, "kVFT_Thread")) { dst = kVFT_Thread; }
			if(!bb_stricmp(str, "kVFT_PIEInstance")) { dst = kVFT_PIEInstance; }
			if(!bb_stricmp(str, "kVFT_Category")) { dst = kVFT_Category; }
			if(!bb_stricmp(str, "kVFT_Verbosity")) { dst = kVFT_Verbosity; }
			if(!bb_stricmp(str, "kVFT_Text")) { dst = kVFT_Text; }
			if(!bb_stricmp(str, "kVFT_Number")) { dst = kVFT_Number; }
			if(!bb_stricmp(str, "kVFT_NamedFilter")) { dst = kVFT_NamedFilter; }
			if(!bb_stricmp(str, "kVFT_Count")) { dst = kVFT_Count; }
		}
	}
	return dst;
}

//////////////////////////////////////////////////////////////////////////

JSON_Value *json_serialize_vfilter_type_e(const vfilter_type_e src)
{
	const char *str = "";
	switch(src) {
		case kVF_Standard: str = "kVF_Standard"; break;
		case kVF_SQL: str = "kVF_SQL"; break;
		case kVF_Legacy: str = "kVF_Legacy"; break;
		case kVF_Count: str = "kVF_Count"; break;
	}
	JSON_Value *val = json_value_init_string(str);
	return val;
}

JSON_Value *json_serialize_vfilter_token_type_e(const vfilter_token_type_e src)
{
	const char *str = "";
	switch(src) {
		case kVFT_Invalid: str = "kVFT_Invalid"; break;
		case kVFT_OpenParen: str = "kVFT_OpenParen"; break;
		case kVFT_CloseParen: str = "kVFT_CloseParen"; break;
		case kVFT_String: str = "kVFT_String"; break;
		case kVFT_LessThan: str = "kVFT_LessThan"; break;
		case kVFT_LessThanEquals: str = "kVFT_LessThanEquals"; break;
		case kVFT_Equals: str = "kVFT_Equals"; break;
		case kVFT_NotEquals: str = "kVFT_NotEquals"; break;
		case kVFT_GreaterThan: str = "kVFT_GreaterThan"; break;
		case kVFT_GreaterThanEquals: str = "kVFT_GreaterThanEquals"; break;
		case kVFT_Matches: str = "kVFT_Matches"; break;
		case kVFT_And: str = "kVFT_And"; break;
		case kVFT_Or: str = "kVFT_Or"; break;
		case kVFT_Not: str = "kVFT_Not"; break;
		case kVFT_Contains: str = "kVFT_Contains"; break;
		case kVFT_StartsWith: str = "kVFT_StartsWith"; break;
		case kVFT_EndsWith: str = "kVFT_EndsWith"; break;
		case kVFT_DeltaMillisecondsAbsolute: str = "kVFT_DeltaMillisecondsAbsolute"; break;
		case kVFT_DeltaMillisecondsViewRelative: str = "kVFT_DeltaMillisecondsViewRelative"; break;
		case kVFT_Filename: str = "kVFT_Filename"; break;
		case kVFT_Thread: str = "kVFT_Thread"; break;
		case kVFT_PIEInstance: str = "kVFT_PIEInstance"; break;
		case kVFT_Category: str = "kVFT_Category"; break;
		case kVFT_Verbosity: str = "kVFT_Verbosity"; break;
		case kVFT_Text: str = "kVFT_Text"; break;
		case kVFT_Number: str = "kVFT_Number"; break;
		case kVFT_NamedFilter: str = "kVFT_NamedFilter"; break;
		case kVFT_Count: str = "kVFT_Count"; break;
	}
	JSON_Value *val = json_value_init_string(str);
	return val;
}

//////////////////////////////////////////////////////////////////////////

vfilter_type_e vfilter_type_e_from_string(const char *src)
{
	vfilter_type_e dst = kVF_Count;
	if(src) {
		if(!bb_stricmp(src, "kVF_Standard")) { dst = kVF_Standard; }
		if(!bb_stricmp(src, "kVF_SQL")) { dst = kVF_SQL; }
		if(!bb_stricmp(src, "kVF_Legacy")) { dst = kVF_Legacy; }
		if(!bb_stricmp(src, "kVF_Count")) { dst = kVF_Count; }
	}
	return dst;
}

vfilter_token_type_e vfilter_token_type_e_from_string(const char *src)
{
	vfilter_token_type_e dst = kVFT_Count;
	if(src) {
		if(!bb_stricmp(src, "kVFT_Invalid")) { dst = kVFT_Invalid; }
		if(!bb_stricmp(src, "kVFT_OpenParen")) { dst = kVFT_OpenParen; }
		if(!bb_stricmp(src, "kVFT_CloseParen")) { dst = kVFT_CloseParen; }
		if(!bb_stricmp(src, "kVFT_String")) { dst = kVFT_String; }
		if(!bb_stricmp(src, "kVFT_LessThan")) { dst = kVFT_LessThan; }
		if(!bb_stricmp(src, "kVFT_LessThanEquals")) { dst = kVFT_LessThanEquals; }
		if(!bb_stricmp(src, "kVFT_Equals")) { dst = kVFT_Equals; }
		if(!bb_stricmp(src, "kVFT_NotEquals")) { dst = kVFT_NotEquals; }
		if(!bb_stricmp(src, "kVFT_GreaterThan")) { dst = kVFT_GreaterThan; }
		if(!bb_stricmp(src, "kVFT_GreaterThanEquals")) { dst = kVFT_GreaterThanEquals; }
		if(!bb_stricmp(src, "kVFT_Matches")) { dst = kVFT_Matches; }
		if(!bb_stricmp(src, "kVFT_And")) { dst = kVFT_And; }
		if(!bb_stricmp(src, "kVFT_Or")) { dst = kVFT_Or; }
		if(!bb_stricmp(src, "kVFT_Not")) { dst = kVFT_Not; }
		if(!bb_stricmp(src, "kVFT_Contains")) { dst = kVFT_Contains; }
		if(!bb_stricmp(src, "kVFT_StartsWith")) { dst = kVFT_StartsWith; }
		if(!bb_stricmp(src, "kVFT_EndsWith")) { dst = kVFT_EndsWith; }
		if(!bb_stricmp(src, "kVFT_DeltaMillisecondsAbsolute")) { dst = kVFT_DeltaMillisecondsAbsolute; }
		if(!bb_stricmp(src, "kVFT_DeltaMillisecondsViewRelative")) { dst = kVFT_DeltaMillisecondsViewRelative; }
		if(!bb_stricmp(src, "kVFT_Filename")) { dst = kVFT_Filename; }
		if(!bb_stricmp(src, "kVFT_Thread")) { dst = kVFT_Thread; }
		if(!bb_stricmp(src, "kVFT_PIEInstance")) { dst = kVFT_PIEInstance; }
		if(!bb_stricmp(src, "kVFT_Category")) { dst = kVFT_Category; }
		if(!bb_stricmp(src, "kVFT_Verbosity")) { dst = kVFT_Verbosity; }
		if(!bb_stricmp(src, "kVFT_Text")) { dst = kVFT_Text; }
		if(!bb_stricmp(src, "kVFT_Number")) { dst = kVFT_Number; }
		if(!bb_stricmp(src, "kVFT_NamedFilter")) { dst = kVFT_NamedFilter; }
		if(!bb_stricmp(src, "kVFT_Count")) { dst = kVFT_Count; }
	}
	return dst;
}

//////////////////////////////////////////////////////////////////////////

const char *string_from_vfilter_type_e(const vfilter_type_e src)
{
	switch(src) {
		case kVF_Standard: return "kVF_Standard"; break;
		case kVF_SQL: return "kVF_SQL"; break;
		case kVF_Legacy: return "kVF_Legacy"; break;
		case kVF_Count: return "kVF_Count"; break;
	}
	return "";
}

const char *string_from_vfilter_token_type_e(const vfilter_token_type_e src)
{
	switch(src) {
		case kVFT_Invalid: return "kVFT_Invalid"; break;
		case kVFT_OpenParen: return "kVFT_OpenParen"; break;
		case kVFT_CloseParen: return "kVFT_CloseParen"; break;
		case kVFT_String: return "kVFT_String"; break;
		case kVFT_LessThan: return "kVFT_LessThan"; break;
		case kVFT_LessThanEquals: return "kVFT_LessThanEquals"; break;
		case kVFT_Equals: return "kVFT_Equals"; break;
		case kVFT_NotEquals: return "kVFT_NotEquals"; break;
		case kVFT_GreaterThan: return "kVFT_GreaterThan"; break;
		case kVFT_GreaterThanEquals: return "kVFT_GreaterThanEquals"; break;
		case kVFT_Matches: return "kVFT_Matches"; break;
		case kVFT_And: return "kVFT_And"; break;
		case kVFT_Or: return "kVFT_Or"; break;
		case kVFT_Not: return "kVFT_Not"; break;
		case kVFT_Contains: return "kVFT_Contains"; break;
		case kVFT_StartsWith: return "kVFT_StartsWith"; break;
		case kVFT_EndsWith: return "kVFT_EndsWith"; break;
		case kVFT_DeltaMillisecondsAbsolute: return "kVFT_DeltaMillisecondsAbsolute"; break;
		case kVFT_DeltaMillisecondsViewRelative: return "kVFT_DeltaMillisecondsViewRelative"; break;
		case kVFT_Filename: return "kVFT_Filename"; break;
		case kVFT_Thread: return "kVFT_Thread"; break;
		case kVFT_PIEInstance: return "kVFT_PIEInstance"; break;
		case kVFT_Category: return "kVFT_Category"; break;
		case kVFT_Verbosity: return "kVFT_Verbosity"; break;
		case kVFT_Text: return "kVFT_Text"; break;
		case kVFT_Number: return "kVFT_Number"; break;
		case kVFT_NamedFilter: return "kVFT_NamedFilter"; break;
		case kVFT_Count: return "kVFT_Count"; break;
	}
	return "";
}

//////////////////////////////////////////////////////////////////////////
