// Copyright (c) 2012-2023 Matt Campbell
// MIT license (see License.txt)

// AUTOGENERATED FILE - DO NOT EDIT

// clang-format off

#pragma once

#include "bb_types.h"

#if defined(__cplusplus)
extern "C" {
#endif

struct sb_s;
struct sbs_s;
struct sdictEntry_s;
struct sdict_s;
struct tag_sdicts;
struct uuid_node_s;
struct vfilter_token_s;
struct vfilter_tokens_s;
struct vfilter_error_s;
struct vfilter_result_s;
struct vfilter_results_s;
struct named_vfilters_s;
struct vfilter_s;

typedef struct sb_s sb_t;
typedef struct sbs_s sbs_t;
typedef struct sdictEntry_s sdictEntry_t;
typedef struct sdict_s sdict_t;
typedef struct tag_sdicts sdicts;
typedef struct uuid_node_s uuid_node_t;
typedef struct vfilter_token_s vfilter_token_t;
typedef struct vfilter_tokens_s vfilter_tokens_t;
typedef struct vfilter_error_s vfilter_error_t;
typedef struct vfilter_result_s vfilter_result_t;
typedef struct vfilter_results_s vfilter_results_t;
typedef struct named_vfilters_s named_vfilters_t;
typedef struct vfilter_s vfilter_t;

void sb_reset_from_loc(const char *file, int line, sb_t *val);
void sbs_reset_from_loc(const char *file, int line, sbs_t *val);
void sdictEntry_reset(sdictEntry_t *val);
void sdict_reset(sdict_t *val);
void sdicts_reset(sdicts *val);
void uuid_node_reset(uuid_node_t *val);
void vfilter_token_reset(vfilter_token_t *val);
void vfilter_tokens_reset(vfilter_tokens_t *val);
void vfilter_error_reset(vfilter_error_t *val);
void vfilter_result_reset(vfilter_result_t *val);
void vfilter_results_reset(vfilter_results_t *val);
void named_vfilters_reset(named_vfilters_t *val);
void vfilter_reset(vfilter_t *val);

#if !defined(__cplusplus) || defined(DECLARE_sb_clone)
sb_t sb_clone_from_loc(const char *file, int line, const sb_t *src);
#endif
#if !defined(__cplusplus) || defined(DECLARE_sbs_clone)
sbs_t sbs_clone_from_loc(const char *file, int line, const sbs_t *src);
#endif
#if !defined(__cplusplus) || defined(DECLARE_sdictEntry_clone)
sdictEntry_t sdictEntry_clone(const sdictEntry_t *src);
#endif
#if !defined(__cplusplus) || defined(DECLARE_sdict_clone)
sdict_t sdict_clone(const sdict_t *src);
#endif
#if !defined(__cplusplus) || defined(DECLARE_sdicts_clone)
sdicts sdicts_clone(const sdicts *src);
#endif
#if !defined(__cplusplus) || defined(DECLARE_uuid_node_clone)
uuid_node_t uuid_node_clone(const uuid_node_t *src);
#endif
#if !defined(__cplusplus) || defined(DECLARE_vfilter_token_clone)
vfilter_token_t vfilter_token_clone(const vfilter_token_t *src);
#endif
#if !defined(__cplusplus) || defined(DECLARE_vfilter_tokens_clone)
vfilter_tokens_t vfilter_tokens_clone(const vfilter_tokens_t *src);
#endif
#if !defined(__cplusplus) || defined(DECLARE_vfilter_error_clone)
vfilter_error_t vfilter_error_clone(const vfilter_error_t *src);
#endif
#if !defined(__cplusplus) || defined(DECLARE_vfilter_result_clone)
vfilter_result_t vfilter_result_clone(const vfilter_result_t *src);
#endif
#if !defined(__cplusplus) || defined(DECLARE_vfilter_results_clone)
vfilter_results_t vfilter_results_clone(const vfilter_results_t *src);
#endif
#if !defined(__cplusplus) || defined(DECLARE_named_vfilters_clone)
named_vfilters_t named_vfilters_clone(const named_vfilters_t *src);
#endif
#if !defined(__cplusplus) || defined(DECLARE_vfilter_clone)
vfilter_t vfilter_clone(const vfilter_t *src);
#endif

#if defined(__cplusplus)
} // extern "C"
#endif

#if !defined(sb_reset)
#define sb_reset(var) sb_reset_from_loc(__FILE__, __LINE__, var);
#endif
#if !defined(sbs_reset)
#define sbs_reset(var) sbs_reset_from_loc(__FILE__, __LINE__, var);
#endif

#if !defined(sb_clone)
#define sb_clone(var) sb_clone_from_loc(__FILE__, __LINE__, var);
#endif
#if !defined(sbs_clone)
#define sbs_clone(var) sbs_clone_from_loc(__FILE__, __LINE__, var);
#endif
