// Copyright (c) Matt Campbell
// MIT license (see License.txt)

// AUTOGENERATED FILE - DO NOT EDIT

// clang-format off

#include "bboxtolog_json_generated.h"
#include "bb_array.h"
#include "bb_string.h"
#include "json_utils.h"
#include "va.h"

#include "bboxtolog_utils.h"
#include "bbstats.h"
#include "sb.h"
#include "sdict.h"
#include "standalone_theme_config.h"
#include "uuid_rfc4122/sysdep.h"
#include "view_filter.h"

//////////////////////////////////////////////////////////////////////////

color_config_t json_deserialize_color_config_t(JSON_Value *src)
{
	color_config_t dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			dst.colorName = json_deserialize_styleColor_e(json_object_get_value(obj, "colorName"));
			dst.r = (u8)json_object_get_number(obj, "r");
			dst.g = (u8)json_object_get_number(obj, "g");
			dst.b = (u8)json_object_get_number(obj, "b");
			dst.a = (u8)json_object_get_number(obj, "a");
			dst.bTextShadows = json_object_get_boolean_safe(obj, "bTextShadows");
			for(u32 i = 0; i < BB_ARRAYSIZE(dst.pad); ++i) {
				dst.pad[i] = (u8)json_object_get_number(obj, va("pad.%u", i));
			}
		}
	}
	return dst;
}

colors_config_t json_deserialize_colors_config_t(JSON_Value *src)
{
	colors_config_t dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Array *arr = json_value_get_array(src);
		if(arr) {
			for(u32 i = 0; i < json_array_get_count(arr); ++i) {
				bba_push(dst, json_deserialize_color_config_t(json_array_get_value(arr, i)));
			}
		}
	}
	return dst;
}

theme_config_t json_deserialize_theme_config_t(JSON_Value *src)
{
	theme_config_t dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			dst.colors = json_deserialize_colors_config_t(json_object_get_value(obj, "colors"));
		}
	}
	return dst;
}

//////////////////////////////////////////////////////////////////////////

JSON_Value *json_serialize_color_config_t(const color_config_t *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		json_object_set_value(obj, "colorName", json_serialize_styleColor_e(src->colorName));
		json_object_set_number(obj, "r", src->r);
		json_object_set_number(obj, "g", src->g);
		json_object_set_number(obj, "b", src->b);
		json_object_set_number(obj, "a", src->a);
		json_object_set_boolean(obj, "bTextShadows", src->bTextShadows);
		for(u32 i = 0; i < BB_ARRAYSIZE(src->pad); ++i) {
			json_object_set_number(obj, va("pad.%u", i), src->pad[i]);
		}
	}
	return val;
}

JSON_Value *json_serialize_colors_config_t(const colors_config_t *src)
{
	JSON_Value *val = json_value_init_array();
	JSON_Array *arr = json_value_get_array(val);
	if(arr) {
		for(u32 i = 0; i < src->count; ++i) {
			JSON_Value *child = json_serialize_color_config_t(src->data + i);
			if(child) {
				json_array_append_value(arr, child);
			}
		}
	}
	return val;
}

JSON_Value *json_serialize_theme_config_t(const theme_config_t *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		json_object_set_value(obj, "colors", json_serialize_colors_config_t(&src->colors));
	}
	return val;
}

//////////////////////////////////////////////////////////////////////////

styleColor_e json_deserialize_styleColor_e(JSON_Value *src)
{
	styleColor_e dst = kStyleColor_Count;
	if(src) {
		const char *str = json_value_get_string(src);
		if(str) {
			if(!bb_stricmp(str, "kStyleColor_kBBColor_Default")) { dst = kStyleColor_kBBColor_Default; }
			if(!bb_stricmp(str, "kStyleColor_kBBColor_Evergreen_Black")) { dst = kStyleColor_kBBColor_Evergreen_Black; }
			if(!bb_stricmp(str, "kStyleColor_kBBColor_Evergreen_Red")) { dst = kStyleColor_kBBColor_Evergreen_Red; }
			if(!bb_stricmp(str, "kStyleColor_kBBColor_Evergreen_Green")) { dst = kStyleColor_kBBColor_Evergreen_Green; }
			if(!bb_stricmp(str, "kStyleColor_kBBColor_Evergreen_Yellow")) { dst = kStyleColor_kBBColor_Evergreen_Yellow; }
			if(!bb_stricmp(str, "kStyleColor_kBBColor_Evergreen_Blue")) { dst = kStyleColor_kBBColor_Evergreen_Blue; }
			if(!bb_stricmp(str, "kStyleColor_kBBColor_Evergreen_Cyan")) { dst = kStyleColor_kBBColor_Evergreen_Cyan; }
			if(!bb_stricmp(str, "kStyleColor_kBBColor_Evergreen_Pink")) { dst = kStyleColor_kBBColor_Evergreen_Pink; }
			if(!bb_stricmp(str, "kStyleColor_kBBColor_Evergreen_White")) { dst = kStyleColor_kBBColor_Evergreen_White; }
			if(!bb_stricmp(str, "kStyleColor_kBBColor_Evergreen_LightBlue")) { dst = kStyleColor_kBBColor_Evergreen_LightBlue; }
			if(!bb_stricmp(str, "kStyleColor_kBBColor_Evergreen_Orange")) { dst = kStyleColor_kBBColor_Evergreen_Orange; }
			if(!bb_stricmp(str, "kStyleColor_kBBColor_Evergreen_LightBlueAlt")) { dst = kStyleColor_kBBColor_Evergreen_LightBlueAlt; }
			if(!bb_stricmp(str, "kStyleColor_kBBColor_Evergreen_OrangeAlt")) { dst = kStyleColor_kBBColor_Evergreen_OrangeAlt; }
			if(!bb_stricmp(str, "kStyleColor_kBBColor_Evergreen_MediumBlue")) { dst = kStyleColor_kBBColor_Evergreen_MediumBlue; }
			if(!bb_stricmp(str, "kStyleColor_kBBColor_Evergreen_Amber")) { dst = kStyleColor_kBBColor_Evergreen_Amber; }
			if(!bb_stricmp(str, "kStyleColor_kBBColor_UE4_Black")) { dst = kStyleColor_kBBColor_UE4_Black; }
			if(!bb_stricmp(str, "kStyleColor_kBBColor_UE4_DarkRed")) { dst = kStyleColor_kBBColor_UE4_DarkRed; }
			if(!bb_stricmp(str, "kStyleColor_kBBColor_UE4_DarkGreen")) { dst = kStyleColor_kBBColor_UE4_DarkGreen; }
			if(!bb_stricmp(str, "kStyleColor_kBBColor_UE4_DarkBlue")) { dst = kStyleColor_kBBColor_UE4_DarkBlue; }
			if(!bb_stricmp(str, "kStyleColor_kBBColor_UE4_DarkYellow")) { dst = kStyleColor_kBBColor_UE4_DarkYellow; }
			if(!bb_stricmp(str, "kStyleColor_kBBColor_UE4_DarkCyan")) { dst = kStyleColor_kBBColor_UE4_DarkCyan; }
			if(!bb_stricmp(str, "kStyleColor_kBBColor_UE4_DarkPurple")) { dst = kStyleColor_kBBColor_UE4_DarkPurple; }
			if(!bb_stricmp(str, "kStyleColor_kBBColor_UE4_DarkWhite")) { dst = kStyleColor_kBBColor_UE4_DarkWhite; }
			if(!bb_stricmp(str, "kStyleColor_kBBColor_UE4_Red")) { dst = kStyleColor_kBBColor_UE4_Red; }
			if(!bb_stricmp(str, "kStyleColor_kBBColor_UE4_Green")) { dst = kStyleColor_kBBColor_UE4_Green; }
			if(!bb_stricmp(str, "kStyleColor_kBBColor_UE4_Blue")) { dst = kStyleColor_kBBColor_UE4_Blue; }
			if(!bb_stricmp(str, "kStyleColor_kBBColor_UE4_Yellow")) { dst = kStyleColor_kBBColor_UE4_Yellow; }
			if(!bb_stricmp(str, "kStyleColor_kBBColor_UE4_Cyan")) { dst = kStyleColor_kBBColor_UE4_Cyan; }
			if(!bb_stricmp(str, "kStyleColor_kBBColor_UE4_Purple")) { dst = kStyleColor_kBBColor_UE4_Purple; }
			if(!bb_stricmp(str, "kStyleColor_kBBColor_UE4_White")) { dst = kStyleColor_kBBColor_UE4_White; }
			if(!bb_stricmp(str, "kStyleColor_ActiveSession")) { dst = kStyleColor_ActiveSession; }
			if(!bb_stricmp(str, "kStyleColor_InactiveSession")) { dst = kStyleColor_InactiveSession; }
			if(!bb_stricmp(str, "kStyleColor_LogLevel_VeryVerbose")) { dst = kStyleColor_LogLevel_VeryVerbose; }
			if(!bb_stricmp(str, "kStyleColor_LogLevel_Verbose")) { dst = kStyleColor_LogLevel_Verbose; }
			if(!bb_stricmp(str, "kStyleColor_LogLevel_Log")) { dst = kStyleColor_LogLevel_Log; }
			if(!bb_stricmp(str, "kStyleColor_LogLevel_Display")) { dst = kStyleColor_LogLevel_Display; }
			if(!bb_stricmp(str, "kStyleColor_LogLevel_Warning")) { dst = kStyleColor_LogLevel_Warning; }
			if(!bb_stricmp(str, "kStyleColor_LogLevel_Error")) { dst = kStyleColor_LogLevel_Error; }
			if(!bb_stricmp(str, "kStyleColor_LogLevel_Fatal")) { dst = kStyleColor_LogLevel_Fatal; }
			if(!bb_stricmp(str, "kStyleColor_Multiline")) { dst = kStyleColor_Multiline; }
			if(!bb_stricmp(str, "kStyleColor_LogBackground_Normal")) { dst = kStyleColor_LogBackground_Normal; }
			if(!bb_stricmp(str, "kStyleColor_LogBackground_NormalAlternate0")) { dst = kStyleColor_LogBackground_NormalAlternate0; }
			if(!bb_stricmp(str, "kStyleColor_LogBackground_NormalAlternate1")) { dst = kStyleColor_LogBackground_NormalAlternate1; }
			if(!bb_stricmp(str, "kStyleColor_LogBackground_Bookmarked")) { dst = kStyleColor_LogBackground_Bookmarked; }
			if(!bb_stricmp(str, "kStyleColor_LogBackground_BookmarkedAlternate0")) { dst = kStyleColor_LogBackground_BookmarkedAlternate0; }
			if(!bb_stricmp(str, "kStyleColor_LogBackground_BookmarkedAlternate1")) { dst = kStyleColor_LogBackground_BookmarkedAlternate1; }
			if(!bb_stricmp(str, "kStyleColor_ResizeNormal")) { dst = kStyleColor_ResizeNormal; }
			if(!bb_stricmp(str, "kStyleColor_ResizeHovered")) { dst = kStyleColor_ResizeHovered; }
			if(!bb_stricmp(str, "kStyleColor_ResizeActive")) { dst = kStyleColor_ResizeActive; }
			if(!bb_stricmp(str, "kStyleColor_MessageBoxBackground0")) { dst = kStyleColor_MessageBoxBackground0; }
			if(!bb_stricmp(str, "kStyleColor_MessageBoxBackground1")) { dst = kStyleColor_MessageBoxBackground1; }
			if(!bb_stricmp(str, "kStyleColor_TextShadow")) { dst = kStyleColor_TextShadow; }
			if(!bb_stricmp(str, "kStyleColor_Count")) { dst = kStyleColor_Count; }
		}
	}
	return dst;
}

vfilter_type_e json_deserialize_vfilter_type_e(JSON_Value *src)
{
	vfilter_type_e dst = kVF_Count;
	if(src) {
		const char *str = json_value_get_string(src);
		if(str) {
			if(!bb_stricmp(str, "kVF_Standard")) { dst = kVF_Standard; }
			if(!bb_stricmp(str, "kVF_SQL")) { dst = kVF_SQL; }
			if(!bb_stricmp(str, "kVF_Legacy")) { dst = kVF_Legacy; }
			if(!bb_stricmp(str, "kVF_Count")) { dst = kVF_Count; }
		}
	}
	return dst;
}

vfilter_token_type_e json_deserialize_vfilter_token_type_e(JSON_Value *src)
{
	vfilter_token_type_e dst = kVFT_Count;
	if(src) {
		const char *str = json_value_get_string(src);
		if(str) {
			if(!bb_stricmp(str, "kVFT_Invalid")) { dst = kVFT_Invalid; }
			if(!bb_stricmp(str, "kVFT_OpenParen")) { dst = kVFT_OpenParen; }
			if(!bb_stricmp(str, "kVFT_CloseParen")) { dst = kVFT_CloseParen; }
			if(!bb_stricmp(str, "kVFT_String")) { dst = kVFT_String; }
			if(!bb_stricmp(str, "kVFT_LessThan")) { dst = kVFT_LessThan; }
			if(!bb_stricmp(str, "kVFT_LessThanEquals")) { dst = kVFT_LessThanEquals; }
			if(!bb_stricmp(str, "kVFT_Equals")) { dst = kVFT_Equals; }
			if(!bb_stricmp(str, "kVFT_NotEquals")) { dst = kVFT_NotEquals; }
			if(!bb_stricmp(str, "kVFT_GreaterThan")) { dst = kVFT_GreaterThan; }
			if(!bb_stricmp(str, "kVFT_GreaterThanEquals")) { dst = kVFT_GreaterThanEquals; }
			if(!bb_stricmp(str, "kVFT_Matches")) { dst = kVFT_Matches; }
			if(!bb_stricmp(str, "kVFT_And")) { dst = kVFT_And; }
			if(!bb_stricmp(str, "kVFT_Or")) { dst = kVFT_Or; }
			if(!bb_stricmp(str, "kVFT_Not")) { dst = kVFT_Not; }
			if(!bb_stricmp(str, "kVFT_Contains")) { dst = kVFT_Contains; }
			if(!bb_stricmp(str, "kVFT_StartsWith")) { dst = kVFT_StartsWith; }
			if(!bb_stricmp(str, "kVFT_EndsWith")) { dst = kVFT_EndsWith; }
			if(!bb_stricmp(str, "kVFT_DeltaMillisecondsAbsolute")) { dst = kVFT_DeltaMillisecondsAbsolute; }
			if(!bb_stricmp(str, "kVFT_DeltaMillisecondsViewRelative")) { dst = kVFT_DeltaMillisecondsViewRelative; }
			if(!bb_stricmp(str, "kVFT_Filename")) { dst = kVFT_Filename; }
			if(!bb_stricmp(str, "kVFT_Thread")) { dst = kVFT_Thread; }
			if(!bb_stricmp(str, "kVFT_PIEInstance")) { dst = kVFT_PIEInstance; }
			if(!bb_stricmp(str, "kVFT_Category")) { dst = kVFT_Category; }
			if(!bb_stricmp(str, "kVFT_Verbosity")) { dst = kVFT_Verbosity; }
			if(!bb_stricmp(str, "kVFT_Text")) { dst = kVFT_Text; }
			if(!bb_stricmp(str, "kVFT_Number")) { dst = kVFT_Number; }
			if(!bb_stricmp(str, "kVFT_NamedFilter")) { dst = kVFT_NamedFilter; }
			if(!bb_stricmp(str, "kVFT_Count")) { dst = kVFT_Count; }
		}
	}
	return dst;
}

//////////////////////////////////////////////////////////////////////////

JSON_Value *json_serialize_styleColor_e(const styleColor_e src)
{
	const char *str = "";
	switch(src) {
		case kStyleColor_kBBColor_Default: str = "kStyleColor_kBBColor_Default"; break;
		case kStyleColor_kBBColor_Evergreen_Black: str = "kStyleColor_kBBColor_Evergreen_Black"; break;
		case kStyleColor_kBBColor_Evergreen_Red: str = "kStyleColor_kBBColor_Evergreen_Red"; break;
		case kStyleColor_kBBColor_Evergreen_Green: str = "kStyleColor_kBBColor_Evergreen_Green"; break;
		case kStyleColor_kBBColor_Evergreen_Yellow: str = "kStyleColor_kBBColor_Evergreen_Yellow"; break;
		case kStyleColor_kBBColor_Evergreen_Blue: str = "kStyleColor_kBBColor_Evergreen_Blue"; break;
		case kStyleColor_kBBColor_Evergreen_Cyan: str = "kStyleColor_kBBColor_Evergreen_Cyan"; break;
		case kStyleColor_kBBColor_Evergreen_Pink: str = "kStyleColor_kBBColor_Evergreen_Pink"; break;
		case kStyleColor_kBBColor_Evergreen_White: str = "kStyleColor_kBBColor_Evergreen_White"; break;
		case kStyleColor_kBBColor_Evergreen_LightBlue: str = "kStyleColor_kBBColor_Evergreen_LightBlue"; break;
		case kStyleColor_kBBColor_Evergreen_Orange: str = "kStyleColor_kBBColor_Evergreen_Orange"; break;
		case kStyleColor_kBBColor_Evergreen_LightBlueAlt: str = "kStyleColor_kBBColor_Evergreen_LightBlueAlt"; break;
		case kStyleColor_kBBColor_Evergreen_OrangeAlt: str = "kStyleColor_kBBColor_Evergreen_OrangeAlt"; break;
		case kStyleColor_kBBColor_Evergreen_MediumBlue: str = "kStyleColor_kBBColor_Evergreen_MediumBlue"; break;
		case kStyleColor_kBBColor_Evergreen_Amber: str = "kStyleColor_kBBColor_Evergreen_Amber"; break;
		case kStyleColor_kBBColor_UE4_Black: str = "kStyleColor_kBBColor_UE4_Black"; break;
		case kStyleColor_kBBColor_UE4_DarkRed: str = "kStyleColor_kBBColor_UE4_DarkRed"; break;
		case kStyleColor_kBBColor_UE4_DarkGreen: str = "kStyleColor_kBBColor_UE4_DarkGreen"; break;
		case kStyleColor_kBBColor_UE4_DarkBlue: str = "kStyleColor_kBBColor_UE4_DarkBlue"; break;
		case kStyleColor_kBBColor_UE4_DarkYellow: str = "kStyleColor_kBBColor_UE4_DarkYellow"; break;
		case kStyleColor_kBBColor_UE4_DarkCyan: str = "kStyleColor_kBBColor_UE4_DarkCyan"; break;
		case kStyleColor_kBBColor_UE4_DarkPurple: str = "kStyleColor_kBBColor_UE4_DarkPurple"; break;
		case kStyleColor_kBBColor_UE4_DarkWhite: str = "kStyleColor_kBBColor_UE4_DarkWhite"; break;
		case kStyleColor_kBBColor_UE4_Red: str = "kStyleColor_kBBColor_UE4_Red"; break;
		case kStyleColor_kBBColor_UE4_Green: str = "kStyleColor_kBBColor_UE4_Green"; break;
		case kStyleColor_kBBColor_UE4_Blue: str = "kStyleColor_kBBColor_UE4_Blue"; break;
		case kStyleColor_kBBColor_UE4_Yellow: str = "kStyleColor_kBBColor_UE4_Yellow"; break;
		case kStyleColor_kBBColor_UE4_Cyan: str = "kStyleColor_kBBColor_UE4_Cyan"; break;
		case kStyleColor_kBBColor_UE4_Purple: str = "kStyleColor_kBBColor_UE4_Purple"; break;
		case kStyleColor_kBBColor_UE4_White: str = "kStyleColor_kBBColor_UE4_White"; break;
		case kStyleColor_ActiveSession: str = "kStyleColor_ActiveSession"; break;
		case kStyleColor_InactiveSession: str = "kStyleColor_InactiveSession"; break;
		case kStyleColor_LogLevel_VeryVerbose: str = "kStyleColor_LogLevel_VeryVerbose"; break;
		case kStyleColor_LogLevel_Verbose: str = "kStyleColor_LogLevel_Verbose"; break;
		case kStyleColor_LogLevel_Log: str = "kStyleColor_LogLevel_Log"; break;
		case kStyleColor_LogLevel_Display: str = "kStyleColor_LogLevel_Display"; break;
		case kStyleColor_LogLevel_Warning: str = "kStyleColor_LogLevel_Warning"; break;
		case kStyleColor_LogLevel_Error: str = "kStyleColor_LogLevel_Error"; break;
		case kStyleColor_LogLevel_Fatal: str = "kStyleColor_LogLevel_Fatal"; break;
		case kStyleColor_Multiline: str = "kStyleColor_Multiline"; break;
		case kStyleColor_LogBackground_Normal: str = "kStyleColor_LogBackground_Normal"; break;
		case kStyleColor_LogBackground_NormalAlternate0: str = "kStyleColor_LogBackground_NormalAlternate0"; break;
		case kStyleColor_LogBackground_NormalAlternate1: str = "kStyleColor_LogBackground_NormalAlternate1"; break;
		case kStyleColor_LogBackground_Bookmarked: str = "kStyleColor_LogBackground_Bookmarked"; break;
		case kStyleColor_LogBackground_BookmarkedAlternate0: str = "kStyleColor_LogBackground_BookmarkedAlternate0"; break;
		case kStyleColor_LogBackground_BookmarkedAlternate1: str = "kStyleColor_LogBackground_BookmarkedAlternate1"; break;
		case kStyleColor_ResizeNormal: str = "kStyleColor_ResizeNormal"; break;
		case kStyleColor_ResizeHovered: str = "kStyleColor_ResizeHovered"; break;
		case kStyleColor_ResizeActive: str = "kStyleColor_ResizeActive"; break;
		case kStyleColor_MessageBoxBackground0: str = "kStyleColor_MessageBoxBackground0"; break;
		case kStyleColor_MessageBoxBackground1: str = "kStyleColor_MessageBoxBackground1"; break;
		case kStyleColor_TextShadow: str = "kStyleColor_TextShadow"; break;
		case kStyleColor_Count: str = "kStyleColor_Count"; break;
	}
	JSON_Value *val = json_value_init_string(str);
	return val;
}

JSON_Value *json_serialize_vfilter_type_e(const vfilter_type_e src)
{
	const char *str = "";
	switch(src) {
		case kVF_Standard: str = "kVF_Standard"; break;
		case kVF_SQL: str = "kVF_SQL"; break;
		case kVF_Legacy: str = "kVF_Legacy"; break;
		case kVF_Count: str = "kVF_Count"; break;
	}
	JSON_Value *val = json_value_init_string(str);
	return val;
}

JSON_Value *json_serialize_vfilter_token_type_e(const vfilter_token_type_e src)
{
	const char *str = "";
	switch(src) {
		case kVFT_Invalid: str = "kVFT_Invalid"; break;
		case kVFT_OpenParen: str = "kVFT_OpenParen"; break;
		case kVFT_CloseParen: str = "kVFT_CloseParen"; break;
		case kVFT_String: str = "kVFT_String"; break;
		case kVFT_LessThan: str = "kVFT_LessThan"; break;
		case kVFT_LessThanEquals: str = "kVFT_LessThanEquals"; break;
		case kVFT_Equals: str = "kVFT_Equals"; break;
		case kVFT_NotEquals: str = "kVFT_NotEquals"; break;
		case kVFT_GreaterThan: str = "kVFT_GreaterThan"; break;
		case kVFT_GreaterThanEquals: str = "kVFT_GreaterThanEquals"; break;
		case kVFT_Matches: str = "kVFT_Matches"; break;
		case kVFT_And: str = "kVFT_And"; break;
		case kVFT_Or: str = "kVFT_Or"; break;
		case kVFT_Not: str = "kVFT_Not"; break;
		case kVFT_Contains: str = "kVFT_Contains"; break;
		case kVFT_StartsWith: str = "kVFT_StartsWith"; break;
		case kVFT_EndsWith: str = "kVFT_EndsWith"; break;
		case kVFT_DeltaMillisecondsAbsolute: str = "kVFT_DeltaMillisecondsAbsolute"; break;
		case kVFT_DeltaMillisecondsViewRelative: str = "kVFT_DeltaMillisecondsViewRelative"; break;
		case kVFT_Filename: str = "kVFT_Filename"; break;
		case kVFT_Thread: str = "kVFT_Thread"; break;
		case kVFT_PIEInstance: str = "kVFT_PIEInstance"; break;
		case kVFT_Category: str = "kVFT_Category"; break;
		case kVFT_Verbosity: str = "kVFT_Verbosity"; break;
		case kVFT_Text: str = "kVFT_Text"; break;
		case kVFT_Number: str = "kVFT_Number"; break;
		case kVFT_NamedFilter: str = "kVFT_NamedFilter"; break;
		case kVFT_Count: str = "kVFT_Count"; break;
	}
	JSON_Value *val = json_value_init_string(str);
	return val;
}

//////////////////////////////////////////////////////////////////////////

styleColor_e styleColor_e_from_string(const char *src)
{
	styleColor_e dst = kStyleColor_Count;
	if(src) {
		if(!bb_stricmp(src, "kStyleColor_kBBColor_Default")) { dst = kStyleColor_kBBColor_Default; }
		if(!bb_stricmp(src, "kStyleColor_kBBColor_Evergreen_Black")) { dst = kStyleColor_kBBColor_Evergreen_Black; }
		if(!bb_stricmp(src, "kStyleColor_kBBColor_Evergreen_Red")) { dst = kStyleColor_kBBColor_Evergreen_Red; }
		if(!bb_stricmp(src, "kStyleColor_kBBColor_Evergreen_Green")) { dst = kStyleColor_kBBColor_Evergreen_Green; }
		if(!bb_stricmp(src, "kStyleColor_kBBColor_Evergreen_Yellow")) { dst = kStyleColor_kBBColor_Evergreen_Yellow; }
		if(!bb_stricmp(src, "kStyleColor_kBBColor_Evergreen_Blue")) { dst = kStyleColor_kBBColor_Evergreen_Blue; }
		if(!bb_stricmp(src, "kStyleColor_kBBColor_Evergreen_Cyan")) { dst = kStyleColor_kBBColor_Evergreen_Cyan; }
		if(!bb_stricmp(src, "kStyleColor_kBBColor_Evergreen_Pink")) { dst = kStyleColor_kBBColor_Evergreen_Pink; }
		if(!bb_stricmp(src, "kStyleColor_kBBColor_Evergreen_White")) { dst = kStyleColor_kBBColor_Evergreen_White; }
		if(!bb_stricmp(src, "kStyleColor_kBBColor_Evergreen_LightBlue")) { dst = kStyleColor_kBBColor_Evergreen_LightBlue; }
		if(!bb_stricmp(src, "kStyleColor_kBBColor_Evergreen_Orange")) { dst = kStyleColor_kBBColor_Evergreen_Orange; }
		if(!bb_stricmp(src, "kStyleColor_kBBColor_Evergreen_LightBlueAlt")) { dst = kStyleColor_kBBColor_Evergreen_LightBlueAlt; }
		if(!bb_stricmp(src, "kStyleColor_kBBColor_Evergreen_OrangeAlt")) { dst = kStyleColor_kBBColor_Evergreen_OrangeAlt; }
		if(!bb_stricmp(src, "kStyleColor_kBBColor_Evergreen_MediumBlue")) { dst = kStyleColor_kBBColor_Evergreen_MediumBlue; }
		if(!bb_stricmp(src, "kStyleColor_kBBColor_Evergreen_Amber")) { dst = kStyleColor_kBBColor_Evergreen_Amber; }
		if(!bb_stricmp(src, "kStyleColor_kBBColor_UE4_Black")) { dst = kStyleColor_kBBColor_UE4_Black; }
		if(!bb_stricmp(src, "kStyleColor_kBBColor_UE4_DarkRed")) { dst = kStyleColor_kBBColor_UE4_DarkRed; }
		if(!bb_stricmp(src, "kStyleColor_kBBColor_UE4_DarkGreen")) { dst = kStyleColor_kBBColor_UE4_DarkGreen; }
		if(!bb_stricmp(src, "kStyleColor_kBBColor_UE4_DarkBlue")) { dst = kStyleColor_kBBColor_UE4_DarkBlue; }
		if(!bb_stricmp(src, "kStyleColor_kBBColor_UE4_DarkYellow")) { dst = kStyleColor_kBBColor_UE4_DarkYellow; }
		if(!bb_stricmp(src, "kStyleColor_kBBColor_UE4_DarkCyan")) { dst = kStyleColor_kBBColor_UE4_DarkCyan; }
		if(!bb_stricmp(src, "kStyleColor_kBBColor_UE4_DarkPurple")) { dst = kStyleColor_kBBColor_UE4_DarkPurple; }
		if(!bb_stricmp(src, "kStyleColor_kBBColor_UE4_DarkWhite")) { dst = kStyleColor_kBBColor_UE4_DarkWhite; }
		if(!bb_stricmp(src, "kStyleColor_kBBColor_UE4_Red")) { dst = kStyleColor_kBBColor_UE4_Red; }
		if(!bb_stricmp(src, "kStyleColor_kBBColor_UE4_Green")) { dst = kStyleColor_kBBColor_UE4_Green; }
		if(!bb_stricmp(src, "kStyleColor_kBBColor_UE4_Blue")) { dst = kStyleColor_kBBColor_UE4_Blue; }
		if(!bb_stricmp(src, "kStyleColor_kBBColor_UE4_Yellow")) { dst = kStyleColor_kBBColor_UE4_Yellow; }
		if(!bb_stricmp(src, "kStyleColor_kBBColor_UE4_Cyan")) { dst = kStyleColor_kBBColor_UE4_Cyan; }
		if(!bb_stricmp(src, "kStyleColor_kBBColor_UE4_Purple")) { dst = kStyleColor_kBBColor_UE4_Purple; }
		if(!bb_stricmp(src, "kStyleColor_kBBColor_UE4_White")) { dst = kStyleColor_kBBColor_UE4_White; }
		if(!bb_stricmp(src, "kStyleColor_ActiveSession")) { dst = kStyleColor_ActiveSession; }
		if(!bb_stricmp(src, "kStyleColor_InactiveSession")) { dst = kStyleColor_InactiveSession; }
		if(!bb_stricmp(src, "kStyleColor_LogLevel_VeryVerbose")) { dst = kStyleColor_LogLevel_VeryVerbose; }
		if(!bb_stricmp(src, "kStyleColor_LogLevel_Verbose")) { dst = kStyleColor_LogLevel_Verbose; }
		if(!bb_stricmp(src, "kStyleColor_LogLevel_Log")) { dst = kStyleColor_LogLevel_Log; }
		if(!bb_stricmp(src, "kStyleColor_LogLevel_Display")) { dst = kStyleColor_LogLevel_Display; }
		if(!bb_stricmp(src, "kStyleColor_LogLevel_Warning")) { dst = kStyleColor_LogLevel_Warning; }
		if(!bb_stricmp(src, "kStyleColor_LogLevel_Error")) { dst = kStyleColor_LogLevel_Error; }
		if(!bb_stricmp(src, "kStyleColor_LogLevel_Fatal")) { dst = kStyleColor_LogLevel_Fatal; }
		if(!bb_stricmp(src, "kStyleColor_Multiline")) { dst = kStyleColor_Multiline; }
		if(!bb_stricmp(src, "kStyleColor_LogBackground_Normal")) { dst = kStyleColor_LogBackground_Normal; }
		if(!bb_stricmp(src, "kStyleColor_LogBackground_NormalAlternate0")) { dst = kStyleColor_LogBackground_NormalAlternate0; }
		if(!bb_stricmp(src, "kStyleColor_LogBackground_NormalAlternate1")) { dst = kStyleColor_LogBackground_NormalAlternate1; }
		if(!bb_stricmp(src, "kStyleColor_LogBackground_Bookmarked")) { dst = kStyleColor_LogBackground_Bookmarked; }
		if(!bb_stricmp(src, "kStyleColor_LogBackground_BookmarkedAlternate0")) { dst = kStyleColor_LogBackground_BookmarkedAlternate0; }
		if(!bb_stricmp(src, "kStyleColor_LogBackground_BookmarkedAlternate1")) { dst = kStyleColor_LogBackground_BookmarkedAlternate1; }
		if(!bb_stricmp(src, "kStyleColor_ResizeNormal")) { dst = kStyleColor_ResizeNormal; }
		if(!bb_stricmp(src, "kStyleColor_ResizeHovered")) { dst = kStyleColor_ResizeHovered; }
		if(!bb_stricmp(src, "kStyleColor_ResizeActive")) { dst = kStyleColor_ResizeActive; }
		if(!bb_stricmp(src, "kStyleColor_MessageBoxBackground0")) { dst = kStyleColor_MessageBoxBackground0; }
		if(!bb_stricmp(src, "kStyleColor_MessageBoxBackground1")) { dst = kStyleColor_MessageBoxBackground1; }
		if(!bb_stricmp(src, "kStyleColor_TextShadow")) { dst = kStyleColor_TextShadow; }
		if(!bb_stricmp(src, "kStyleColor_Count")) { dst = kStyleColor_Count; }
	}
	return dst;
}

vfilter_type_e vfilter_type_e_from_string(const char *src)
{
	vfilter_type_e dst = kVF_Count;
	if(src) {
		if(!bb_stricmp(src, "kVF_Standard")) { dst = kVF_Standard; }
		if(!bb_stricmp(src, "kVF_SQL")) { dst = kVF_SQL; }
		if(!bb_stricmp(src, "kVF_Legacy")) { dst = kVF_Legacy; }
		if(!bb_stricmp(src, "kVF_Count")) { dst = kVF_Count; }
	}
	return dst;
}

vfilter_token_type_e vfilter_token_type_e_from_string(const char *src)
{
	vfilter_token_type_e dst = kVFT_Count;
	if(src) {
		if(!bb_stricmp(src, "kVFT_Invalid")) { dst = kVFT_Invalid; }
		if(!bb_stricmp(src, "kVFT_OpenParen")) { dst = kVFT_OpenParen; }
		if(!bb_stricmp(src, "kVFT_CloseParen")) { dst = kVFT_CloseParen; }
		if(!bb_stricmp(src, "kVFT_String")) { dst = kVFT_String; }
		if(!bb_stricmp(src, "kVFT_LessThan")) { dst = kVFT_LessThan; }
		if(!bb_stricmp(src, "kVFT_LessThanEquals")) { dst = kVFT_LessThanEquals; }
		if(!bb_stricmp(src, "kVFT_Equals")) { dst = kVFT_Equals; }
		if(!bb_stricmp(src, "kVFT_NotEquals")) { dst = kVFT_NotEquals; }
		if(!bb_stricmp(src, "kVFT_GreaterThan")) { dst = kVFT_GreaterThan; }
		if(!bb_stricmp(src, "kVFT_GreaterThanEquals")) { dst = kVFT_GreaterThanEquals; }
		if(!bb_stricmp(src, "kVFT_Matches")) { dst = kVFT_Matches; }
		if(!bb_stricmp(src, "kVFT_And")) { dst = kVFT_And; }
		if(!bb_stricmp(src, "kVFT_Or")) { dst = kVFT_Or; }
		if(!bb_stricmp(src, "kVFT_Not")) { dst = kVFT_Not; }
		if(!bb_stricmp(src, "kVFT_Contains")) { dst = kVFT_Contains; }
		if(!bb_stricmp(src, "kVFT_StartsWith")) { dst = kVFT_StartsWith; }
		if(!bb_stricmp(src, "kVFT_EndsWith")) { dst = kVFT_EndsWith; }
		if(!bb_stricmp(src, "kVFT_DeltaMillisecondsAbsolute")) { dst = kVFT_DeltaMillisecondsAbsolute; }
		if(!bb_stricmp(src, "kVFT_DeltaMillisecondsViewRelative")) { dst = kVFT_DeltaMillisecondsViewRelative; }
		if(!bb_stricmp(src, "kVFT_Filename")) { dst = kVFT_Filename; }
		if(!bb_stricmp(src, "kVFT_Thread")) { dst = kVFT_Thread; }
		if(!bb_stricmp(src, "kVFT_PIEInstance")) { dst = kVFT_PIEInstance; }
		if(!bb_stricmp(src, "kVFT_Category")) { dst = kVFT_Category; }
		if(!bb_stricmp(src, "kVFT_Verbosity")) { dst = kVFT_Verbosity; }
		if(!bb_stricmp(src, "kVFT_Text")) { dst = kVFT_Text; }
		if(!bb_stricmp(src, "kVFT_Number")) { dst = kVFT_Number; }
		if(!bb_stricmp(src, "kVFT_NamedFilter")) { dst = kVFT_NamedFilter; }
		if(!bb_stricmp(src, "kVFT_Count")) { dst = kVFT_Count; }
	}
	return dst;
}

//////////////////////////////////////////////////////////////////////////

const char *string_from_styleColor_e(const styleColor_e src)
{
	switch(src) {
		case kStyleColor_kBBColor_Default: return "kStyleColor_kBBColor_Default"; break;
		case kStyleColor_kBBColor_Evergreen_Black: return "kStyleColor_kBBColor_Evergreen_Black"; break;
		case kStyleColor_kBBColor_Evergreen_Red: return "kStyleColor_kBBColor_Evergreen_Red"; break;
		case kStyleColor_kBBColor_Evergreen_Green: return "kStyleColor_kBBColor_Evergreen_Green"; break;
		case kStyleColor_kBBColor_Evergreen_Yellow: return "kStyleColor_kBBColor_Evergreen_Yellow"; break;
		case kStyleColor_kBBColor_Evergreen_Blue: return "kStyleColor_kBBColor_Evergreen_Blue"; break;
		case kStyleColor_kBBColor_Evergreen_Cyan: return "kStyleColor_kBBColor_Evergreen_Cyan"; break;
		case kStyleColor_kBBColor_Evergreen_Pink: return "kStyleColor_kBBColor_Evergreen_Pink"; break;
		case kStyleColor_kBBColor_Evergreen_White: return "kStyleColor_kBBColor_Evergreen_White"; break;
		case kStyleColor_kBBColor_Evergreen_LightBlue: return "kStyleColor_kBBColor_Evergreen_LightBlue"; break;
		case kStyleColor_kBBColor_Evergreen_Orange: return "kStyleColor_kBBColor_Evergreen_Orange"; break;
		case kStyleColor_kBBColor_Evergreen_LightBlueAlt: return "kStyleColor_kBBColor_Evergreen_LightBlueAlt"; break;
		case kStyleColor_kBBColor_Evergreen_OrangeAlt: return "kStyleColor_kBBColor_Evergreen_OrangeAlt"; break;
		case kStyleColor_kBBColor_Evergreen_MediumBlue: return "kStyleColor_kBBColor_Evergreen_MediumBlue"; break;
		case kStyleColor_kBBColor_Evergreen_Amber: return "kStyleColor_kBBColor_Evergreen_Amber"; break;
		case kStyleColor_kBBColor_UE4_Black: return "kStyleColor_kBBColor_UE4_Black"; break;
		case kStyleColor_kBBColor_UE4_DarkRed: return "kStyleColor_kBBColor_UE4_DarkRed"; break;
		case kStyleColor_kBBColor_UE4_DarkGreen: return "kStyleColor_kBBColor_UE4_DarkGreen"; break;
		case kStyleColor_kBBColor_UE4_DarkBlue: return "kStyleColor_kBBColor_UE4_DarkBlue"; break;
		case kStyleColor_kBBColor_UE4_DarkYellow: return "kStyleColor_kBBColor_UE4_DarkYellow"; break;
		case kStyleColor_kBBColor_UE4_DarkCyan: return "kStyleColor_kBBColor_UE4_DarkCyan"; break;
		case kStyleColor_kBBColor_UE4_DarkPurple: return "kStyleColor_kBBColor_UE4_DarkPurple"; break;
		case kStyleColor_kBBColor_UE4_DarkWhite: return "kStyleColor_kBBColor_UE4_DarkWhite"; break;
		case kStyleColor_kBBColor_UE4_Red: return "kStyleColor_kBBColor_UE4_Red"; break;
		case kStyleColor_kBBColor_UE4_Green: return "kStyleColor_kBBColor_UE4_Green"; break;
		case kStyleColor_kBBColor_UE4_Blue: return "kStyleColor_kBBColor_UE4_Blue"; break;
		case kStyleColor_kBBColor_UE4_Yellow: return "kStyleColor_kBBColor_UE4_Yellow"; break;
		case kStyleColor_kBBColor_UE4_Cyan: return "kStyleColor_kBBColor_UE4_Cyan"; break;
		case kStyleColor_kBBColor_UE4_Purple: return "kStyleColor_kBBColor_UE4_Purple"; break;
		case kStyleColor_kBBColor_UE4_White: return "kStyleColor_kBBColor_UE4_White"; break;
		case kStyleColor_ActiveSession: return "kStyleColor_ActiveSession"; break;
		case kStyleColor_InactiveSession: return "kStyleColor_InactiveSession"; break;
		case kStyleColor_LogLevel_VeryVerbose: return "kStyleColor_LogLevel_VeryVerbose"; break;
		case kStyleColor_LogLevel_Verbose: return "kStyleColor_LogLevel_Verbose"; break;
		case kStyleColor_LogLevel_Log: return "kStyleColor_LogLevel_Log"; break;
		case kStyleColor_LogLevel_Display: return "kStyleColor_LogLevel_Display"; break;
		case kStyleColor_LogLevel_Warning: return "kStyleColor_LogLevel_Warning"; break;
		case kStyleColor_LogLevel_Error: return "kStyleColor_LogLevel_Error"; break;
		case kStyleColor_LogLevel_Fatal: return "kStyleColor_LogLevel_Fatal"; break;
		case kStyleColor_Multiline: return "kStyleColor_Multiline"; break;
		case kStyleColor_LogBackground_Normal: return "kStyleColor_LogBackground_Normal"; break;
		case kStyleColor_LogBackground_NormalAlternate0: return "kStyleColor_LogBackground_NormalAlternate0"; break;
		case kStyleColor_LogBackground_NormalAlternate1: return "kStyleColor_LogBackground_NormalAlternate1"; break;
		case kStyleColor_LogBackground_Bookmarked: return "kStyleColor_LogBackground_Bookmarked"; break;
		case kStyleColor_LogBackground_BookmarkedAlternate0: return "kStyleColor_LogBackground_BookmarkedAlternate0"; break;
		case kStyleColor_LogBackground_BookmarkedAlternate1: return "kStyleColor_LogBackground_BookmarkedAlternate1"; break;
		case kStyleColor_ResizeNormal: return "kStyleColor_ResizeNormal"; break;
		case kStyleColor_ResizeHovered: return "kStyleColor_ResizeHovered"; break;
		case kStyleColor_ResizeActive: return "kStyleColor_ResizeActive"; break;
		case kStyleColor_MessageBoxBackground0: return "kStyleColor_MessageBoxBackground0"; break;
		case kStyleColor_MessageBoxBackground1: return "kStyleColor_MessageBoxBackground1"; break;
		case kStyleColor_TextShadow: return "kStyleColor_TextShadow"; break;
		case kStyleColor_Count: return "kStyleColor_Count"; break;
	}
	return "";
}

const char *string_from_vfilter_type_e(const vfilter_type_e src)
{
	switch(src) {
		case kVF_Standard: return "kVF_Standard"; break;
		case kVF_SQL: return "kVF_SQL"; break;
		case kVF_Legacy: return "kVF_Legacy"; break;
		case kVF_Count: return "kVF_Count"; break;
	}
	return "";
}

const char *string_from_vfilter_token_type_e(const vfilter_token_type_e src)
{
	switch(src) {
		case kVFT_Invalid: return "kVFT_Invalid"; break;
		case kVFT_OpenParen: return "kVFT_OpenParen"; break;
		case kVFT_CloseParen: return "kVFT_CloseParen"; break;
		case kVFT_String: return "kVFT_String"; break;
		case kVFT_LessThan: return "kVFT_LessThan"; break;
		case kVFT_LessThanEquals: return "kVFT_LessThanEquals"; break;
		case kVFT_Equals: return "kVFT_Equals"; break;
		case kVFT_NotEquals: return "kVFT_NotEquals"; break;
		case kVFT_GreaterThan: return "kVFT_GreaterThan"; break;
		case kVFT_GreaterThanEquals: return "kVFT_GreaterThanEquals"; break;
		case kVFT_Matches: return "kVFT_Matches"; break;
		case kVFT_And: return "kVFT_And"; break;
		case kVFT_Or: return "kVFT_Or"; break;
		case kVFT_Not: return "kVFT_Not"; break;
		case kVFT_Contains: return "kVFT_Contains"; break;
		case kVFT_StartsWith: return "kVFT_StartsWith"; break;
		case kVFT_EndsWith: return "kVFT_EndsWith"; break;
		case kVFT_DeltaMillisecondsAbsolute: return "kVFT_DeltaMillisecondsAbsolute"; break;
		case kVFT_DeltaMillisecondsViewRelative: return "kVFT_DeltaMillisecondsViewRelative"; break;
		case kVFT_Filename: return "kVFT_Filename"; break;
		case kVFT_Thread: return "kVFT_Thread"; break;
		case kVFT_PIEInstance: return "kVFT_PIEInstance"; break;
		case kVFT_Category: return "kVFT_Category"; break;
		case kVFT_Verbosity: return "kVFT_Verbosity"; break;
		case kVFT_Text: return "kVFT_Text"; break;
		case kVFT_Number: return "kVFT_Number"; break;
		case kVFT_NamedFilter: return "kVFT_NamedFilter"; break;
		case kVFT_Count: return "kVFT_Count"; break;
	}
	return "";
}

//////////////////////////////////////////////////////////////////////////
