// Copyright (c) 2012-2019 Matt Campbell
// MIT license (see License.txt)

// AUTOGENERATED FILE - DO NOT EDIT

// clang-format off

#include "bb_json_generated.h"
#include "bbclient/bb_array.h"
#include "json_utils.h"
#include "va.h"

#include "config.h"
#include "fonts.h"
#include "recordings.h"
#include "sb.h"
#include "sdict.h"
#include "site_config.h"
#include "uuid_config.h"
#include "uuid_rfc4122\sysdep.h"
#include "view.h"

//////////////////////////////////////////////////////////////////////////

POINT json_deserialize_POINT(JSON_Value *src)
{
	POINT dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			dst.x = (LONG)json_object_get_number(obj, "x");
			dst.y = (LONG)json_object_get_number(obj, "y");
		}
	}
	return dst;
}

RECT json_deserialize_RECT(JSON_Value *src)
{
	RECT dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			dst.left = (LONG)json_object_get_number(obj, "left");
			dst.top = (LONG)json_object_get_number(obj, "top");
			dst.right = (LONG)json_object_get_number(obj, "right");
			dst.bottom = (LONG)json_object_get_number(obj, "bottom");
		}
	}
	return dst;
}

WINDOWPLACEMENT json_deserialize_WINDOWPLACEMENT(JSON_Value *src)
{
	WINDOWPLACEMENT dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			dst.length = (UINT)json_object_get_number(obj, "length");
			dst.flags = (UINT)json_object_get_number(obj, "flags");
			dst.showCmd = (UINT)json_object_get_number(obj, "showCmd");
			dst.ptMinPosition = json_deserialize_POINT(json_object_get_value(obj, "ptMinPosition"));
			dst.ptMaxPosition = json_deserialize_POINT(json_object_get_value(obj, "ptMaxPosition"));
			dst.rcNormalPosition = json_deserialize_RECT(json_object_get_value(obj, "rcNormalPosition"));
		}
	}
	return dst;
}

configWhitelistEntry_t json_deserialize_configWhitelistEntry_t(JSON_Value *src)
{
	configWhitelistEntry_t dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			dst.allow = json_object_get_boolean_safe(obj, "allow");
			dst.autodetectedDevkit = json_object_get_boolean_safe(obj, "autodetectedDevkit");
			dst.delay = (u32)json_object_get_number(obj, "delay");
			for(u32 i = 0; i < BB_ARRAYSIZE(dst.pad); ++i) {
				dst.pad[i] = (u8)json_object_get_number(obj, va("pad.%u", i));
			}
			dst.addressPlusMask = json_deserialize_sb_t(json_object_get_value(obj, "addressPlusMask"));
			dst.applicationName = json_deserialize_sb_t(json_object_get_value(obj, "applicationName"));
			dst.comment = json_deserialize_sb_t(json_object_get_value(obj, "comment"));
		}
	}
	return dst;
}

configWhitelist_t json_deserialize_configWhitelist_t(JSON_Value *src)
{
	configWhitelist_t dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Array *arr = json_value_get_array(src);
		if(arr) {
			for(u32 i = 0; i < json_array_get_count(arr); ++i) {
				bba_push(dst, json_deserialize_configWhitelistEntry_t(json_array_get_value(arr, i)));
			}
		}
	}
	return dst;
}

openTargetEntry_t json_deserialize_openTargetEntry_t(JSON_Value *src)
{
	openTargetEntry_t dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			dst.displayName = json_deserialize_sb_t(json_object_get_value(obj, "displayName"));
			dst.commandLine = json_deserialize_sb_t(json_object_get_value(obj, "commandLine"));
		}
	}
	return dst;
}

openTargetList_t json_deserialize_openTargetList_t(JSON_Value *src)
{
	openTargetList_t dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Array *arr = json_value_get_array(src);
		if(arr) {
			for(u32 i = 0; i < json_array_get_count(arr); ++i) {
				bba_push(dst, json_deserialize_openTargetEntry_t(json_array_get_value(arr, i)));
			}
		}
	}
	return dst;
}

pathFixupEntry_t json_deserialize_pathFixupEntry_t(JSON_Value *src)
{
	pathFixupEntry_t dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			dst.src = json_deserialize_sb_t(json_object_get_value(obj, "src"));
			dst.dst = json_deserialize_sb_t(json_object_get_value(obj, "dst"));
		}
	}
	return dst;
}

pathFixupList_t json_deserialize_pathFixupList_t(JSON_Value *src)
{
	pathFixupList_t dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Array *arr = json_value_get_array(src);
		if(arr) {
			for(u32 i = 0; i < json_array_get_count(arr); ++i) {
				bba_push(dst, json_deserialize_pathFixupEntry_t(json_array_get_value(arr, i)));
			}
		}
	}
	return dst;
}

tooltipConfig json_deserialize_tooltipConfig(JSON_Value *src)
{
	tooltipConfig dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			dst.enabled = json_object_get_boolean_safe(obj, "enabled");
			dst.overText = json_object_get_boolean_safe(obj, "overText");
			dst.overMisc = json_object_get_boolean_safe(obj, "overMisc");
			dst.onlyOverSelected = json_object_get_boolean_safe(obj, "onlyOverSelected");
			dst.delay = (float)json_object_get_number(obj, "delay");
			for(u32 i = 0; i < BB_ARRAYSIZE(dst.pad); ++i) {
				dst.pad[i] = (u8)json_object_get_number(obj, va("pad.%u", i));
			}
		}
	}
	return dst;
}

config_t json_deserialize_config_t(JSON_Value *src)
{
	config_t dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			dst.whitelist = json_deserialize_configWhitelist_t(json_object_get_value(obj, "whitelist"));
			dst.openTargets = json_deserialize_openTargetList_t(json_object_get_value(obj, "openTargets"));
			dst.pathFixups = json_deserialize_pathFixupList_t(json_object_get_value(obj, "pathFixups"));
			dst.logFontConfig = json_deserialize_fontConfig_t(json_object_get_value(obj, "logFontConfig"));
			dst.uiFontConfig = json_deserialize_fontConfig_t(json_object_get_value(obj, "uiFontConfig"));
			dst.colorscheme = json_deserialize_sb_t(json_object_get_value(obj, "colorscheme"));
			dst.wp = json_deserialize_WINDOWPLACEMENT(json_object_get_value(obj, "wp"));
			dst.version = (u32)json_object_get_number(obj, "version");
			dst.autoTileViews = json_object_get_boolean_safe(obj, "autoTileViews");
			dst.alternateRowBackground = json_object_get_boolean_safe(obj, "alternateRowBackground");
			dst.textShadows = json_object_get_boolean_safe(obj, "textShadows");
			dst.logColorUsage = json_deserialize_configColorUsage(json_object_get_value(obj, "logColorUsage"));
			dst.tooltips = json_deserialize_tooltipConfig(json_object_get_value(obj, "tooltips"));
			dst.recordingsOpen = json_object_get_boolean_safe(obj, "recordingsOpen");
			dst.dpiAware = json_object_get_boolean_safe(obj, "dpiAware");
			dst.autoDeleteAfterDays = (u32)json_object_get_number(obj, "autoDeleteAfterDays");
			dst.autoCloseAll = json_object_get_boolean_safe(obj, "autoCloseAll");
			dst.updateManagement = json_object_get_boolean_safe(obj, "updateManagement");
			dst.doubleClickSeconds = (float)json_object_get_number(obj, "doubleClickSeconds");
			dst.dpiScale = (float)json_object_get_number(obj, "dpiScale");
			dst.updateWaitForDebugger = json_object_get_boolean_safe(obj, "updateWaitForDebugger");
			dst.updatePauseAfterSuccessfulUpdate = json_object_get_boolean_safe(obj, "updatePauseAfterSuccessfulUpdate");
			dst.updatePauseAfterFailedUpdate = json_object_get_boolean_safe(obj, "updatePauseAfterFailedUpdate");
			dst.assertMessageBox = json_object_get_boolean_safe(obj, "assertMessageBox");
			for(u32 i = 0; i < BB_ARRAYSIZE(dst.pad); ++i) {
				dst.pad[i] = (u8)json_object_get_number(obj, va("pad.%u", i));
			}
		}
	}
	return dst;
}

FILETIME json_deserialize_FILETIME(JSON_Value *src)
{
	FILETIME dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			dst.dwLowDateTime = (unsigned long)json_object_get_number(obj, "dwLowDateTime");
			dst.dwHighDateTime = (unsigned long)json_object_get_number(obj, "dwHighDateTime");
		}
	}
	return dst;
}

new_recording_t json_deserialize_new_recording_t(JSON_Value *src)
{
	new_recording_t dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			dst.applicationName = json_deserialize_sb_t(json_object_get_value(obj, "applicationName"));
			dst.applicationFilename = json_deserialize_sb_t(json_object_get_value(obj, "applicationFilename"));
			dst.path = json_deserialize_sb_t(json_object_get_value(obj, "path"));
			dst.filetime = json_deserialize_FILETIME(json_object_get_value(obj, "filetime"));
			dst.openView = json_object_get_boolean_safe(obj, "openView");
			dst.recordingType = json_deserialize_recording_type_t(json_object_get_value(obj, "recordingType"));
			dst.mqId = (u32)json_object_get_number(obj, "mqId");
			dst.platform = (u32)json_object_get_number(obj, "platform");
		}
	}
	return dst;
}

updateConfig_t json_deserialize_updateConfig_t(JSON_Value *src)
{
	updateConfig_t dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			dst.updateResultDir = json_deserialize_sb_t(json_object_get_value(obj, "updateResultDir"));
			dst.updateAvailableMessage = json_deserialize_sb_t(json_object_get_value(obj, "updateAvailableMessage"));
			dst.updateIgnoredMessage = json_deserialize_sb_t(json_object_get_value(obj, "updateIgnoredMessage"));
			dst.updateShutdownMessage = json_deserialize_sb_t(json_object_get_value(obj, "updateShutdownMessage"));
			dst.updateManifestDir = json_deserialize_sb_t(json_object_get_value(obj, "updateManifestDir"));
			dst.updateCheckMs = (u32)json_object_get_number(obj, "updateCheckMs");
			for(u32 i = 0; i < BB_ARRAYSIZE(dst.pad); ++i) {
				dst.pad[i] = (u8)json_object_get_number(obj, va("pad.%u", i));
			}
		}
	}
	return dst;
}

site_config_t json_deserialize_site_config_t(JSON_Value *src)
{
	site_config_t dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			dst.updates = json_deserialize_updateConfig_t(json_object_get_value(obj, "updates"));
			dst.bugAssignee = json_deserialize_sb_t(json_object_get_value(obj, "bugAssignee"));
			dst.bugProject = json_deserialize_sb_t(json_object_get_value(obj, "bugProject"));
		}
	}
	return dst;
}

uuidState_t json_deserialize_uuidState_t(JSON_Value *src)
{
	uuidState_t dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			dst.timestampLow = (u32)json_object_get_number(obj, "timestampLow");
			dst.timestampHi = (u32)json_object_get_number(obj, "timestampHi");
			dst.clockSequence = (u16)json_object_get_number(obj, "clockSequence");
			dst.nodeId = json_deserialize_uuid_node_t(json_object_get_value(obj, "nodeId"));
		}
	}
	return dst;
}

view_pieInstance_t json_deserialize_view_pieInstance_t(JSON_Value *src)
{
	view_pieInstance_t dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			dst.selected = json_object_get_boolean_safe(obj, "selected");
			dst.visible = json_object_get_boolean_safe(obj, "visible");
		}
	}
	return dst;
}

view_pieInstances_t json_deserialize_view_pieInstances_t(JSON_Value *src)
{
	view_pieInstances_t dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Array *arr = json_value_get_array(src);
		if(arr) {
			for(u32 i = 0; i < json_array_get_count(arr); ++i) {
				bba_push(dst, json_deserialize_view_pieInstance_t(json_array_get_value(arr, i)));
			}
		}
	}
	return dst;
}

view_config_thread_t json_deserialize_view_config_thread_t(JSON_Value *src)
{
	view_config_thread_t dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			dst.name = json_deserialize_sb_t(json_object_get_value(obj, "name"));
			dst.selected = json_object_get_boolean_safe(obj, "selected");
			dst.visible = json_object_get_boolean_safe(obj, "visible");
		}
	}
	return dst;
}

view_config_threads_t json_deserialize_view_config_threads_t(JSON_Value *src)
{
	view_config_threads_t dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Array *arr = json_value_get_array(src);
		if(arr) {
			for(u32 i = 0; i < json_array_get_count(arr); ++i) {
				bba_push(dst, json_deserialize_view_config_thread_t(json_array_get_value(arr, i)));
			}
		}
	}
	return dst;
}

view_config_file_t json_deserialize_view_config_file_t(JSON_Value *src)
{
	view_config_file_t dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			dst.path = json_deserialize_sb_t(json_object_get_value(obj, "path"));
			dst.selected = json_object_get_boolean_safe(obj, "selected");
			dst.visible = json_object_get_boolean_safe(obj, "visible");
		}
	}
	return dst;
}

view_config_files_t json_deserialize_view_config_files_t(JSON_Value *src)
{
	view_config_files_t dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Array *arr = json_value_get_array(src);
		if(arr) {
			for(u32 i = 0; i < json_array_get_count(arr); ++i) {
				bba_push(dst, json_deserialize_view_config_file_t(json_array_get_value(arr, i)));
			}
		}
	}
	return dst;
}

view_config_category_t json_deserialize_view_config_category_t(JSON_Value *src)
{
	view_config_category_t dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			dst.name = json_deserialize_sb_t(json_object_get_value(obj, "name"));
			dst.selected = json_object_get_boolean_safe(obj, "selected");
			dst.visible = json_object_get_boolean_safe(obj, "visible");
			dst.favorite = json_object_get_boolean_safe(obj, "favorite");
			dst.depth = (u32)json_object_get_number(obj, "depth");
		}
	}
	return dst;
}

view_config_categories_t json_deserialize_view_config_categories_t(JSON_Value *src)
{
	view_config_categories_t dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Array *arr = json_value_get_array(src);
		if(arr) {
			for(u32 i = 0; i < json_array_get_count(arr); ++i) {
				bba_push(dst, json_deserialize_view_config_category_t(json_array_get_value(arr, i)));
			}
		}
	}
	return dst;
}

view_config_column_t json_deserialize_view_config_column_t(JSON_Value *src)
{
	view_config_column_t dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			dst.name = json_deserialize_sb_t(json_object_get_value(obj, "name"));
			dst.visible = json_object_get_boolean_safe(obj, "visible");
			dst.width = (float)json_object_get_number(obj, "width");
		}
	}
	return dst;
}

view_config_columns_t json_deserialize_view_config_columns_t(JSON_Value *src)
{
	view_config_columns_t dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Array *arr = json_value_get_array(src);
		if(arr) {
			for(u32 i = 0; i < json_array_get_count(arr); ++i) {
				bba_push(dst, json_deserialize_view_config_column_t(json_array_get_value(arr, i)));
			}
		}
	}
	return dst;
}

view_console_history_entry_t json_deserialize_view_console_history_entry_t(JSON_Value *src)
{
	view_console_history_entry_t dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			dst.command = json_deserialize_sb_t(json_object_get_value(obj, "command"));
		}
	}
	return dst;
}

view_console_history_entries_t json_deserialize_view_console_history_entries_t(JSON_Value *src)
{
	view_console_history_entries_t dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Array *arr = json_value_get_array(src);
		if(arr) {
			for(u32 i = 0; i < json_array_get_count(arr); ++i) {
				bba_push(dst, json_deserialize_view_console_history_entry_t(json_array_get_value(arr, i)));
			}
		}
	}
	return dst;
}

view_console_history_t json_deserialize_view_console_history_t(JSON_Value *src)
{
	view_console_history_t dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			dst.entries = json_deserialize_view_console_history_entries_t(json_object_get_value(obj, "entries"));
			dst.pos = (u32)json_object_get_number(obj, "pos");
			for(u32 i = 0; i < BB_ARRAYSIZE(dst.pad); ++i) {
				dst.pad[i] = (u8)json_object_get_number(obj, va("pad.%u", i));
			}
		}
	}
	return dst;
}

view_config_t json_deserialize_view_config_t(JSON_Value *src)
{
	view_config_t dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			dst.configColumns = json_deserialize_view_config_columns_t(json_object_get_value(obj, "configColumns"));
			dst.configThreads = json_deserialize_view_config_threads_t(json_object_get_value(obj, "configThreads"));
			dst.configFiles = json_deserialize_view_config_files_t(json_object_get_value(obj, "configFiles"));
			dst.configCategories = json_deserialize_view_config_categories_t(json_object_get_value(obj, "configCategories"));
			dst.consoleHistory = json_deserialize_view_console_history_t(json_object_get_value(obj, "consoleHistory"));
			dst.filterInput = json_deserialize_sb_t(json_object_get_value(obj, "filterInput"));
			dst.spansInput = json_deserialize_sb_t(json_object_get_value(obj, "spansInput"));
			dst.showVeryVerbose = json_object_get_boolean_safe(obj, "showVeryVerbose");
			dst.showVerbose = json_object_get_boolean_safe(obj, "showVerbose");
			dst.showLogs = json_object_get_boolean_safe(obj, "showLogs");
			dst.showDisplay = json_object_get_boolean_safe(obj, "showDisplay");
			dst.showWarnings = json_object_get_boolean_safe(obj, "showWarnings");
			dst.showErrors = json_object_get_boolean_safe(obj, "showErrors");
			dst.showFatal = json_object_get_boolean_safe(obj, "showFatal");
			dst.showSelectorTarget = json_object_get_boolean_safe(obj, "showSelectorTarget");
			dst.newNonFavoriteColumnVisibility = json_object_get_boolean_safe(obj, "newNonFavoriteColumnVisibility");
			dst.newFavoriteColumnVisibility = json_object_get_boolean_safe(obj, "newFavoriteColumnVisibility");
			dst.newThreadVisibility = json_object_get_boolean_safe(obj, "newThreadVisibility");
			dst.newFileVisibility = json_object_get_boolean_safe(obj, "newFileVisibility");
			dst.filterActive = json_object_get_boolean_safe(obj, "filterActive");
			dst.version = (u32)json_object_get_number(obj, "version");
			dst.selector = json_deserialize_view_config_selector_t(json_object_get_value(obj, "selector"));
			for(u32 i = 0; i < BB_ARRAYSIZE(dst.pad); ++i) {
				dst.pad[i] = (u8)json_object_get_number(obj, va("pad.%u", i));
			}
		}
	}
	return dst;
}

//////////////////////////////////////////////////////////////////////////

JSON_Value *json_serialize_POINT(const POINT *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		json_object_set_number(obj, "x", src->x);
		json_object_set_number(obj, "y", src->y);
	}
	return val;
}

JSON_Value *json_serialize_RECT(const RECT *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		json_object_set_number(obj, "left", src->left);
		json_object_set_number(obj, "top", src->top);
		json_object_set_number(obj, "right", src->right);
		json_object_set_number(obj, "bottom", src->bottom);
	}
	return val;
}

JSON_Value *json_serialize_WINDOWPLACEMENT(const WINDOWPLACEMENT *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		json_object_set_number(obj, "length", src->length);
		json_object_set_number(obj, "flags", src->flags);
		json_object_set_number(obj, "showCmd", src->showCmd);
		json_object_set_value(obj, "ptMinPosition", json_serialize_POINT(&src->ptMinPosition));
		json_object_set_value(obj, "ptMaxPosition", json_serialize_POINT(&src->ptMaxPosition));
		json_object_set_value(obj, "rcNormalPosition", json_serialize_RECT(&src->rcNormalPosition));
	}
	return val;
}

JSON_Value *json_serialize_configWhitelistEntry_t(const configWhitelistEntry_t *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		json_object_set_boolean(obj, "allow", src->allow);
		json_object_set_boolean(obj, "autodetectedDevkit", src->autodetectedDevkit);
		json_object_set_number(obj, "delay", src->delay);
		for(u32 i = 0; i < BB_ARRAYSIZE(src->pad); ++i) {
			json_object_set_number(obj, va("pad.%u", i), src->pad[i]);
		}
		json_object_set_value(obj, "addressPlusMask", json_serialize_sb_t(&src->addressPlusMask));
		json_object_set_value(obj, "applicationName", json_serialize_sb_t(&src->applicationName));
		json_object_set_value(obj, "comment", json_serialize_sb_t(&src->comment));
	}
	return val;
}

JSON_Value *json_serialize_configWhitelist_t(const configWhitelist_t *src)
{
	JSON_Value *val = json_value_init_array();
	JSON_Array *arr = json_value_get_array(val);
	if(arr) {
		for(u32 i = 0; i < src->count; ++i) {
			JSON_Value *child = json_serialize_configWhitelistEntry_t(src->data + i);
			if(child) {
				json_array_append_value(arr, child);
			}
		}
	}
	return val;
}

JSON_Value *json_serialize_openTargetEntry_t(const openTargetEntry_t *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		json_object_set_value(obj, "displayName", json_serialize_sb_t(&src->displayName));
		json_object_set_value(obj, "commandLine", json_serialize_sb_t(&src->commandLine));
	}
	return val;
}

JSON_Value *json_serialize_openTargetList_t(const openTargetList_t *src)
{
	JSON_Value *val = json_value_init_array();
	JSON_Array *arr = json_value_get_array(val);
	if(arr) {
		for(u32 i = 0; i < src->count; ++i) {
			JSON_Value *child = json_serialize_openTargetEntry_t(src->data + i);
			if(child) {
				json_array_append_value(arr, child);
			}
		}
	}
	return val;
}

JSON_Value *json_serialize_pathFixupEntry_t(const pathFixupEntry_t *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		json_object_set_value(obj, "src", json_serialize_sb_t(&src->src));
		json_object_set_value(obj, "dst", json_serialize_sb_t(&src->dst));
	}
	return val;
}

JSON_Value *json_serialize_pathFixupList_t(const pathFixupList_t *src)
{
	JSON_Value *val = json_value_init_array();
	JSON_Array *arr = json_value_get_array(val);
	if(arr) {
		for(u32 i = 0; i < src->count; ++i) {
			JSON_Value *child = json_serialize_pathFixupEntry_t(src->data + i);
			if(child) {
				json_array_append_value(arr, child);
			}
		}
	}
	return val;
}

JSON_Value *json_serialize_tooltipConfig(const tooltipConfig *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		json_object_set_boolean(obj, "enabled", src->enabled);
		json_object_set_boolean(obj, "overText", src->overText);
		json_object_set_boolean(obj, "overMisc", src->overMisc);
		json_object_set_boolean(obj, "onlyOverSelected", src->onlyOverSelected);
		json_object_set_number(obj, "delay", src->delay);
		for(u32 i = 0; i < BB_ARRAYSIZE(src->pad); ++i) {
			json_object_set_number(obj, va("pad.%u", i), src->pad[i]);
		}
	}
	return val;
}

JSON_Value *json_serialize_config_t(const config_t *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		json_object_set_value(obj, "whitelist", json_serialize_configWhitelist_t(&src->whitelist));
		json_object_set_value(obj, "openTargets", json_serialize_openTargetList_t(&src->openTargets));
		json_object_set_value(obj, "pathFixups", json_serialize_pathFixupList_t(&src->pathFixups));
		json_object_set_value(obj, "logFontConfig", json_serialize_fontConfig_t(&src->logFontConfig));
		json_object_set_value(obj, "uiFontConfig", json_serialize_fontConfig_t(&src->uiFontConfig));
		json_object_set_value(obj, "colorscheme", json_serialize_sb_t(&src->colorscheme));
		json_object_set_value(obj, "wp", json_serialize_WINDOWPLACEMENT(&src->wp));
		json_object_set_number(obj, "version", src->version);
		json_object_set_boolean(obj, "autoTileViews", src->autoTileViews);
		json_object_set_boolean(obj, "alternateRowBackground", src->alternateRowBackground);
		json_object_set_boolean(obj, "textShadows", src->textShadows);
		json_object_set_value(obj, "logColorUsage", json_serialize_configColorUsage(src->logColorUsage));
		json_object_set_value(obj, "tooltips", json_serialize_tooltipConfig(&src->tooltips));
		json_object_set_boolean(obj, "recordingsOpen", src->recordingsOpen);
		json_object_set_boolean(obj, "dpiAware", src->dpiAware);
		json_object_set_number(obj, "autoDeleteAfterDays", src->autoDeleteAfterDays);
		json_object_set_boolean(obj, "autoCloseAll", src->autoCloseAll);
		json_object_set_boolean(obj, "updateManagement", src->updateManagement);
		json_object_set_number(obj, "doubleClickSeconds", src->doubleClickSeconds);
		json_object_set_number(obj, "dpiScale", src->dpiScale);
		json_object_set_boolean(obj, "updateWaitForDebugger", src->updateWaitForDebugger);
		json_object_set_boolean(obj, "updatePauseAfterSuccessfulUpdate", src->updatePauseAfterSuccessfulUpdate);
		json_object_set_boolean(obj, "updatePauseAfterFailedUpdate", src->updatePauseAfterFailedUpdate);
		json_object_set_boolean(obj, "assertMessageBox", src->assertMessageBox);
		for(u32 i = 0; i < BB_ARRAYSIZE(src->pad); ++i) {
			json_object_set_number(obj, va("pad.%u", i), src->pad[i]);
		}
	}
	return val;
}

JSON_Value *json_serialize_FILETIME(const FILETIME *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		json_object_set_number(obj, "dwLowDateTime", src->dwLowDateTime);
		json_object_set_number(obj, "dwHighDateTime", src->dwHighDateTime);
	}
	return val;
}

JSON_Value *json_serialize_new_recording_t(const new_recording_t *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		json_object_set_value(obj, "applicationName", json_serialize_sb_t(&src->applicationName));
		json_object_set_value(obj, "applicationFilename", json_serialize_sb_t(&src->applicationFilename));
		json_object_set_value(obj, "path", json_serialize_sb_t(&src->path));
		json_object_set_value(obj, "filetime", json_serialize_FILETIME(&src->filetime));
		json_object_set_boolean(obj, "openView", src->openView);
		json_object_set_value(obj, "recordingType", json_serialize_recording_type_t(src->recordingType));
		json_object_set_number(obj, "mqId", src->mqId);
		json_object_set_number(obj, "platform", src->platform);
	}
	return val;
}

JSON_Value *json_serialize_updateConfig_t(const updateConfig_t *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		json_object_set_value(obj, "updateResultDir", json_serialize_sb_t(&src->updateResultDir));
		json_object_set_value(obj, "updateAvailableMessage", json_serialize_sb_t(&src->updateAvailableMessage));
		json_object_set_value(obj, "updateIgnoredMessage", json_serialize_sb_t(&src->updateIgnoredMessage));
		json_object_set_value(obj, "updateShutdownMessage", json_serialize_sb_t(&src->updateShutdownMessage));
		json_object_set_value(obj, "updateManifestDir", json_serialize_sb_t(&src->updateManifestDir));
		json_object_set_number(obj, "updateCheckMs", src->updateCheckMs);
		for(u32 i = 0; i < BB_ARRAYSIZE(src->pad); ++i) {
			json_object_set_number(obj, va("pad.%u", i), src->pad[i]);
		}
	}
	return val;
}

JSON_Value *json_serialize_site_config_t(const site_config_t *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		json_object_set_value(obj, "updates", json_serialize_updateConfig_t(&src->updates));
		json_object_set_value(obj, "bugAssignee", json_serialize_sb_t(&src->bugAssignee));
		json_object_set_value(obj, "bugProject", json_serialize_sb_t(&src->bugProject));
	}
	return val;
}

JSON_Value *json_serialize_uuidState_t(const uuidState_t *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		json_object_set_number(obj, "timestampLow", src->timestampLow);
		json_object_set_number(obj, "timestampHi", src->timestampHi);
		json_object_set_number(obj, "clockSequence", src->clockSequence);
		json_object_set_value(obj, "nodeId", json_serialize_uuid_node_t(&src->nodeId));
	}
	return val;
}

JSON_Value *json_serialize_view_pieInstance_t(const view_pieInstance_t *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		json_object_set_boolean(obj, "selected", src->selected);
		json_object_set_boolean(obj, "visible", src->visible);
	}
	return val;
}

JSON_Value *json_serialize_view_pieInstances_t(const view_pieInstances_t *src)
{
	JSON_Value *val = json_value_init_array();
	JSON_Array *arr = json_value_get_array(val);
	if(arr) {
		for(u32 i = 0; i < src->count; ++i) {
			JSON_Value *child = json_serialize_view_pieInstance_t(src->data + i);
			if(child) {
				json_array_append_value(arr, child);
			}
		}
	}
	return val;
}

JSON_Value *json_serialize_view_config_thread_t(const view_config_thread_t *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		json_object_set_value(obj, "name", json_serialize_sb_t(&src->name));
		json_object_set_boolean(obj, "selected", src->selected);
		json_object_set_boolean(obj, "visible", src->visible);
	}
	return val;
}

JSON_Value *json_serialize_view_config_threads_t(const view_config_threads_t *src)
{
	JSON_Value *val = json_value_init_array();
	JSON_Array *arr = json_value_get_array(val);
	if(arr) {
		for(u32 i = 0; i < src->count; ++i) {
			JSON_Value *child = json_serialize_view_config_thread_t(src->data + i);
			if(child) {
				json_array_append_value(arr, child);
			}
		}
	}
	return val;
}

JSON_Value *json_serialize_view_config_file_t(const view_config_file_t *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		json_object_set_value(obj, "path", json_serialize_sb_t(&src->path));
		json_object_set_boolean(obj, "selected", src->selected);
		json_object_set_boolean(obj, "visible", src->visible);
	}
	return val;
}

JSON_Value *json_serialize_view_config_files_t(const view_config_files_t *src)
{
	JSON_Value *val = json_value_init_array();
	JSON_Array *arr = json_value_get_array(val);
	if(arr) {
		for(u32 i = 0; i < src->count; ++i) {
			JSON_Value *child = json_serialize_view_config_file_t(src->data + i);
			if(child) {
				json_array_append_value(arr, child);
			}
		}
	}
	return val;
}

JSON_Value *json_serialize_view_config_category_t(const view_config_category_t *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		json_object_set_value(obj, "name", json_serialize_sb_t(&src->name));
		json_object_set_boolean(obj, "selected", src->selected);
		json_object_set_boolean(obj, "visible", src->visible);
		json_object_set_boolean(obj, "favorite", src->favorite);
		json_object_set_number(obj, "depth", src->depth);
	}
	return val;
}

JSON_Value *json_serialize_view_config_categories_t(const view_config_categories_t *src)
{
	JSON_Value *val = json_value_init_array();
	JSON_Array *arr = json_value_get_array(val);
	if(arr) {
		for(u32 i = 0; i < src->count; ++i) {
			JSON_Value *child = json_serialize_view_config_category_t(src->data + i);
			if(child) {
				json_array_append_value(arr, child);
			}
		}
	}
	return val;
}

JSON_Value *json_serialize_view_config_column_t(const view_config_column_t *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		json_object_set_value(obj, "name", json_serialize_sb_t(&src->name));
		json_object_set_boolean(obj, "visible", src->visible);
		json_object_set_number(obj, "width", src->width);
	}
	return val;
}

JSON_Value *json_serialize_view_config_columns_t(const view_config_columns_t *src)
{
	JSON_Value *val = json_value_init_array();
	JSON_Array *arr = json_value_get_array(val);
	if(arr) {
		for(u32 i = 0; i < src->count; ++i) {
			JSON_Value *child = json_serialize_view_config_column_t(src->data + i);
			if(child) {
				json_array_append_value(arr, child);
			}
		}
	}
	return val;
}

JSON_Value *json_serialize_view_console_history_entry_t(const view_console_history_entry_t *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		json_object_set_value(obj, "command", json_serialize_sb_t(&src->command));
	}
	return val;
}

JSON_Value *json_serialize_view_console_history_entries_t(const view_console_history_entries_t *src)
{
	JSON_Value *val = json_value_init_array();
	JSON_Array *arr = json_value_get_array(val);
	if(arr) {
		for(u32 i = 0; i < src->count; ++i) {
			JSON_Value *child = json_serialize_view_console_history_entry_t(src->data + i);
			if(child) {
				json_array_append_value(arr, child);
			}
		}
	}
	return val;
}

JSON_Value *json_serialize_view_console_history_t(const view_console_history_t *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		json_object_set_value(obj, "entries", json_serialize_view_console_history_entries_t(&src->entries));
		json_object_set_number(obj, "pos", src->pos);
		for(u32 i = 0; i < BB_ARRAYSIZE(src->pad); ++i) {
			json_object_set_number(obj, va("pad.%u", i), src->pad[i]);
		}
	}
	return val;
}

JSON_Value *json_serialize_view_config_t(const view_config_t *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		json_object_set_value(obj, "configColumns", json_serialize_view_config_columns_t(&src->configColumns));
		json_object_set_value(obj, "configThreads", json_serialize_view_config_threads_t(&src->configThreads));
		json_object_set_value(obj, "configFiles", json_serialize_view_config_files_t(&src->configFiles));
		json_object_set_value(obj, "configCategories", json_serialize_view_config_categories_t(&src->configCategories));
		json_object_set_value(obj, "consoleHistory", json_serialize_view_console_history_t(&src->consoleHistory));
		json_object_set_value(obj, "filterInput", json_serialize_sb_t(&src->filterInput));
		json_object_set_value(obj, "spansInput", json_serialize_sb_t(&src->spansInput));
		json_object_set_boolean(obj, "showVeryVerbose", src->showVeryVerbose);
		json_object_set_boolean(obj, "showVerbose", src->showVerbose);
		json_object_set_boolean(obj, "showLogs", src->showLogs);
		json_object_set_boolean(obj, "showDisplay", src->showDisplay);
		json_object_set_boolean(obj, "showWarnings", src->showWarnings);
		json_object_set_boolean(obj, "showErrors", src->showErrors);
		json_object_set_boolean(obj, "showFatal", src->showFatal);
		json_object_set_boolean(obj, "showSelectorTarget", src->showSelectorTarget);
		json_object_set_boolean(obj, "newNonFavoriteColumnVisibility", src->newNonFavoriteColumnVisibility);
		json_object_set_boolean(obj, "newFavoriteColumnVisibility", src->newFavoriteColumnVisibility);
		json_object_set_boolean(obj, "newThreadVisibility", src->newThreadVisibility);
		json_object_set_boolean(obj, "newFileVisibility", src->newFileVisibility);
		json_object_set_boolean(obj, "filterActive", src->filterActive);
		json_object_set_number(obj, "version", src->version);
		json_object_set_value(obj, "selector", json_serialize_view_config_selector_t(src->selector));
		for(u32 i = 0; i < BB_ARRAYSIZE(src->pad); ++i) {
			json_object_set_number(obj, va("pad.%u", i), src->pad[i]);
		}
	}
	return val;
}

//////////////////////////////////////////////////////////////////////////

configColorUsage json_deserialize_configColorUsage(JSON_Value *src)
{
	configColorUsage dst = kConfigColors_Full;
	if(src) {
		const char *str = json_value_get_string(src);
		if(str) {
			if(!strcmp(str, "kConfigColors_Full")) { dst = kConfigColors_Full; }
			if(!strcmp(str, "kConfigColors_BgAsFg")) { dst = kConfigColors_BgAsFg; }
			if(!strcmp(str, "kConfigColors_NoBg")) { dst = kConfigColors_NoBg; }
			if(!strcmp(str, "kConfigColors_None")) { dst = kConfigColors_None; }
			if(!strcmp(str, "kConfigColors_Count")) { dst = kConfigColors_Count; }
		}
	}
	return dst;
}

recording_type_t json_deserialize_recording_type_t(JSON_Value *src)
{
	recording_type_t dst = kRecordingType_Count;
	if(src) {
		const char *str = json_value_get_string(src);
		if(str) {
			if(!strcmp(str, "kRecordingType_Normal")) { dst = kRecordingType_Normal; }
			if(!strcmp(str, "kRecordingType_ExistingFile")) { dst = kRecordingType_ExistingFile; }
			if(!strcmp(str, "kRecordingType_MainLog")) { dst = kRecordingType_MainLog; }
			if(!strcmp(str, "kRecordingType_ExternalFile")) { dst = kRecordingType_ExternalFile; }
			if(!strcmp(str, "kRecordingType_Count")) { dst = kRecordingType_Count; }
		}
	}
	return dst;
}

view_config_selector_t json_deserialize_view_config_selector_t(JSON_Value *src)
{
	view_config_selector_t dst = kViewSelector_Categories;
	if(src) {
		const char *str = json_value_get_string(src);
		if(str) {
			if(!strcmp(str, "kViewSelector_Categories")) { dst = kViewSelector_Categories; }
			if(!strcmp(str, "kViewSelector_AllCategories")) { dst = kViewSelector_AllCategories; }
			if(!strcmp(str, "kViewSelector_Threads")) { dst = kViewSelector_Threads; }
			if(!strcmp(str, "kViewSelector_Files")) { dst = kViewSelector_Files; }
			if(!strcmp(str, "kViewSelector_PIEInstances")) { dst = kViewSelector_PIEInstances; }
			if(!strcmp(str, "kViewSelector_Count")) { dst = kViewSelector_Count; }
		}
	}
	return dst;
}

//////////////////////////////////////////////////////////////////////////

JSON_Value *json_serialize_configColorUsage(const configColorUsage src)
{
	const char *str = "";
	switch(src) {
		case kConfigColors_Full: str = "kConfigColors_Full"; break;
		case kConfigColors_BgAsFg: str = "kConfigColors_BgAsFg"; break;
		case kConfigColors_NoBg: str = "kConfigColors_NoBg"; break;
		case kConfigColors_None: str = "kConfigColors_None"; break;
		case kConfigColors_Count: str = "kConfigColors_Count"; break;
	}
	JSON_Value *val = json_value_init_string(str);
	return val;
}

JSON_Value *json_serialize_recording_type_t(const recording_type_t src)
{
	const char *str = "";
	switch(src) {
		case kRecordingType_Normal: str = "kRecordingType_Normal"; break;
		case kRecordingType_ExistingFile: str = "kRecordingType_ExistingFile"; break;
		case kRecordingType_MainLog: str = "kRecordingType_MainLog"; break;
		case kRecordingType_ExternalFile: str = "kRecordingType_ExternalFile"; break;
		case kRecordingType_Count: str = "kRecordingType_Count"; break;
	}
	JSON_Value *val = json_value_init_string(str);
	return val;
}

JSON_Value *json_serialize_view_config_selector_t(const view_config_selector_t src)
{
	const char *str = "";
	switch(src) {
		case kViewSelector_Categories: str = "kViewSelector_Categories"; break;
		case kViewSelector_AllCategories: str = "kViewSelector_AllCategories"; break;
		case kViewSelector_Threads: str = "kViewSelector_Threads"; break;
		case kViewSelector_Files: str = "kViewSelector_Files"; break;
		case kViewSelector_PIEInstances: str = "kViewSelector_PIEInstances"; break;
		case kViewSelector_Count: str = "kViewSelector_Count"; break;
	}
	JSON_Value *val = json_value_init_string(str);
	return val;
}

//////////////////////////////////////////////////////////////////////////
