// Copyright (c) 2012-2019 Matt Campbell
// MIT license (see License.txt)

// AUTOGENERATED FILE - DO NOT EDIT

// clang-format off

#include "bb_json_generated.h"
#include "bb_array.h"
#include "json_utils.h"
#include "va.h"

#include "config.h"
#include "device_codes.h"
#include "fonts.h"
#include "message_queue.h"
#include "recordings.h"
#include "sb.h"
#include "sdict.h"
#include "site_config.h"
#include "tags.h"
#include "theme_config.h"
#include "uuid_config.h"
#include "uuid_rfc4122/sysdep.h"
#include "view.h"
#include "view_filter.h"

//////////////////////////////////////////////////////////////////////////

POINT json_deserialize_POINT(JSON_Value *src)
{
	POINT dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			dst.x = (LONG)json_object_get_number(obj, "x");
			dst.y = (LONG)json_object_get_number(obj, "y");
		}
	}
	return dst;
}

RECT json_deserialize_RECT(JSON_Value *src)
{
	RECT dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			dst.left = (LONG)json_object_get_number(obj, "left");
			dst.top = (LONG)json_object_get_number(obj, "top");
			dst.right = (LONG)json_object_get_number(obj, "right");
			dst.bottom = (LONG)json_object_get_number(obj, "bottom");
		}
	}
	return dst;
}

WINDOWPLACEMENT json_deserialize_WINDOWPLACEMENT(JSON_Value *src)
{
	WINDOWPLACEMENT dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			dst.length = (UINT)json_object_get_number(obj, "length");
			dst.flags = (UINT)json_object_get_number(obj, "flags");
			dst.showCmd = (UINT)json_object_get_number(obj, "showCmd");
			dst.ptMinPosition = json_deserialize_POINT(json_object_get_value(obj, "ptMinPosition"));
			dst.ptMaxPosition = json_deserialize_POINT(json_object_get_value(obj, "ptMaxPosition"));
			dst.rcNormalPosition = json_deserialize_RECT(json_object_get_value(obj, "rcNormalPosition"));
		}
	}
	return dst;
}

configWhitelistEntry_t json_deserialize_configWhitelistEntry_t(JSON_Value *src)
{
	configWhitelistEntry_t dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			dst.allow = json_object_get_boolean_safe(obj, "allow");
			dst.autodetectedDevkit = json_object_get_boolean_safe(obj, "autodetectedDevkit");
			dst.delay = (u32)json_object_get_number(obj, "delay");
			for(u32 i = 0; i < BB_ARRAYSIZE(dst.pad); ++i) {
				dst.pad[i] = (u8)json_object_get_number(obj, va("pad.%u", i));
			}
			dst.addressPlusMask = json_deserialize_sb_t(json_object_get_value(obj, "addressPlusMask"));
			dst.applicationName = json_deserialize_sb_t(json_object_get_value(obj, "applicationName"));
			dst.comment = json_deserialize_sb_t(json_object_get_value(obj, "comment"));
		}
	}
	return dst;
}

configWhitelist_t json_deserialize_configWhitelist_t(JSON_Value *src)
{
	configWhitelist_t dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Array *arr = json_value_get_array(src);
		if(arr) {
			for(u32 i = 0; i < json_array_get_count(arr); ++i) {
				bba_push(dst, json_deserialize_configWhitelistEntry_t(json_array_get_value(arr, i)));
			}
		}
	}
	return dst;
}

openTargetEntry_t json_deserialize_openTargetEntry_t(JSON_Value *src)
{
	openTargetEntry_t dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			dst.displayName = json_deserialize_sb_t(json_object_get_value(obj, "displayName"));
			dst.commandLine = json_deserialize_sb_t(json_object_get_value(obj, "commandLine"));
		}
	}
	return dst;
}

openTargetList_t json_deserialize_openTargetList_t(JSON_Value *src)
{
	openTargetList_t dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Array *arr = json_value_get_array(src);
		if(arr) {
			for(u32 i = 0; i < json_array_get_count(arr); ++i) {
				bba_push(dst, json_deserialize_openTargetEntry_t(json_array_get_value(arr, i)));
			}
		}
	}
	return dst;
}

pathFixupEntry_t json_deserialize_pathFixupEntry_t(JSON_Value *src)
{
	pathFixupEntry_t dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			dst.src = json_deserialize_sb_t(json_object_get_value(obj, "src"));
			dst.dst = json_deserialize_sb_t(json_object_get_value(obj, "dst"));
		}
	}
	return dst;
}

pathFixupList_t json_deserialize_pathFixupList_t(JSON_Value *src)
{
	pathFixupList_t dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Array *arr = json_value_get_array(src);
		if(arr) {
			for(u32 i = 0; i < json_array_get_count(arr); ++i) {
				bba_push(dst, json_deserialize_pathFixupEntry_t(json_array_get_value(arr, i)));
			}
		}
	}
	return dst;
}

tooltipConfig json_deserialize_tooltipConfig(JSON_Value *src)
{
	tooltipConfig dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			dst.enabled = json_object_get_boolean_safe(obj, "enabled");
			dst.overText = json_object_get_boolean_safe(obj, "overText");
			dst.overMisc = json_object_get_boolean_safe(obj, "overMisc");
			dst.onlyOverSelected = json_object_get_boolean_safe(obj, "onlyOverSelected");
			dst.delay = (float)json_object_get_number(obj, "delay");
			for(u32 i = 0; i < BB_ARRAYSIZE(dst.pad); ++i) {
				dst.pad[i] = (u8)json_object_get_number(obj, va("pad.%u", i));
			}
		}
	}
	return dst;
}

sizeConfig json_deserialize_sizeConfig(JSON_Value *src)
{
	sizeConfig dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			dst.resizeBarSize = (s32)json_object_get_number(obj, "resizeBarSize");
			dst.scrollbarSize = (s32)json_object_get_number(obj, "scrollbarSize");
		}
	}
	return dst;
}

config_t json_deserialize_config_t(JSON_Value *src)
{
	config_t dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			dst.whitelist = json_deserialize_configWhitelist_t(json_object_get_value(obj, "whitelist"));
			dst.openTargets = json_deserialize_openTargetList_t(json_object_get_value(obj, "openTargets"));
			dst.pathFixups = json_deserialize_pathFixupList_t(json_object_get_value(obj, "pathFixups"));
			dst.logFontConfig = json_deserialize_fontConfig_t(json_object_get_value(obj, "logFontConfig"));
			dst.uiFontConfig = json_deserialize_fontConfig_t(json_object_get_value(obj, "uiFontConfig"));
			dst.colorscheme = json_deserialize_sb_t(json_object_get_value(obj, "colorscheme"));
			dst.wp = json_deserialize_WINDOWPLACEMENT(json_object_get_value(obj, "wp"));
			dst.version = (u32)json_object_get_number(obj, "version");
			dst.viewTileMode = json_deserialize_viewTileMode_t(json_object_get_value(obj, "viewTileMode"));
			dst.alternateRowBackground = json_object_get_boolean_safe(obj, "alternateRowBackground");
			dst.textShadows = json_object_get_boolean_safe(obj, "textShadows");
			dst.logColorUsage = json_deserialize_configColorUsage(json_object_get_value(obj, "logColorUsage"));
			dst.tooltips = json_deserialize_tooltipConfig(json_object_get_value(obj, "tooltips"));
			dst.sizes = json_deserialize_sizeConfig(json_object_get_value(obj, "sizes"));
			dst.dpiAware = json_object_get_boolean_safe(obj, "dpiAware");
			dst.dpiScrollwheel = json_object_get_boolean_safe(obj, "dpiScrollwheel");
			dst.autoDeleteAfterDays = (u32)json_object_get_number(obj, "autoDeleteAfterDays");
			dst.autoCloseAll = json_object_get_boolean_safe(obj, "autoCloseAll");
			dst.autoCloseManual = json_object_get_boolean_safe(obj, "autoCloseManual");
			dst.updateManagement = json_object_get_boolean_safe(obj, "updateManagement");
			dst.doubleClickSeconds = (float)json_object_get_number(obj, "doubleClickSeconds");
			dst.dpiScale = (float)json_object_get_number(obj, "dpiScale");
			dst.updateWaitForDebugger = json_object_get_boolean_safe(obj, "updateWaitForDebugger");
			dst.updatePauseAfterSuccessfulUpdate = json_object_get_boolean_safe(obj, "updatePauseAfterSuccessfulUpdate");
			dst.updatePauseAfterFailedUpdate = json_object_get_boolean_safe(obj, "updatePauseAfterFailedUpdate");
			dst.assertMessageBox = json_object_get_boolean_safe(obj, "assertMessageBox");
			dst.showDebugMenu = json_object_get_boolean_safe(obj, "showDebugMenu");
			dst.showEmptyCategories = json_object_get_boolean_safe(obj, "showEmptyCategories");
		}
	}
	return dst;
}

deviceCodes_t json_deserialize_deviceCodes_t(JSON_Value *src)
{
	deviceCodes_t dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			dst.deviceCodes = json_deserialize_sbs_t(json_object_get_value(obj, "deviceCodes"));
		}
	}
	return dst;
}

FILETIME json_deserialize_FILETIME(JSON_Value *src)
{
	FILETIME dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			dst.dwLowDateTime = (unsigned long)json_object_get_number(obj, "dwLowDateTime");
			dst.dwHighDateTime = (unsigned long)json_object_get_number(obj, "dwHighDateTime");
		}
	}
	return dst;
}

new_recording_t json_deserialize_new_recording_t(JSON_Value *src)
{
	new_recording_t dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			dst.applicationName = json_deserialize_sb_t(json_object_get_value(obj, "applicationName"));
			dst.applicationFilename = json_deserialize_sb_t(json_object_get_value(obj, "applicationFilename"));
			dst.path = json_deserialize_sb_t(json_object_get_value(obj, "path"));
			dst.filetime = json_deserialize_FILETIME(json_object_get_value(obj, "filetime"));
			dst.openView = json_object_get_boolean_safe(obj, "openView");
			dst.recordingType = json_deserialize_recording_type_t(json_object_get_value(obj, "recordingType"));
			dst.mqId = (u32)json_object_get_number(obj, "mqId");
			dst.platform = (u32)json_object_get_number(obj, "platform");
		}
	}
	return dst;
}

recordings_tab_config_t json_deserialize_recordings_tab_config_t(JSON_Value *src)
{
	recordings_tab_config_t dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			dst.group = json_deserialize_recording_group_t(json_object_get_value(obj, "group"));
			dst.sort = json_deserialize_recording_sort_t(json_object_get_value(obj, "sort"));
			dst.showDate = json_object_get_boolean_safe(obj, "showDate");
			dst.showTime = json_object_get_boolean_safe(obj, "showTime");
			dst.showInternal = json_object_get_boolean_safe(obj, "showInternal");
			dst.showExternal = json_object_get_boolean_safe(obj, "showExternal");
		}
	}
	return dst;
}

recordings_config_t json_deserialize_recordings_config_t(JSON_Value *src)
{
	recordings_config_t dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			for(u32 i = 0; i < BB_ARRAYSIZE(dst.tabs); ++i) {
				dst.tabs[i] = json_deserialize_recordings_tab_config_t(json_object_get_value(obj, va("tabs.%u", i)));
			}
			dst.width = (float)json_object_get_number(obj, "width");
			dst.recordingsOpen = json_object_get_boolean_safe(obj, "recordingsOpen");
		}
	}
	return dst;
}

updateConfig_t json_deserialize_updateConfig_t(JSON_Value *src)
{
	updateConfig_t dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			dst.updateResultDir = json_deserialize_sb_t(json_object_get_value(obj, "updateResultDir"));
			dst.updateAvailableMessage = json_deserialize_sb_t(json_object_get_value(obj, "updateAvailableMessage"));
			dst.updateIgnoredMessage = json_deserialize_sb_t(json_object_get_value(obj, "updateIgnoredMessage"));
			dst.updateShutdownMessage = json_deserialize_sb_t(json_object_get_value(obj, "updateShutdownMessage"));
			dst.updateManifestDir = json_deserialize_sb_t(json_object_get_value(obj, "updateManifestDir"));
			dst.updateCheckMs = (u32)json_object_get_number(obj, "updateCheckMs");
			for(u32 i = 0; i < BB_ARRAYSIZE(dst.pad); ++i) {
				dst.pad[i] = (u8)json_object_get_number(obj, va("pad.%u", i));
			}
		}
	}
	return dst;
}

site_config_t json_deserialize_site_config_t(JSON_Value *src)
{
	site_config_t dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			dst.updates = json_deserialize_updateConfig_t(json_object_get_value(obj, "updates"));
			dst.bugAssignee = json_deserialize_sb_t(json_object_get_value(obj, "bugAssignee"));
			dst.bugProject = json_deserialize_sb_t(json_object_get_value(obj, "bugProject"));
			dst.autodetectDevkits = json_object_get_boolean_safe(obj, "autodetectDevkits");
			dst.bugPort = (u16)json_object_get_number(obj, "bugPort");
			for(u32 i = 0; i < BB_ARRAYSIZE(dst.pad); ++i) {
				dst.pad[i] = (u8)json_object_get_number(obj, va("pad.%u", i));
			}
		}
	}
	return dst;
}

sbsHashEntry json_deserialize_sbsHashEntry(JSON_Value *src)
{
	sbsHashEntry dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			dst.key = json_deserialize_sb_t(json_object_get_value(obj, "key"));
			dst.values = json_deserialize_sbs_t(json_object_get_value(obj, "values"));
		}
	}
	return dst;
}

tag_t json_deserialize_tag_t(JSON_Value *src)
{
	tag_t dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			dst.name = json_deserialize_sb_t(json_object_get_value(obj, "name"));
			dst.categories = json_deserialize_sbs_t(json_object_get_value(obj, "categories"));
			dst.visibility = json_deserialize_tag_visibility_t(json_object_get_value(obj, "visibility"));
			for(u32 i = 0; i < BB_ARRAYSIZE(dst.pad); ++i) {
				dst.pad[i] = (u8)json_object_get_number(obj, va("pad.%u", i));
			}
		}
	}
	return dst;
}

tags_t json_deserialize_tags_t(JSON_Value *src)
{
	tags_t dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Array *arr = json_value_get_array(src);
		if(arr) {
			for(u32 i = 0; i < json_array_get_count(arr); ++i) {
				bba_push(dst, json_deserialize_tag_t(json_array_get_value(arr, i)));
			}
		}
	}
	return dst;
}

tags_config_t json_deserialize_tags_config_t(JSON_Value *src)
{
	tags_config_t dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			dst.tags = json_deserialize_tags_t(json_object_get_value(obj, "tags"));
		}
	}
	return dst;
}

color_config_t json_deserialize_color_config_t(JSON_Value *src)
{
	color_config_t dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			dst.colorName = json_deserialize_styleColor_e(json_object_get_value(obj, "colorName"));
			dst.r = (u8)json_object_get_number(obj, "r");
			dst.g = (u8)json_object_get_number(obj, "g");
			dst.b = (u8)json_object_get_number(obj, "b");
			dst.a = (u8)json_object_get_number(obj, "a");
			dst.bTextShadows = json_object_get_boolean_safe(obj, "bTextShadows");
			for(u32 i = 0; i < BB_ARRAYSIZE(dst.pad); ++i) {
				dst.pad[i] = (u8)json_object_get_number(obj, va("pad.%u", i));
			}
		}
	}
	return dst;
}

colors_config_t json_deserialize_colors_config_t(JSON_Value *src)
{
	colors_config_t dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Array *arr = json_value_get_array(src);
		if(arr) {
			for(u32 i = 0; i < json_array_get_count(arr); ++i) {
				bba_push(dst, json_deserialize_color_config_t(json_array_get_value(arr, i)));
			}
		}
	}
	return dst;
}

theme_config_t json_deserialize_theme_config_t(JSON_Value *src)
{
	theme_config_t dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			dst.colors = json_deserialize_colors_config_t(json_object_get_value(obj, "colors"));
		}
	}
	return dst;
}

uuidState_t json_deserialize_uuidState_t(JSON_Value *src)
{
	uuidState_t dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			dst.timestampLow = (u32)json_object_get_number(obj, "timestampLow");
			dst.timestampHi = (u32)json_object_get_number(obj, "timestampHi");
			dst.clockSequence = (u16)json_object_get_number(obj, "clockSequence");
			dst.nodeId = json_deserialize_uuid_node_t(json_object_get_value(obj, "nodeId"));
		}
	}
	return dst;
}

view_pieInstance_t json_deserialize_view_pieInstance_t(JSON_Value *src)
{
	view_pieInstance_t dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			dst.selected = json_object_get_boolean_safe(obj, "selected");
			dst.visible = json_object_get_boolean_safe(obj, "visible");
			dst.pieInstance = (s32)json_object_get_number(obj, "pieInstance");
			dst.primary = json_object_get_boolean_safe(obj, "primary");
		}
	}
	return dst;
}

view_pieInstances_t json_deserialize_view_pieInstances_t(JSON_Value *src)
{
	view_pieInstances_t dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Array *arr = json_value_get_array(src);
		if(arr) {
			for(u32 i = 0; i < json_array_get_count(arr); ++i) {
				bba_push(dst, json_deserialize_view_pieInstance_t(json_array_get_value(arr, i)));
			}
		}
	}
	return dst;
}

view_config_thread_t json_deserialize_view_config_thread_t(JSON_Value *src)
{
	view_config_thread_t dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			dst.name = json_deserialize_sb_t(json_object_get_value(obj, "name"));
			dst.selected = json_object_get_boolean_safe(obj, "selected");
			dst.visible = json_object_get_boolean_safe(obj, "visible");
		}
	}
	return dst;
}

view_config_threads_t json_deserialize_view_config_threads_t(JSON_Value *src)
{
	view_config_threads_t dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Array *arr = json_value_get_array(src);
		if(arr) {
			for(u32 i = 0; i < json_array_get_count(arr); ++i) {
				bba_push(dst, json_deserialize_view_config_thread_t(json_array_get_value(arr, i)));
			}
		}
	}
	return dst;
}

view_config_file_t json_deserialize_view_config_file_t(JSON_Value *src)
{
	view_config_file_t dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			dst.path = json_deserialize_sb_t(json_object_get_value(obj, "path"));
			dst.selected = json_object_get_boolean_safe(obj, "selected");
			dst.visible = json_object_get_boolean_safe(obj, "visible");
		}
	}
	return dst;
}

view_config_files_t json_deserialize_view_config_files_t(JSON_Value *src)
{
	view_config_files_t dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Array *arr = json_value_get_array(src);
		if(arr) {
			for(u32 i = 0; i < json_array_get_count(arr); ++i) {
				bba_push(dst, json_deserialize_view_config_file_t(json_array_get_value(arr, i)));
			}
		}
	}
	return dst;
}

view_config_category_t json_deserialize_view_config_category_t(JSON_Value *src)
{
	view_config_category_t dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			dst.name = json_deserialize_sb_t(json_object_get_value(obj, "name"));
			dst.selected = json_object_get_boolean_safe(obj, "selected");
			dst.visible = json_object_get_boolean_safe(obj, "visible");
			dst.depth = (u32)json_object_get_number(obj, "depth");
			dst.disabled = json_object_get_boolean_safe(obj, "disabled");
		}
	}
	return dst;
}

view_config_categories_t json_deserialize_view_config_categories_t(JSON_Value *src)
{
	view_config_categories_t dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Array *arr = json_value_get_array(src);
		if(arr) {
			for(u32 i = 0; i < json_array_get_count(arr); ++i) {
				bba_push(dst, json_deserialize_view_config_category_t(json_array_get_value(arr, i)));
			}
		}
	}
	return dst;
}

view_config_column_t json_deserialize_view_config_column_t(JSON_Value *src)
{
	view_config_column_t dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			dst.name = json_deserialize_sb_t(json_object_get_value(obj, "name"));
			dst.visible = json_object_get_boolean_safe(obj, "visible");
			dst.width = (float)json_object_get_number(obj, "width");
		}
	}
	return dst;
}

view_config_columns_t json_deserialize_view_config_columns_t(JSON_Value *src)
{
	view_config_columns_t dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Array *arr = json_value_get_array(src);
		if(arr) {
			for(u32 i = 0; i < json_array_get_count(arr); ++i) {
				bba_push(dst, json_deserialize_view_config_column_t(json_array_get_value(arr, i)));
			}
		}
	}
	return dst;
}

view_console_history_entry_t json_deserialize_view_console_history_entry_t(JSON_Value *src)
{
	view_console_history_entry_t dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			dst.command = json_deserialize_sb_t(json_object_get_value(obj, "command"));
		}
	}
	return dst;
}

view_console_history_entries_t json_deserialize_view_console_history_entries_t(JSON_Value *src)
{
	view_console_history_entries_t dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Array *arr = json_value_get_array(src);
		if(arr) {
			for(u32 i = 0; i < json_array_get_count(arr); ++i) {
				bba_push(dst, json_deserialize_view_console_history_entry_t(json_array_get_value(arr, i)));
			}
		}
	}
	return dst;
}

view_console_history_t json_deserialize_view_console_history_t(JSON_Value *src)
{
	view_console_history_t dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			dst.entries = json_deserialize_view_console_history_entries_t(json_object_get_value(obj, "entries"));
			dst.pos = (u32)json_object_get_number(obj, "pos");
			for(u32 i = 0; i < BB_ARRAYSIZE(dst.pad); ++i) {
				dst.pad[i] = (u8)json_object_get_number(obj, va("pad.%u", i));
			}
		}
	}
	return dst;
}

view_config_t json_deserialize_view_config_t(JSON_Value *src)
{
	view_config_t dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			dst.configColumns = json_deserialize_view_config_columns_t(json_object_get_value(obj, "configColumns"));
			dst.configThreads = json_deserialize_view_config_threads_t(json_object_get_value(obj, "configThreads"));
			dst.configFiles = json_deserialize_view_config_files_t(json_object_get_value(obj, "configFiles"));
			dst.configCategories = json_deserialize_view_config_categories_t(json_object_get_value(obj, "configCategories"));
			dst.consoleHistory = json_deserialize_view_console_history_t(json_object_get_value(obj, "consoleHistory"));
			dst.filterInput = json_deserialize_sb_t(json_object_get_value(obj, "filterInput"));
			dst.spansInput = json_deserialize_sb_t(json_object_get_value(obj, "spansInput"));
			dst.showVeryVerbose = json_object_get_boolean_safe(obj, "showVeryVerbose");
			dst.showVerbose = json_object_get_boolean_safe(obj, "showVerbose");
			dst.showLogs = json_object_get_boolean_safe(obj, "showLogs");
			dst.showDisplay = json_object_get_boolean_safe(obj, "showDisplay");
			dst.showWarnings = json_object_get_boolean_safe(obj, "showWarnings");
			dst.showErrors = json_object_get_boolean_safe(obj, "showErrors");
			dst.showFatal = json_object_get_boolean_safe(obj, "showFatal");
			dst.showSelectorTarget = json_object_get_boolean_safe(obj, "showSelectorTarget");
			dst.newNonFavoriteCategoryVisibility = json_object_get_boolean_safe(obj, "newNonFavoriteCategoryVisibility");
			dst.newThreadVisibility = json_object_get_boolean_safe(obj, "newThreadVisibility");
			dst.newFileVisibility = json_object_get_boolean_safe(obj, "newFileVisibility");
			dst.filterActive = json_object_get_boolean_safe(obj, "filterActive");
			dst.showFilterHelp = json_object_get_boolean_safe(obj, "showFilterHelp");
			dst.version = (u32)json_object_get_number(obj, "version");
		}
	}
	return dst;
}

view_config_log_t json_deserialize_view_config_log_t(JSON_Value *src)
{
	view_config_log_t dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			dst.sessionLogIndex = (u32)json_object_get_number(obj, "sessionLogIndex");
			dst.subLine = (u32)json_object_get_number(obj, "subLine");
			dst.bookmarked = json_object_get_boolean_safe(obj, "bookmarked");
			dst.selected = json_object_get_boolean_safe(obj, "selected");
		}
	}
	return dst;
}

view_config_logs_t json_deserialize_view_config_logs_t(JSON_Value *src)
{
	view_config_logs_t dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Array *arr = json_value_get_array(src);
		if(arr) {
			for(u32 i = 0; i < json_array_get_count(arr); ++i) {
				bba_push(dst, json_deserialize_view_config_log_t(json_array_get_value(arr, i)));
			}
		}
	}
	return dst;
}

view_config_log_index_t json_deserialize_view_config_log_index_t(JSON_Value *src)
{
	view_config_log_index_t dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			dst.sessionLogIndex = (u32)json_object_get_number(obj, "sessionLogIndex");
			dst.subLine = (u32)json_object_get_number(obj, "subLine");
		}
	}
	return dst;
}

view_config_log_indices_t json_deserialize_view_config_log_indices_t(JSON_Value *src)
{
	view_config_log_indices_t dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Array *arr = json_value_get_array(src);
		if(arr) {
			for(u32 i = 0; i < json_array_get_count(arr); ++i) {
				bba_push(dst, json_deserialize_view_config_log_index_t(json_array_get_value(arr, i)));
			}
		}
	}
	return dst;
}

view_session_config_t json_deserialize_view_session_config_t(JSON_Value *src)
{
	view_session_config_t dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			dst.viewConfig = json_deserialize_view_config_t(json_object_get_value(obj, "viewConfig"));
			dst.selectedLogs = json_deserialize_view_config_log_indices_t(json_object_get_value(obj, "selectedLogs"));
			dst.bookmarkedLogs = json_deserialize_view_config_log_indices_t(json_object_get_value(obj, "bookmarkedLogs"));
			dst.version = (u32)json_object_get_number(obj, "version");
			dst.pad = (u32)json_object_get_number(obj, "pad");
		}
	}
	return dst;
}

//////////////////////////////////////////////////////////////////////////

JSON_Value *json_serialize_POINT(const POINT *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		json_object_set_number(obj, "x", src->x);
		json_object_set_number(obj, "y", src->y);
	}
	return val;
}

JSON_Value *json_serialize_RECT(const RECT *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		json_object_set_number(obj, "left", src->left);
		json_object_set_number(obj, "top", src->top);
		json_object_set_number(obj, "right", src->right);
		json_object_set_number(obj, "bottom", src->bottom);
	}
	return val;
}

JSON_Value *json_serialize_WINDOWPLACEMENT(const WINDOWPLACEMENT *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		json_object_set_number(obj, "length", src->length);
		json_object_set_number(obj, "flags", src->flags);
		json_object_set_number(obj, "showCmd", src->showCmd);
		json_object_set_value(obj, "ptMinPosition", json_serialize_POINT(&src->ptMinPosition));
		json_object_set_value(obj, "ptMaxPosition", json_serialize_POINT(&src->ptMaxPosition));
		json_object_set_value(obj, "rcNormalPosition", json_serialize_RECT(&src->rcNormalPosition));
	}
	return val;
}

JSON_Value *json_serialize_configWhitelistEntry_t(const configWhitelistEntry_t *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		json_object_set_boolean(obj, "allow", src->allow);
		json_object_set_boolean(obj, "autodetectedDevkit", src->autodetectedDevkit);
		json_object_set_number(obj, "delay", src->delay);
		for(u32 i = 0; i < BB_ARRAYSIZE(src->pad); ++i) {
			json_object_set_number(obj, va("pad.%u", i), src->pad[i]);
		}
		json_object_set_value(obj, "addressPlusMask", json_serialize_sb_t(&src->addressPlusMask));
		json_object_set_value(obj, "applicationName", json_serialize_sb_t(&src->applicationName));
		json_object_set_value(obj, "comment", json_serialize_sb_t(&src->comment));
	}
	return val;
}

JSON_Value *json_serialize_configWhitelist_t(const configWhitelist_t *src)
{
	JSON_Value *val = json_value_init_array();
	JSON_Array *arr = json_value_get_array(val);
	if(arr) {
		for(u32 i = 0; i < src->count; ++i) {
			JSON_Value *child = json_serialize_configWhitelistEntry_t(src->data + i);
			if(child) {
				json_array_append_value(arr, child);
			}
		}
	}
	return val;
}

JSON_Value *json_serialize_openTargetEntry_t(const openTargetEntry_t *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		json_object_set_value(obj, "displayName", json_serialize_sb_t(&src->displayName));
		json_object_set_value(obj, "commandLine", json_serialize_sb_t(&src->commandLine));
	}
	return val;
}

JSON_Value *json_serialize_openTargetList_t(const openTargetList_t *src)
{
	JSON_Value *val = json_value_init_array();
	JSON_Array *arr = json_value_get_array(val);
	if(arr) {
		for(u32 i = 0; i < src->count; ++i) {
			JSON_Value *child = json_serialize_openTargetEntry_t(src->data + i);
			if(child) {
				json_array_append_value(arr, child);
			}
		}
	}
	return val;
}

JSON_Value *json_serialize_pathFixupEntry_t(const pathFixupEntry_t *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		json_object_set_value(obj, "src", json_serialize_sb_t(&src->src));
		json_object_set_value(obj, "dst", json_serialize_sb_t(&src->dst));
	}
	return val;
}

JSON_Value *json_serialize_pathFixupList_t(const pathFixupList_t *src)
{
	JSON_Value *val = json_value_init_array();
	JSON_Array *arr = json_value_get_array(val);
	if(arr) {
		for(u32 i = 0; i < src->count; ++i) {
			JSON_Value *child = json_serialize_pathFixupEntry_t(src->data + i);
			if(child) {
				json_array_append_value(arr, child);
			}
		}
	}
	return val;
}

JSON_Value *json_serialize_tooltipConfig(const tooltipConfig *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		json_object_set_boolean(obj, "enabled", src->enabled);
		json_object_set_boolean(obj, "overText", src->overText);
		json_object_set_boolean(obj, "overMisc", src->overMisc);
		json_object_set_boolean(obj, "onlyOverSelected", src->onlyOverSelected);
		json_object_set_number(obj, "delay", src->delay);
		for(u32 i = 0; i < BB_ARRAYSIZE(src->pad); ++i) {
			json_object_set_number(obj, va("pad.%u", i), src->pad[i]);
		}
	}
	return val;
}

JSON_Value *json_serialize_sizeConfig(const sizeConfig *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		json_object_set_number(obj, "resizeBarSize", src->resizeBarSize);
		json_object_set_number(obj, "scrollbarSize", src->scrollbarSize);
	}
	return val;
}

JSON_Value *json_serialize_config_t(const config_t *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		json_object_set_value(obj, "whitelist", json_serialize_configWhitelist_t(&src->whitelist));
		json_object_set_value(obj, "openTargets", json_serialize_openTargetList_t(&src->openTargets));
		json_object_set_value(obj, "pathFixups", json_serialize_pathFixupList_t(&src->pathFixups));
		json_object_set_value(obj, "logFontConfig", json_serialize_fontConfig_t(&src->logFontConfig));
		json_object_set_value(obj, "uiFontConfig", json_serialize_fontConfig_t(&src->uiFontConfig));
		json_object_set_value(obj, "colorscheme", json_serialize_sb_t(&src->colorscheme));
		json_object_set_value(obj, "wp", json_serialize_WINDOWPLACEMENT(&src->wp));
		json_object_set_number(obj, "version", src->version);
		json_object_set_value(obj, "viewTileMode", json_serialize_viewTileMode_t(src->viewTileMode));
		json_object_set_boolean(obj, "alternateRowBackground", src->alternateRowBackground);
		json_object_set_boolean(obj, "textShadows", src->textShadows);
		json_object_set_value(obj, "logColorUsage", json_serialize_configColorUsage(src->logColorUsage));
		json_object_set_value(obj, "tooltips", json_serialize_tooltipConfig(&src->tooltips));
		json_object_set_value(obj, "sizes", json_serialize_sizeConfig(&src->sizes));
		json_object_set_boolean(obj, "dpiAware", src->dpiAware);
		json_object_set_boolean(obj, "dpiScrollwheel", src->dpiScrollwheel);
		json_object_set_number(obj, "autoDeleteAfterDays", src->autoDeleteAfterDays);
		json_object_set_boolean(obj, "autoCloseAll", src->autoCloseAll);
		json_object_set_boolean(obj, "autoCloseManual", src->autoCloseManual);
		json_object_set_boolean(obj, "updateManagement", src->updateManagement);
		json_object_set_number(obj, "doubleClickSeconds", src->doubleClickSeconds);
		json_object_set_number(obj, "dpiScale", src->dpiScale);
		json_object_set_boolean(obj, "updateWaitForDebugger", src->updateWaitForDebugger);
		json_object_set_boolean(obj, "updatePauseAfterSuccessfulUpdate", src->updatePauseAfterSuccessfulUpdate);
		json_object_set_boolean(obj, "updatePauseAfterFailedUpdate", src->updatePauseAfterFailedUpdate);
		json_object_set_boolean(obj, "assertMessageBox", src->assertMessageBox);
		json_object_set_boolean(obj, "showDebugMenu", src->showDebugMenu);
		json_object_set_boolean(obj, "showEmptyCategories", src->showEmptyCategories);
	}
	return val;
}

JSON_Value *json_serialize_deviceCodes_t(const deviceCodes_t *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		json_object_set_value(obj, "deviceCodes", json_serialize_sbs_t(&src->deviceCodes));
	}
	return val;
}

JSON_Value *json_serialize_FILETIME(const FILETIME *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		json_object_set_number(obj, "dwLowDateTime", src->dwLowDateTime);
		json_object_set_number(obj, "dwHighDateTime", src->dwHighDateTime);
	}
	return val;
}

JSON_Value *json_serialize_new_recording_t(const new_recording_t *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		json_object_set_value(obj, "applicationName", json_serialize_sb_t(&src->applicationName));
		json_object_set_value(obj, "applicationFilename", json_serialize_sb_t(&src->applicationFilename));
		json_object_set_value(obj, "path", json_serialize_sb_t(&src->path));
		json_object_set_value(obj, "filetime", json_serialize_FILETIME(&src->filetime));
		json_object_set_boolean(obj, "openView", src->openView);
		json_object_set_value(obj, "recordingType", json_serialize_recording_type_t(src->recordingType));
		json_object_set_number(obj, "mqId", src->mqId);
		json_object_set_number(obj, "platform", src->platform);
	}
	return val;
}

JSON_Value *json_serialize_recordings_tab_config_t(const recordings_tab_config_t *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		json_object_set_value(obj, "group", json_serialize_recording_group_t(src->group));
		json_object_set_value(obj, "sort", json_serialize_recording_sort_t(src->sort));
		json_object_set_boolean(obj, "showDate", src->showDate);
		json_object_set_boolean(obj, "showTime", src->showTime);
		json_object_set_boolean(obj, "showInternal", src->showInternal);
		json_object_set_boolean(obj, "showExternal", src->showExternal);
	}
	return val;
}

JSON_Value *json_serialize_recordings_config_t(const recordings_config_t *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		for(u32 i = 0; i < BB_ARRAYSIZE(src->tabs); ++i) {
			json_object_set_value(obj, va("tabs.%u", i), json_serialize_recordings_tab_config_t(&src->tabs[i]));
		}
		json_object_set_number(obj, "width", src->width);
		json_object_set_boolean(obj, "recordingsOpen", src->recordingsOpen);
	}
	return val;
}

JSON_Value *json_serialize_updateConfig_t(const updateConfig_t *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		json_object_set_value(obj, "updateResultDir", json_serialize_sb_t(&src->updateResultDir));
		json_object_set_value(obj, "updateAvailableMessage", json_serialize_sb_t(&src->updateAvailableMessage));
		json_object_set_value(obj, "updateIgnoredMessage", json_serialize_sb_t(&src->updateIgnoredMessage));
		json_object_set_value(obj, "updateShutdownMessage", json_serialize_sb_t(&src->updateShutdownMessage));
		json_object_set_value(obj, "updateManifestDir", json_serialize_sb_t(&src->updateManifestDir));
		json_object_set_number(obj, "updateCheckMs", src->updateCheckMs);
		for(u32 i = 0; i < BB_ARRAYSIZE(src->pad); ++i) {
			json_object_set_number(obj, va("pad.%u", i), src->pad[i]);
		}
	}
	return val;
}

JSON_Value *json_serialize_site_config_t(const site_config_t *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		json_object_set_value(obj, "updates", json_serialize_updateConfig_t(&src->updates));
		json_object_set_value(obj, "bugAssignee", json_serialize_sb_t(&src->bugAssignee));
		json_object_set_value(obj, "bugProject", json_serialize_sb_t(&src->bugProject));
		json_object_set_boolean(obj, "autodetectDevkits", src->autodetectDevkits);
		json_object_set_number(obj, "bugPort", src->bugPort);
		for(u32 i = 0; i < BB_ARRAYSIZE(src->pad); ++i) {
			json_object_set_number(obj, va("pad.%u", i), src->pad[i]);
		}
	}
	return val;
}

JSON_Value *json_serialize_sbsHashEntry(const sbsHashEntry *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		json_object_set_value(obj, "key", json_serialize_sb_t(&src->key));
		json_object_set_value(obj, "values", json_serialize_sbs_t(&src->values));
	}
	return val;
}

JSON_Value *json_serialize_tag_t(const tag_t *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		json_object_set_value(obj, "name", json_serialize_sb_t(&src->name));
		json_object_set_value(obj, "categories", json_serialize_sbs_t(&src->categories));
		json_object_set_value(obj, "visibility", json_serialize_tag_visibility_t(src->visibility));
		for(u32 i = 0; i < BB_ARRAYSIZE(src->pad); ++i) {
			json_object_set_number(obj, va("pad.%u", i), src->pad[i]);
		}
	}
	return val;
}

JSON_Value *json_serialize_tags_t(const tags_t *src)
{
	JSON_Value *val = json_value_init_array();
	JSON_Array *arr = json_value_get_array(val);
	if(arr) {
		for(u32 i = 0; i < src->count; ++i) {
			JSON_Value *child = json_serialize_tag_t(src->data + i);
			if(child) {
				json_array_append_value(arr, child);
			}
		}
	}
	return val;
}

JSON_Value *json_serialize_tags_config_t(const tags_config_t *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		json_object_set_value(obj, "tags", json_serialize_tags_t(&src->tags));
	}
	return val;
}

JSON_Value *json_serialize_color_config_t(const color_config_t *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		json_object_set_value(obj, "colorName", json_serialize_styleColor_e(src->colorName));
		json_object_set_number(obj, "r", src->r);
		json_object_set_number(obj, "g", src->g);
		json_object_set_number(obj, "b", src->b);
		json_object_set_number(obj, "a", src->a);
		json_object_set_boolean(obj, "bTextShadows", src->bTextShadows);
		for(u32 i = 0; i < BB_ARRAYSIZE(src->pad); ++i) {
			json_object_set_number(obj, va("pad.%u", i), src->pad[i]);
		}
	}
	return val;
}

JSON_Value *json_serialize_colors_config_t(const colors_config_t *src)
{
	JSON_Value *val = json_value_init_array();
	JSON_Array *arr = json_value_get_array(val);
	if(arr) {
		for(u32 i = 0; i < src->count; ++i) {
			JSON_Value *child = json_serialize_color_config_t(src->data + i);
			if(child) {
				json_array_append_value(arr, child);
			}
		}
	}
	return val;
}

JSON_Value *json_serialize_theme_config_t(const theme_config_t *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		json_object_set_value(obj, "colors", json_serialize_colors_config_t(&src->colors));
	}
	return val;
}

JSON_Value *json_serialize_uuidState_t(const uuidState_t *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		json_object_set_number(obj, "timestampLow", src->timestampLow);
		json_object_set_number(obj, "timestampHi", src->timestampHi);
		json_object_set_number(obj, "clockSequence", src->clockSequence);
		json_object_set_value(obj, "nodeId", json_serialize_uuid_node_t(&src->nodeId));
	}
	return val;
}

JSON_Value *json_serialize_view_pieInstance_t(const view_pieInstance_t *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		json_object_set_boolean(obj, "selected", src->selected);
		json_object_set_boolean(obj, "visible", src->visible);
		json_object_set_number(obj, "pieInstance", src->pieInstance);
		json_object_set_boolean(obj, "primary", src->primary);
	}
	return val;
}

JSON_Value *json_serialize_view_pieInstances_t(const view_pieInstances_t *src)
{
	JSON_Value *val = json_value_init_array();
	JSON_Array *arr = json_value_get_array(val);
	if(arr) {
		for(u32 i = 0; i < src->count; ++i) {
			JSON_Value *child = json_serialize_view_pieInstance_t(src->data + i);
			if(child) {
				json_array_append_value(arr, child);
			}
		}
	}
	return val;
}

JSON_Value *json_serialize_view_config_thread_t(const view_config_thread_t *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		json_object_set_value(obj, "name", json_serialize_sb_t(&src->name));
		json_object_set_boolean(obj, "selected", src->selected);
		json_object_set_boolean(obj, "visible", src->visible);
	}
	return val;
}

JSON_Value *json_serialize_view_config_threads_t(const view_config_threads_t *src)
{
	JSON_Value *val = json_value_init_array();
	JSON_Array *arr = json_value_get_array(val);
	if(arr) {
		for(u32 i = 0; i < src->count; ++i) {
			JSON_Value *child = json_serialize_view_config_thread_t(src->data + i);
			if(child) {
				json_array_append_value(arr, child);
			}
		}
	}
	return val;
}

JSON_Value *json_serialize_view_config_file_t(const view_config_file_t *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		json_object_set_value(obj, "path", json_serialize_sb_t(&src->path));
		json_object_set_boolean(obj, "selected", src->selected);
		json_object_set_boolean(obj, "visible", src->visible);
	}
	return val;
}

JSON_Value *json_serialize_view_config_files_t(const view_config_files_t *src)
{
	JSON_Value *val = json_value_init_array();
	JSON_Array *arr = json_value_get_array(val);
	if(arr) {
		for(u32 i = 0; i < src->count; ++i) {
			JSON_Value *child = json_serialize_view_config_file_t(src->data + i);
			if(child) {
				json_array_append_value(arr, child);
			}
		}
	}
	return val;
}

JSON_Value *json_serialize_view_config_category_t(const view_config_category_t *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		json_object_set_value(obj, "name", json_serialize_sb_t(&src->name));
		json_object_set_boolean(obj, "selected", src->selected);
		json_object_set_boolean(obj, "visible", src->visible);
		json_object_set_number(obj, "depth", src->depth);
		json_object_set_boolean(obj, "disabled", src->disabled);
	}
	return val;
}

JSON_Value *json_serialize_view_config_categories_t(const view_config_categories_t *src)
{
	JSON_Value *val = json_value_init_array();
	JSON_Array *arr = json_value_get_array(val);
	if(arr) {
		for(u32 i = 0; i < src->count; ++i) {
			JSON_Value *child = json_serialize_view_config_category_t(src->data + i);
			if(child) {
				json_array_append_value(arr, child);
			}
		}
	}
	return val;
}

JSON_Value *json_serialize_view_config_column_t(const view_config_column_t *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		json_object_set_value(obj, "name", json_serialize_sb_t(&src->name));
		json_object_set_boolean(obj, "visible", src->visible);
		json_object_set_number(obj, "width", src->width);
	}
	return val;
}

JSON_Value *json_serialize_view_config_columns_t(const view_config_columns_t *src)
{
	JSON_Value *val = json_value_init_array();
	JSON_Array *arr = json_value_get_array(val);
	if(arr) {
		for(u32 i = 0; i < src->count; ++i) {
			JSON_Value *child = json_serialize_view_config_column_t(src->data + i);
			if(child) {
				json_array_append_value(arr, child);
			}
		}
	}
	return val;
}

JSON_Value *json_serialize_view_console_history_entry_t(const view_console_history_entry_t *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		json_object_set_value(obj, "command", json_serialize_sb_t(&src->command));
	}
	return val;
}

JSON_Value *json_serialize_view_console_history_entries_t(const view_console_history_entries_t *src)
{
	JSON_Value *val = json_value_init_array();
	JSON_Array *arr = json_value_get_array(val);
	if(arr) {
		for(u32 i = 0; i < src->count; ++i) {
			JSON_Value *child = json_serialize_view_console_history_entry_t(src->data + i);
			if(child) {
				json_array_append_value(arr, child);
			}
		}
	}
	return val;
}

JSON_Value *json_serialize_view_console_history_t(const view_console_history_t *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		json_object_set_value(obj, "entries", json_serialize_view_console_history_entries_t(&src->entries));
		json_object_set_number(obj, "pos", src->pos);
		for(u32 i = 0; i < BB_ARRAYSIZE(src->pad); ++i) {
			json_object_set_number(obj, va("pad.%u", i), src->pad[i]);
		}
	}
	return val;
}

JSON_Value *json_serialize_view_config_t(const view_config_t *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		json_object_set_value(obj, "configColumns", json_serialize_view_config_columns_t(&src->configColumns));
		json_object_set_value(obj, "configThreads", json_serialize_view_config_threads_t(&src->configThreads));
		json_object_set_value(obj, "configFiles", json_serialize_view_config_files_t(&src->configFiles));
		json_object_set_value(obj, "configCategories", json_serialize_view_config_categories_t(&src->configCategories));
		json_object_set_value(obj, "consoleHistory", json_serialize_view_console_history_t(&src->consoleHistory));
		json_object_set_value(obj, "filterInput", json_serialize_sb_t(&src->filterInput));
		json_object_set_value(obj, "spansInput", json_serialize_sb_t(&src->spansInput));
		json_object_set_boolean(obj, "showVeryVerbose", src->showVeryVerbose);
		json_object_set_boolean(obj, "showVerbose", src->showVerbose);
		json_object_set_boolean(obj, "showLogs", src->showLogs);
		json_object_set_boolean(obj, "showDisplay", src->showDisplay);
		json_object_set_boolean(obj, "showWarnings", src->showWarnings);
		json_object_set_boolean(obj, "showErrors", src->showErrors);
		json_object_set_boolean(obj, "showFatal", src->showFatal);
		json_object_set_boolean(obj, "showSelectorTarget", src->showSelectorTarget);
		json_object_set_boolean(obj, "newNonFavoriteCategoryVisibility", src->newNonFavoriteCategoryVisibility);
		json_object_set_boolean(obj, "newThreadVisibility", src->newThreadVisibility);
		json_object_set_boolean(obj, "newFileVisibility", src->newFileVisibility);
		json_object_set_boolean(obj, "filterActive", src->filterActive);
		json_object_set_boolean(obj, "showFilterHelp", src->showFilterHelp);
		json_object_set_number(obj, "version", src->version);
	}
	return val;
}

JSON_Value *json_serialize_view_config_log_t(const view_config_log_t *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		json_object_set_number(obj, "sessionLogIndex", src->sessionLogIndex);
		json_object_set_number(obj, "subLine", src->subLine);
		json_object_set_boolean(obj, "bookmarked", src->bookmarked);
		json_object_set_boolean(obj, "selected", src->selected);
	}
	return val;
}

JSON_Value *json_serialize_view_config_logs_t(const view_config_logs_t *src)
{
	JSON_Value *val = json_value_init_array();
	JSON_Array *arr = json_value_get_array(val);
	if(arr) {
		for(u32 i = 0; i < src->count; ++i) {
			JSON_Value *child = json_serialize_view_config_log_t(src->data + i);
			if(child) {
				json_array_append_value(arr, child);
			}
		}
	}
	return val;
}

JSON_Value *json_serialize_view_config_log_index_t(const view_config_log_index_t *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		json_object_set_number(obj, "sessionLogIndex", src->sessionLogIndex);
		json_object_set_number(obj, "subLine", src->subLine);
	}
	return val;
}

JSON_Value *json_serialize_view_config_log_indices_t(const view_config_log_indices_t *src)
{
	JSON_Value *val = json_value_init_array();
	JSON_Array *arr = json_value_get_array(val);
	if(arr) {
		for(u32 i = 0; i < src->count; ++i) {
			JSON_Value *child = json_serialize_view_config_log_index_t(src->data + i);
			if(child) {
				json_array_append_value(arr, child);
			}
		}
	}
	return val;
}

JSON_Value *json_serialize_view_session_config_t(const view_session_config_t *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		json_object_set_value(obj, "viewConfig", json_serialize_view_config_t(&src->viewConfig));
		json_object_set_value(obj, "selectedLogs", json_serialize_view_config_log_indices_t(&src->selectedLogs));
		json_object_set_value(obj, "bookmarkedLogs", json_serialize_view_config_log_indices_t(&src->bookmarkedLogs));
		json_object_set_number(obj, "version", src->version);
		json_object_set_number(obj, "pad", src->pad);
	}
	return val;
}

//////////////////////////////////////////////////////////////////////////

configColorUsage json_deserialize_configColorUsage(JSON_Value *src)
{
	configColorUsage dst = kConfigColors_Full;
	if(src) {
		const char *str = json_value_get_string(src);
		if(str) {
			if(!strcmp(str, "kConfigColors_Full")) { dst = kConfigColors_Full; }
			if(!strcmp(str, "kConfigColors_BgAsFg")) { dst = kConfigColors_BgAsFg; }
			if(!strcmp(str, "kConfigColors_NoBg")) { dst = kConfigColors_NoBg; }
			if(!strcmp(str, "kConfigColors_None")) { dst = kConfigColors_None; }
			if(!strcmp(str, "kConfigColors_Count")) { dst = kConfigColors_Count; }
		}
	}
	return dst;
}

viewTileMode_t json_deserialize_viewTileMode_t(JSON_Value *src)
{
	viewTileMode_t dst = kViewTileMode_Auto;
	if(src) {
		const char *str = json_value_get_string(src);
		if(str) {
			if(!strcmp(str, "kViewTileMode_Auto")) { dst = kViewTileMode_Auto; }
			if(!strcmp(str, "kViewTileMode_PreferColumns")) { dst = kViewTileMode_PreferColumns; }
			if(!strcmp(str, "kViewTileMode_PreferRows")) { dst = kViewTileMode_PreferRows; }
			if(!strcmp(str, "kViewTileMode_Columns")) { dst = kViewTileMode_Columns; }
			if(!strcmp(str, "kViewTileMode_Rows")) { dst = kViewTileMode_Rows; }
			if(!strcmp(str, "kViewTileMode_None")) { dst = kViewTileMode_None; }
			if(!strcmp(str, "kViewTileMode_Count")) { dst = kViewTileMode_Count; }
		}
	}
	return dst;
}

recording_tab_t json_deserialize_recording_tab_t(JSON_Value *src)
{
	recording_tab_t dst = kRecordingTab_Count;
	if(src) {
		const char *str = json_value_get_string(src);
		if(str) {
			if(!strcmp(str, "kRecordingTab_Internal")) { dst = kRecordingTab_Internal; }
			if(!strcmp(str, "kRecordingTab_External")) { dst = kRecordingTab_External; }
			if(!strcmp(str, "kRecordingTab_Count")) { dst = kRecordingTab_Count; }
		}
	}
	return dst;
}

recording_sort_t json_deserialize_recording_sort_t(JSON_Value *src)
{
	recording_sort_t dst = kRecordingSort_Count;
	if(src) {
		const char *str = json_value_get_string(src);
		if(str) {
			if(!strcmp(str, "kRecordingSort_StartTime")) { dst = kRecordingSort_StartTime; }
			if(!strcmp(str, "kRecordingSort_Application")) { dst = kRecordingSort_Application; }
			if(!strcmp(str, "kRecordingSort_Count")) { dst = kRecordingSort_Count; }
		}
	}
	return dst;
}

recording_group_t json_deserialize_recording_group_t(JSON_Value *src)
{
	recording_group_t dst = kRecordingGroup_Count;
	if(src) {
		const char *str = json_value_get_string(src);
		if(str) {
			if(!strcmp(str, "kRecordingGroup_None")) { dst = kRecordingGroup_None; }
			if(!strcmp(str, "kRecordingGroup_Application")) { dst = kRecordingGroup_Application; }
			if(!strcmp(str, "kRecordingGroup_Count")) { dst = kRecordingGroup_Count; }
		}
	}
	return dst;
}

recording_type_t json_deserialize_recording_type_t(JSON_Value *src)
{
	recording_type_t dst = kRecordingType_Count;
	if(src) {
		const char *str = json_value_get_string(src);
		if(str) {
			if(!strcmp(str, "kRecordingType_Normal")) { dst = kRecordingType_Normal; }
			if(!strcmp(str, "kRecordingType_ExistingFile")) { dst = kRecordingType_ExistingFile; }
			if(!strcmp(str, "kRecordingType_MainLog")) { dst = kRecordingType_MainLog; }
			if(!strcmp(str, "kRecordingType_ExternalFile")) { dst = kRecordingType_ExternalFile; }
			if(!strcmp(str, "kRecordingType_Count")) { dst = kRecordingType_Count; }
		}
	}
	return dst;
}

tag_visibility_t json_deserialize_tag_visibility_t(JSON_Value *src)
{
	tag_visibility_t dst = kTagVisibility_Count;
	if(src) {
		const char *str = json_value_get_string(src);
		if(str) {
			if(!strcmp(str, "kTagVisibility_Normal")) { dst = kTagVisibility_Normal; }
			if(!strcmp(str, "kTagVisibility_AlwaysVisible")) { dst = kTagVisibility_AlwaysVisible; }
			if(!strcmp(str, "kTagVisibility_AlwaysHidden")) { dst = kTagVisibility_AlwaysHidden; }
			if(!strcmp(str, "kTagVisibility_Count")) { dst = kTagVisibility_Count; }
		}
	}
	return dst;
}

styleColor_e json_deserialize_styleColor_e(JSON_Value *src)
{
	styleColor_e dst = kStyleColor_Count;
	if(src) {
		const char *str = json_value_get_string(src);
		if(str) {
			if(!strcmp(str, "kStyleColor_kBBColor_Default")) { dst = kStyleColor_kBBColor_Default; }
			if(!strcmp(str, "kStyleColor_kBBColor_Evergreen_Black")) { dst = kStyleColor_kBBColor_Evergreen_Black; }
			if(!strcmp(str, "kStyleColor_kBBColor_Evergreen_Red")) { dst = kStyleColor_kBBColor_Evergreen_Red; }
			if(!strcmp(str, "kStyleColor_kBBColor_Evergreen_Green")) { dst = kStyleColor_kBBColor_Evergreen_Green; }
			if(!strcmp(str, "kStyleColor_kBBColor_Evergreen_Yellow")) { dst = kStyleColor_kBBColor_Evergreen_Yellow; }
			if(!strcmp(str, "kStyleColor_kBBColor_Evergreen_Blue")) { dst = kStyleColor_kBBColor_Evergreen_Blue; }
			if(!strcmp(str, "kStyleColor_kBBColor_Evergreen_Cyan")) { dst = kStyleColor_kBBColor_Evergreen_Cyan; }
			if(!strcmp(str, "kStyleColor_kBBColor_Evergreen_Pink")) { dst = kStyleColor_kBBColor_Evergreen_Pink; }
			if(!strcmp(str, "kStyleColor_kBBColor_Evergreen_White")) { dst = kStyleColor_kBBColor_Evergreen_White; }
			if(!strcmp(str, "kStyleColor_kBBColor_Evergreen_LightBlue")) { dst = kStyleColor_kBBColor_Evergreen_LightBlue; }
			if(!strcmp(str, "kStyleColor_kBBColor_Evergreen_Orange")) { dst = kStyleColor_kBBColor_Evergreen_Orange; }
			if(!strcmp(str, "kStyleColor_kBBColor_Evergreen_LightBlueAlt")) { dst = kStyleColor_kBBColor_Evergreen_LightBlueAlt; }
			if(!strcmp(str, "kStyleColor_kBBColor_Evergreen_OrangeAlt")) { dst = kStyleColor_kBBColor_Evergreen_OrangeAlt; }
			if(!strcmp(str, "kStyleColor_kBBColor_Evergreen_MediumBlue")) { dst = kStyleColor_kBBColor_Evergreen_MediumBlue; }
			if(!strcmp(str, "kStyleColor_kBBColor_Evergreen_Amber")) { dst = kStyleColor_kBBColor_Evergreen_Amber; }
			if(!strcmp(str, "kStyleColor_kBBColor_UE4_Black")) { dst = kStyleColor_kBBColor_UE4_Black; }
			if(!strcmp(str, "kStyleColor_kBBColor_UE4_DarkRed")) { dst = kStyleColor_kBBColor_UE4_DarkRed; }
			if(!strcmp(str, "kStyleColor_kBBColor_UE4_DarkGreen")) { dst = kStyleColor_kBBColor_UE4_DarkGreen; }
			if(!strcmp(str, "kStyleColor_kBBColor_UE4_DarkBlue")) { dst = kStyleColor_kBBColor_UE4_DarkBlue; }
			if(!strcmp(str, "kStyleColor_kBBColor_UE4_DarkYellow")) { dst = kStyleColor_kBBColor_UE4_DarkYellow; }
			if(!strcmp(str, "kStyleColor_kBBColor_UE4_DarkCyan")) { dst = kStyleColor_kBBColor_UE4_DarkCyan; }
			if(!strcmp(str, "kStyleColor_kBBColor_UE4_DarkPurple")) { dst = kStyleColor_kBBColor_UE4_DarkPurple; }
			if(!strcmp(str, "kStyleColor_kBBColor_UE4_DarkWhite")) { dst = kStyleColor_kBBColor_UE4_DarkWhite; }
			if(!strcmp(str, "kStyleColor_kBBColor_UE4_Red")) { dst = kStyleColor_kBBColor_UE4_Red; }
			if(!strcmp(str, "kStyleColor_kBBColor_UE4_Green")) { dst = kStyleColor_kBBColor_UE4_Green; }
			if(!strcmp(str, "kStyleColor_kBBColor_UE4_Blue")) { dst = kStyleColor_kBBColor_UE4_Blue; }
			if(!strcmp(str, "kStyleColor_kBBColor_UE4_Yellow")) { dst = kStyleColor_kBBColor_UE4_Yellow; }
			if(!strcmp(str, "kStyleColor_kBBColor_UE4_Cyan")) { dst = kStyleColor_kBBColor_UE4_Cyan; }
			if(!strcmp(str, "kStyleColor_kBBColor_UE4_Purple")) { dst = kStyleColor_kBBColor_UE4_Purple; }
			if(!strcmp(str, "kStyleColor_kBBColor_UE4_White")) { dst = kStyleColor_kBBColor_UE4_White; }
			if(!strcmp(str, "kStyleColor_ActiveSession")) { dst = kStyleColor_ActiveSession; }
			if(!strcmp(str, "kStyleColor_InactiveSession")) { dst = kStyleColor_InactiveSession; }
			if(!strcmp(str, "kStyleColor_LogLevel_VeryVerbose")) { dst = kStyleColor_LogLevel_VeryVerbose; }
			if(!strcmp(str, "kStyleColor_LogLevel_Verbose")) { dst = kStyleColor_LogLevel_Verbose; }
			if(!strcmp(str, "kStyleColor_LogLevel_Log")) { dst = kStyleColor_LogLevel_Log; }
			if(!strcmp(str, "kStyleColor_LogLevel_Display")) { dst = kStyleColor_LogLevel_Display; }
			if(!strcmp(str, "kStyleColor_LogLevel_Warning")) { dst = kStyleColor_LogLevel_Warning; }
			if(!strcmp(str, "kStyleColor_LogLevel_Error")) { dst = kStyleColor_LogLevel_Error; }
			if(!strcmp(str, "kStyleColor_LogLevel_Fatal")) { dst = kStyleColor_LogLevel_Fatal; }
			if(!strcmp(str, "kStyleColor_Multiline")) { dst = kStyleColor_Multiline; }
			if(!strcmp(str, "kStyleColor_LogBackground_Normal")) { dst = kStyleColor_LogBackground_Normal; }
			if(!strcmp(str, "kStyleColor_LogBackground_NormalAlternate0")) { dst = kStyleColor_LogBackground_NormalAlternate0; }
			if(!strcmp(str, "kStyleColor_LogBackground_NormalAlternate1")) { dst = kStyleColor_LogBackground_NormalAlternate1; }
			if(!strcmp(str, "kStyleColor_LogBackground_Bookmarked")) { dst = kStyleColor_LogBackground_Bookmarked; }
			if(!strcmp(str, "kStyleColor_LogBackground_BookmarkedAlternate0")) { dst = kStyleColor_LogBackground_BookmarkedAlternate0; }
			if(!strcmp(str, "kStyleColor_LogBackground_BookmarkedAlternate1")) { dst = kStyleColor_LogBackground_BookmarkedAlternate1; }
			if(!strcmp(str, "kStyleColor_ResizeNormal")) { dst = kStyleColor_ResizeNormal; }
			if(!strcmp(str, "kStyleColor_ResizeHovered")) { dst = kStyleColor_ResizeHovered; }
			if(!strcmp(str, "kStyleColor_ResizeActive")) { dst = kStyleColor_ResizeActive; }
			if(!strcmp(str, "kStyleColor_MessageBoxBackground0")) { dst = kStyleColor_MessageBoxBackground0; }
			if(!strcmp(str, "kStyleColor_MessageBoxBackground1")) { dst = kStyleColor_MessageBoxBackground1; }
			if(!strcmp(str, "kStyleColor_TextShadow")) { dst = kStyleColor_TextShadow; }
			if(!strcmp(str, "kStyleColor_Count")) { dst = kStyleColor_Count; }
		}
	}
	return dst;
}

vfilter_type_e json_deserialize_vfilter_type_e(JSON_Value *src)
{
	vfilter_type_e dst = kVF_Count;
	if(src) {
		const char *str = json_value_get_string(src);
		if(str) {
			if(!strcmp(str, "kVF_Standard")) { dst = kVF_Standard; }
			if(!strcmp(str, "kVF_SQL")) { dst = kVF_SQL; }
			if(!strcmp(str, "kVF_Legacy")) { dst = kVF_Legacy; }
			if(!strcmp(str, "kVF_Count")) { dst = kVF_Count; }
		}
	}
	return dst;
}

vfilter_token_type_e json_deserialize_vfilter_token_type_e(JSON_Value *src)
{
	vfilter_token_type_e dst = kVFT_Count;
	if(src) {
		const char *str = json_value_get_string(src);
		if(str) {
			if(!strcmp(str, "kVFT_Invalid")) { dst = kVFT_Invalid; }
			if(!strcmp(str, "kVFT_OpenParen")) { dst = kVFT_OpenParen; }
			if(!strcmp(str, "kVFT_CloseParen")) { dst = kVFT_CloseParen; }
			if(!strcmp(str, "kVFT_String")) { dst = kVFT_String; }
			if(!strcmp(str, "kVFT_LessThan")) { dst = kVFT_LessThan; }
			if(!strcmp(str, "kVFT_LessThanEquals")) { dst = kVFT_LessThanEquals; }
			if(!strcmp(str, "kVFT_Equals")) { dst = kVFT_Equals; }
			if(!strcmp(str, "kVFT_NotEquals")) { dst = kVFT_NotEquals; }
			if(!strcmp(str, "kVFT_GreaterThan")) { dst = kVFT_GreaterThan; }
			if(!strcmp(str, "kVFT_GreaterThanEquals")) { dst = kVFT_GreaterThanEquals; }
			if(!strcmp(str, "kVFT_Matches")) { dst = kVFT_Matches; }
			if(!strcmp(str, "kVFT_And")) { dst = kVFT_And; }
			if(!strcmp(str, "kVFT_Or")) { dst = kVFT_Or; }
			if(!strcmp(str, "kVFT_Not")) { dst = kVFT_Not; }
			if(!strcmp(str, "kVFT_Contains")) { dst = kVFT_Contains; }
			if(!strcmp(str, "kVFT_StartsWith")) { dst = kVFT_StartsWith; }
			if(!strcmp(str, "kVFT_EndsWith")) { dst = kVFT_EndsWith; }
			if(!strcmp(str, "kVFT_DeltaMillisecondsAbsolute")) { dst = kVFT_DeltaMillisecondsAbsolute; }
			if(!strcmp(str, "kVFT_DeltaMillisecondsViewRelative")) { dst = kVFT_DeltaMillisecondsViewRelative; }
			if(!strcmp(str, "kVFT_Filename")) { dst = kVFT_Filename; }
			if(!strcmp(str, "kVFT_Thread")) { dst = kVFT_Thread; }
			if(!strcmp(str, "kVFT_PIEInstance")) { dst = kVFT_PIEInstance; }
			if(!strcmp(str, "kVFT_Category")) { dst = kVFT_Category; }
			if(!strcmp(str, "kVFT_Verbosity")) { dst = kVFT_Verbosity; }
			if(!strcmp(str, "kVFT_Text")) { dst = kVFT_Text; }
			if(!strcmp(str, "kVFT_Number")) { dst = kVFT_Number; }
			if(!strcmp(str, "kVFT_Count")) { dst = kVFT_Count; }
		}
	}
	return dst;
}

//////////////////////////////////////////////////////////////////////////

JSON_Value *json_serialize_configColorUsage(const configColorUsage src)
{
	const char *str = "";
	switch(src) {
		case kConfigColors_Full: str = "kConfigColors_Full"; break;
		case kConfigColors_BgAsFg: str = "kConfigColors_BgAsFg"; break;
		case kConfigColors_NoBg: str = "kConfigColors_NoBg"; break;
		case kConfigColors_None: str = "kConfigColors_None"; break;
		case kConfigColors_Count: str = "kConfigColors_Count"; break;
	}
	JSON_Value *val = json_value_init_string(str);
	return val;
}

JSON_Value *json_serialize_viewTileMode_t(const viewTileMode_t src)
{
	const char *str = "";
	switch(src) {
		case kViewTileMode_Auto: str = "kViewTileMode_Auto"; break;
		case kViewTileMode_PreferColumns: str = "kViewTileMode_PreferColumns"; break;
		case kViewTileMode_PreferRows: str = "kViewTileMode_PreferRows"; break;
		case kViewTileMode_Columns: str = "kViewTileMode_Columns"; break;
		case kViewTileMode_Rows: str = "kViewTileMode_Rows"; break;
		case kViewTileMode_None: str = "kViewTileMode_None"; break;
		case kViewTileMode_Count: str = "kViewTileMode_Count"; break;
	}
	JSON_Value *val = json_value_init_string(str);
	return val;
}

JSON_Value *json_serialize_recording_tab_t(const recording_tab_t src)
{
	const char *str = "";
	switch(src) {
		case kRecordingTab_Internal: str = "kRecordingTab_Internal"; break;
		case kRecordingTab_External: str = "kRecordingTab_External"; break;
		case kRecordingTab_Count: str = "kRecordingTab_Count"; break;
	}
	JSON_Value *val = json_value_init_string(str);
	return val;
}

JSON_Value *json_serialize_recording_sort_t(const recording_sort_t src)
{
	const char *str = "";
	switch(src) {
		case kRecordingSort_StartTime: str = "kRecordingSort_StartTime"; break;
		case kRecordingSort_Application: str = "kRecordingSort_Application"; break;
		case kRecordingSort_Count: str = "kRecordingSort_Count"; break;
	}
	JSON_Value *val = json_value_init_string(str);
	return val;
}

JSON_Value *json_serialize_recording_group_t(const recording_group_t src)
{
	const char *str = "";
	switch(src) {
		case kRecordingGroup_None: str = "kRecordingGroup_None"; break;
		case kRecordingGroup_Application: str = "kRecordingGroup_Application"; break;
		case kRecordingGroup_Count: str = "kRecordingGroup_Count"; break;
	}
	JSON_Value *val = json_value_init_string(str);
	return val;
}

JSON_Value *json_serialize_recording_type_t(const recording_type_t src)
{
	const char *str = "";
	switch(src) {
		case kRecordingType_Normal: str = "kRecordingType_Normal"; break;
		case kRecordingType_ExistingFile: str = "kRecordingType_ExistingFile"; break;
		case kRecordingType_MainLog: str = "kRecordingType_MainLog"; break;
		case kRecordingType_ExternalFile: str = "kRecordingType_ExternalFile"; break;
		case kRecordingType_Count: str = "kRecordingType_Count"; break;
	}
	JSON_Value *val = json_value_init_string(str);
	return val;
}

JSON_Value *json_serialize_tag_visibility_t(const tag_visibility_t src)
{
	const char *str = "";
	switch(src) {
		case kTagVisibility_Normal: str = "kTagVisibility_Normal"; break;
		case kTagVisibility_AlwaysVisible: str = "kTagVisibility_AlwaysVisible"; break;
		case kTagVisibility_AlwaysHidden: str = "kTagVisibility_AlwaysHidden"; break;
		case kTagVisibility_Count: str = "kTagVisibility_Count"; break;
	}
	JSON_Value *val = json_value_init_string(str);
	return val;
}

JSON_Value *json_serialize_styleColor_e(const styleColor_e src)
{
	const char *str = "";
	switch(src) {
		case kStyleColor_kBBColor_Default: str = "kStyleColor_kBBColor_Default"; break;
		case kStyleColor_kBBColor_Evergreen_Black: str = "kStyleColor_kBBColor_Evergreen_Black"; break;
		case kStyleColor_kBBColor_Evergreen_Red: str = "kStyleColor_kBBColor_Evergreen_Red"; break;
		case kStyleColor_kBBColor_Evergreen_Green: str = "kStyleColor_kBBColor_Evergreen_Green"; break;
		case kStyleColor_kBBColor_Evergreen_Yellow: str = "kStyleColor_kBBColor_Evergreen_Yellow"; break;
		case kStyleColor_kBBColor_Evergreen_Blue: str = "kStyleColor_kBBColor_Evergreen_Blue"; break;
		case kStyleColor_kBBColor_Evergreen_Cyan: str = "kStyleColor_kBBColor_Evergreen_Cyan"; break;
		case kStyleColor_kBBColor_Evergreen_Pink: str = "kStyleColor_kBBColor_Evergreen_Pink"; break;
		case kStyleColor_kBBColor_Evergreen_White: str = "kStyleColor_kBBColor_Evergreen_White"; break;
		case kStyleColor_kBBColor_Evergreen_LightBlue: str = "kStyleColor_kBBColor_Evergreen_LightBlue"; break;
		case kStyleColor_kBBColor_Evergreen_Orange: str = "kStyleColor_kBBColor_Evergreen_Orange"; break;
		case kStyleColor_kBBColor_Evergreen_LightBlueAlt: str = "kStyleColor_kBBColor_Evergreen_LightBlueAlt"; break;
		case kStyleColor_kBBColor_Evergreen_OrangeAlt: str = "kStyleColor_kBBColor_Evergreen_OrangeAlt"; break;
		case kStyleColor_kBBColor_Evergreen_MediumBlue: str = "kStyleColor_kBBColor_Evergreen_MediumBlue"; break;
		case kStyleColor_kBBColor_Evergreen_Amber: str = "kStyleColor_kBBColor_Evergreen_Amber"; break;
		case kStyleColor_kBBColor_UE4_Black: str = "kStyleColor_kBBColor_UE4_Black"; break;
		case kStyleColor_kBBColor_UE4_DarkRed: str = "kStyleColor_kBBColor_UE4_DarkRed"; break;
		case kStyleColor_kBBColor_UE4_DarkGreen: str = "kStyleColor_kBBColor_UE4_DarkGreen"; break;
		case kStyleColor_kBBColor_UE4_DarkBlue: str = "kStyleColor_kBBColor_UE4_DarkBlue"; break;
		case kStyleColor_kBBColor_UE4_DarkYellow: str = "kStyleColor_kBBColor_UE4_DarkYellow"; break;
		case kStyleColor_kBBColor_UE4_DarkCyan: str = "kStyleColor_kBBColor_UE4_DarkCyan"; break;
		case kStyleColor_kBBColor_UE4_DarkPurple: str = "kStyleColor_kBBColor_UE4_DarkPurple"; break;
		case kStyleColor_kBBColor_UE4_DarkWhite: str = "kStyleColor_kBBColor_UE4_DarkWhite"; break;
		case kStyleColor_kBBColor_UE4_Red: str = "kStyleColor_kBBColor_UE4_Red"; break;
		case kStyleColor_kBBColor_UE4_Green: str = "kStyleColor_kBBColor_UE4_Green"; break;
		case kStyleColor_kBBColor_UE4_Blue: str = "kStyleColor_kBBColor_UE4_Blue"; break;
		case kStyleColor_kBBColor_UE4_Yellow: str = "kStyleColor_kBBColor_UE4_Yellow"; break;
		case kStyleColor_kBBColor_UE4_Cyan: str = "kStyleColor_kBBColor_UE4_Cyan"; break;
		case kStyleColor_kBBColor_UE4_Purple: str = "kStyleColor_kBBColor_UE4_Purple"; break;
		case kStyleColor_kBBColor_UE4_White: str = "kStyleColor_kBBColor_UE4_White"; break;
		case kStyleColor_ActiveSession: str = "kStyleColor_ActiveSession"; break;
		case kStyleColor_InactiveSession: str = "kStyleColor_InactiveSession"; break;
		case kStyleColor_LogLevel_VeryVerbose: str = "kStyleColor_LogLevel_VeryVerbose"; break;
		case kStyleColor_LogLevel_Verbose: str = "kStyleColor_LogLevel_Verbose"; break;
		case kStyleColor_LogLevel_Log: str = "kStyleColor_LogLevel_Log"; break;
		case kStyleColor_LogLevel_Display: str = "kStyleColor_LogLevel_Display"; break;
		case kStyleColor_LogLevel_Warning: str = "kStyleColor_LogLevel_Warning"; break;
		case kStyleColor_LogLevel_Error: str = "kStyleColor_LogLevel_Error"; break;
		case kStyleColor_LogLevel_Fatal: str = "kStyleColor_LogLevel_Fatal"; break;
		case kStyleColor_Multiline: str = "kStyleColor_Multiline"; break;
		case kStyleColor_LogBackground_Normal: str = "kStyleColor_LogBackground_Normal"; break;
		case kStyleColor_LogBackground_NormalAlternate0: str = "kStyleColor_LogBackground_NormalAlternate0"; break;
		case kStyleColor_LogBackground_NormalAlternate1: str = "kStyleColor_LogBackground_NormalAlternate1"; break;
		case kStyleColor_LogBackground_Bookmarked: str = "kStyleColor_LogBackground_Bookmarked"; break;
		case kStyleColor_LogBackground_BookmarkedAlternate0: str = "kStyleColor_LogBackground_BookmarkedAlternate0"; break;
		case kStyleColor_LogBackground_BookmarkedAlternate1: str = "kStyleColor_LogBackground_BookmarkedAlternate1"; break;
		case kStyleColor_ResizeNormal: str = "kStyleColor_ResizeNormal"; break;
		case kStyleColor_ResizeHovered: str = "kStyleColor_ResizeHovered"; break;
		case kStyleColor_ResizeActive: str = "kStyleColor_ResizeActive"; break;
		case kStyleColor_MessageBoxBackground0: str = "kStyleColor_MessageBoxBackground0"; break;
		case kStyleColor_MessageBoxBackground1: str = "kStyleColor_MessageBoxBackground1"; break;
		case kStyleColor_TextShadow: str = "kStyleColor_TextShadow"; break;
		case kStyleColor_Count: str = "kStyleColor_Count"; break;
	}
	JSON_Value *val = json_value_init_string(str);
	return val;
}

JSON_Value *json_serialize_vfilter_type_e(const vfilter_type_e src)
{
	const char *str = "";
	switch(src) {
		case kVF_Standard: str = "kVF_Standard"; break;
		case kVF_SQL: str = "kVF_SQL"; break;
		case kVF_Legacy: str = "kVF_Legacy"; break;
		case kVF_Count: str = "kVF_Count"; break;
	}
	JSON_Value *val = json_value_init_string(str);
	return val;
}

JSON_Value *json_serialize_vfilter_token_type_e(const vfilter_token_type_e src)
{
	const char *str = "";
	switch(src) {
		case kVFT_Invalid: str = "kVFT_Invalid"; break;
		case kVFT_OpenParen: str = "kVFT_OpenParen"; break;
		case kVFT_CloseParen: str = "kVFT_CloseParen"; break;
		case kVFT_String: str = "kVFT_String"; break;
		case kVFT_LessThan: str = "kVFT_LessThan"; break;
		case kVFT_LessThanEquals: str = "kVFT_LessThanEquals"; break;
		case kVFT_Equals: str = "kVFT_Equals"; break;
		case kVFT_NotEquals: str = "kVFT_NotEquals"; break;
		case kVFT_GreaterThan: str = "kVFT_GreaterThan"; break;
		case kVFT_GreaterThanEquals: str = "kVFT_GreaterThanEquals"; break;
		case kVFT_Matches: str = "kVFT_Matches"; break;
		case kVFT_And: str = "kVFT_And"; break;
		case kVFT_Or: str = "kVFT_Or"; break;
		case kVFT_Not: str = "kVFT_Not"; break;
		case kVFT_Contains: str = "kVFT_Contains"; break;
		case kVFT_StartsWith: str = "kVFT_StartsWith"; break;
		case kVFT_EndsWith: str = "kVFT_EndsWith"; break;
		case kVFT_DeltaMillisecondsAbsolute: str = "kVFT_DeltaMillisecondsAbsolute"; break;
		case kVFT_DeltaMillisecondsViewRelative: str = "kVFT_DeltaMillisecondsViewRelative"; break;
		case kVFT_Filename: str = "kVFT_Filename"; break;
		case kVFT_Thread: str = "kVFT_Thread"; break;
		case kVFT_PIEInstance: str = "kVFT_PIEInstance"; break;
		case kVFT_Category: str = "kVFT_Category"; break;
		case kVFT_Verbosity: str = "kVFT_Verbosity"; break;
		case kVFT_Text: str = "kVFT_Text"; break;
		case kVFT_Number: str = "kVFT_Number"; break;
		case kVFT_Count: str = "kVFT_Count"; break;
	}
	JSON_Value *val = json_value_init_string(str);
	return val;
}

//////////////////////////////////////////////////////////////////////////

configColorUsage configColorUsage_from_string(const char *src)
{
	configColorUsage dst = kConfigColors_Full;
	if(src) {
		if(!strcmp(src, "kConfigColors_Full")) { dst = kConfigColors_Full; }
		if(!strcmp(src, "kConfigColors_BgAsFg")) { dst = kConfigColors_BgAsFg; }
		if(!strcmp(src, "kConfigColors_NoBg")) { dst = kConfigColors_NoBg; }
		if(!strcmp(src, "kConfigColors_None")) { dst = kConfigColors_None; }
		if(!strcmp(src, "kConfigColors_Count")) { dst = kConfigColors_Count; }
	}
	return dst;
}

viewTileMode_t viewTileMode_t_from_string(const char *src)
{
	viewTileMode_t dst = kViewTileMode_Auto;
	if(src) {
		if(!strcmp(src, "kViewTileMode_Auto")) { dst = kViewTileMode_Auto; }
		if(!strcmp(src, "kViewTileMode_PreferColumns")) { dst = kViewTileMode_PreferColumns; }
		if(!strcmp(src, "kViewTileMode_PreferRows")) { dst = kViewTileMode_PreferRows; }
		if(!strcmp(src, "kViewTileMode_Columns")) { dst = kViewTileMode_Columns; }
		if(!strcmp(src, "kViewTileMode_Rows")) { dst = kViewTileMode_Rows; }
		if(!strcmp(src, "kViewTileMode_None")) { dst = kViewTileMode_None; }
		if(!strcmp(src, "kViewTileMode_Count")) { dst = kViewTileMode_Count; }
	}
	return dst;
}

recording_tab_t recording_tab_t_from_string(const char *src)
{
	recording_tab_t dst = kRecordingTab_Count;
	if(src) {
		if(!strcmp(src, "kRecordingTab_Internal")) { dst = kRecordingTab_Internal; }
		if(!strcmp(src, "kRecordingTab_External")) { dst = kRecordingTab_External; }
		if(!strcmp(src, "kRecordingTab_Count")) { dst = kRecordingTab_Count; }
	}
	return dst;
}

recording_sort_t recording_sort_t_from_string(const char *src)
{
	recording_sort_t dst = kRecordingSort_Count;
	if(src) {
		if(!strcmp(src, "kRecordingSort_StartTime")) { dst = kRecordingSort_StartTime; }
		if(!strcmp(src, "kRecordingSort_Application")) { dst = kRecordingSort_Application; }
		if(!strcmp(src, "kRecordingSort_Count")) { dst = kRecordingSort_Count; }
	}
	return dst;
}

recording_group_t recording_group_t_from_string(const char *src)
{
	recording_group_t dst = kRecordingGroup_Count;
	if(src) {
		if(!strcmp(src, "kRecordingGroup_None")) { dst = kRecordingGroup_None; }
		if(!strcmp(src, "kRecordingGroup_Application")) { dst = kRecordingGroup_Application; }
		if(!strcmp(src, "kRecordingGroup_Count")) { dst = kRecordingGroup_Count; }
	}
	return dst;
}

recording_type_t recording_type_t_from_string(const char *src)
{
	recording_type_t dst = kRecordingType_Count;
	if(src) {
		if(!strcmp(src, "kRecordingType_Normal")) { dst = kRecordingType_Normal; }
		if(!strcmp(src, "kRecordingType_ExistingFile")) { dst = kRecordingType_ExistingFile; }
		if(!strcmp(src, "kRecordingType_MainLog")) { dst = kRecordingType_MainLog; }
		if(!strcmp(src, "kRecordingType_ExternalFile")) { dst = kRecordingType_ExternalFile; }
		if(!strcmp(src, "kRecordingType_Count")) { dst = kRecordingType_Count; }
	}
	return dst;
}

tag_visibility_t tag_visibility_t_from_string(const char *src)
{
	tag_visibility_t dst = kTagVisibility_Count;
	if(src) {
		if(!strcmp(src, "kTagVisibility_Normal")) { dst = kTagVisibility_Normal; }
		if(!strcmp(src, "kTagVisibility_AlwaysVisible")) { dst = kTagVisibility_AlwaysVisible; }
		if(!strcmp(src, "kTagVisibility_AlwaysHidden")) { dst = kTagVisibility_AlwaysHidden; }
		if(!strcmp(src, "kTagVisibility_Count")) { dst = kTagVisibility_Count; }
	}
	return dst;
}

styleColor_e styleColor_e_from_string(const char *src)
{
	styleColor_e dst = kStyleColor_Count;
	if(src) {
		if(!strcmp(src, "kStyleColor_kBBColor_Default")) { dst = kStyleColor_kBBColor_Default; }
		if(!strcmp(src, "kStyleColor_kBBColor_Evergreen_Black")) { dst = kStyleColor_kBBColor_Evergreen_Black; }
		if(!strcmp(src, "kStyleColor_kBBColor_Evergreen_Red")) { dst = kStyleColor_kBBColor_Evergreen_Red; }
		if(!strcmp(src, "kStyleColor_kBBColor_Evergreen_Green")) { dst = kStyleColor_kBBColor_Evergreen_Green; }
		if(!strcmp(src, "kStyleColor_kBBColor_Evergreen_Yellow")) { dst = kStyleColor_kBBColor_Evergreen_Yellow; }
		if(!strcmp(src, "kStyleColor_kBBColor_Evergreen_Blue")) { dst = kStyleColor_kBBColor_Evergreen_Blue; }
		if(!strcmp(src, "kStyleColor_kBBColor_Evergreen_Cyan")) { dst = kStyleColor_kBBColor_Evergreen_Cyan; }
		if(!strcmp(src, "kStyleColor_kBBColor_Evergreen_Pink")) { dst = kStyleColor_kBBColor_Evergreen_Pink; }
		if(!strcmp(src, "kStyleColor_kBBColor_Evergreen_White")) { dst = kStyleColor_kBBColor_Evergreen_White; }
		if(!strcmp(src, "kStyleColor_kBBColor_Evergreen_LightBlue")) { dst = kStyleColor_kBBColor_Evergreen_LightBlue; }
		if(!strcmp(src, "kStyleColor_kBBColor_Evergreen_Orange")) { dst = kStyleColor_kBBColor_Evergreen_Orange; }
		if(!strcmp(src, "kStyleColor_kBBColor_Evergreen_LightBlueAlt")) { dst = kStyleColor_kBBColor_Evergreen_LightBlueAlt; }
		if(!strcmp(src, "kStyleColor_kBBColor_Evergreen_OrangeAlt")) { dst = kStyleColor_kBBColor_Evergreen_OrangeAlt; }
		if(!strcmp(src, "kStyleColor_kBBColor_Evergreen_MediumBlue")) { dst = kStyleColor_kBBColor_Evergreen_MediumBlue; }
		if(!strcmp(src, "kStyleColor_kBBColor_Evergreen_Amber")) { dst = kStyleColor_kBBColor_Evergreen_Amber; }
		if(!strcmp(src, "kStyleColor_kBBColor_UE4_Black")) { dst = kStyleColor_kBBColor_UE4_Black; }
		if(!strcmp(src, "kStyleColor_kBBColor_UE4_DarkRed")) { dst = kStyleColor_kBBColor_UE4_DarkRed; }
		if(!strcmp(src, "kStyleColor_kBBColor_UE4_DarkGreen")) { dst = kStyleColor_kBBColor_UE4_DarkGreen; }
		if(!strcmp(src, "kStyleColor_kBBColor_UE4_DarkBlue")) { dst = kStyleColor_kBBColor_UE4_DarkBlue; }
		if(!strcmp(src, "kStyleColor_kBBColor_UE4_DarkYellow")) { dst = kStyleColor_kBBColor_UE4_DarkYellow; }
		if(!strcmp(src, "kStyleColor_kBBColor_UE4_DarkCyan")) { dst = kStyleColor_kBBColor_UE4_DarkCyan; }
		if(!strcmp(src, "kStyleColor_kBBColor_UE4_DarkPurple")) { dst = kStyleColor_kBBColor_UE4_DarkPurple; }
		if(!strcmp(src, "kStyleColor_kBBColor_UE4_DarkWhite")) { dst = kStyleColor_kBBColor_UE4_DarkWhite; }
		if(!strcmp(src, "kStyleColor_kBBColor_UE4_Red")) { dst = kStyleColor_kBBColor_UE4_Red; }
		if(!strcmp(src, "kStyleColor_kBBColor_UE4_Green")) { dst = kStyleColor_kBBColor_UE4_Green; }
		if(!strcmp(src, "kStyleColor_kBBColor_UE4_Blue")) { dst = kStyleColor_kBBColor_UE4_Blue; }
		if(!strcmp(src, "kStyleColor_kBBColor_UE4_Yellow")) { dst = kStyleColor_kBBColor_UE4_Yellow; }
		if(!strcmp(src, "kStyleColor_kBBColor_UE4_Cyan")) { dst = kStyleColor_kBBColor_UE4_Cyan; }
		if(!strcmp(src, "kStyleColor_kBBColor_UE4_Purple")) { dst = kStyleColor_kBBColor_UE4_Purple; }
		if(!strcmp(src, "kStyleColor_kBBColor_UE4_White")) { dst = kStyleColor_kBBColor_UE4_White; }
		if(!strcmp(src, "kStyleColor_ActiveSession")) { dst = kStyleColor_ActiveSession; }
		if(!strcmp(src, "kStyleColor_InactiveSession")) { dst = kStyleColor_InactiveSession; }
		if(!strcmp(src, "kStyleColor_LogLevel_VeryVerbose")) { dst = kStyleColor_LogLevel_VeryVerbose; }
		if(!strcmp(src, "kStyleColor_LogLevel_Verbose")) { dst = kStyleColor_LogLevel_Verbose; }
		if(!strcmp(src, "kStyleColor_LogLevel_Log")) { dst = kStyleColor_LogLevel_Log; }
		if(!strcmp(src, "kStyleColor_LogLevel_Display")) { dst = kStyleColor_LogLevel_Display; }
		if(!strcmp(src, "kStyleColor_LogLevel_Warning")) { dst = kStyleColor_LogLevel_Warning; }
		if(!strcmp(src, "kStyleColor_LogLevel_Error")) { dst = kStyleColor_LogLevel_Error; }
		if(!strcmp(src, "kStyleColor_LogLevel_Fatal")) { dst = kStyleColor_LogLevel_Fatal; }
		if(!strcmp(src, "kStyleColor_Multiline")) { dst = kStyleColor_Multiline; }
		if(!strcmp(src, "kStyleColor_LogBackground_Normal")) { dst = kStyleColor_LogBackground_Normal; }
		if(!strcmp(src, "kStyleColor_LogBackground_NormalAlternate0")) { dst = kStyleColor_LogBackground_NormalAlternate0; }
		if(!strcmp(src, "kStyleColor_LogBackground_NormalAlternate1")) { dst = kStyleColor_LogBackground_NormalAlternate1; }
		if(!strcmp(src, "kStyleColor_LogBackground_Bookmarked")) { dst = kStyleColor_LogBackground_Bookmarked; }
		if(!strcmp(src, "kStyleColor_LogBackground_BookmarkedAlternate0")) { dst = kStyleColor_LogBackground_BookmarkedAlternate0; }
		if(!strcmp(src, "kStyleColor_LogBackground_BookmarkedAlternate1")) { dst = kStyleColor_LogBackground_BookmarkedAlternate1; }
		if(!strcmp(src, "kStyleColor_ResizeNormal")) { dst = kStyleColor_ResizeNormal; }
		if(!strcmp(src, "kStyleColor_ResizeHovered")) { dst = kStyleColor_ResizeHovered; }
		if(!strcmp(src, "kStyleColor_ResizeActive")) { dst = kStyleColor_ResizeActive; }
		if(!strcmp(src, "kStyleColor_MessageBoxBackground0")) { dst = kStyleColor_MessageBoxBackground0; }
		if(!strcmp(src, "kStyleColor_MessageBoxBackground1")) { dst = kStyleColor_MessageBoxBackground1; }
		if(!strcmp(src, "kStyleColor_TextShadow")) { dst = kStyleColor_TextShadow; }
		if(!strcmp(src, "kStyleColor_Count")) { dst = kStyleColor_Count; }
	}
	return dst;
}

vfilter_type_e vfilter_type_e_from_string(const char *src)
{
	vfilter_type_e dst = kVF_Count;
	if(src) {
		if(!strcmp(src, "kVF_Standard")) { dst = kVF_Standard; }
		if(!strcmp(src, "kVF_SQL")) { dst = kVF_SQL; }
		if(!strcmp(src, "kVF_Legacy")) { dst = kVF_Legacy; }
		if(!strcmp(src, "kVF_Count")) { dst = kVF_Count; }
	}
	return dst;
}

vfilter_token_type_e vfilter_token_type_e_from_string(const char *src)
{
	vfilter_token_type_e dst = kVFT_Count;
	if(src) {
		if(!strcmp(src, "kVFT_Invalid")) { dst = kVFT_Invalid; }
		if(!strcmp(src, "kVFT_OpenParen")) { dst = kVFT_OpenParen; }
		if(!strcmp(src, "kVFT_CloseParen")) { dst = kVFT_CloseParen; }
		if(!strcmp(src, "kVFT_String")) { dst = kVFT_String; }
		if(!strcmp(src, "kVFT_LessThan")) { dst = kVFT_LessThan; }
		if(!strcmp(src, "kVFT_LessThanEquals")) { dst = kVFT_LessThanEquals; }
		if(!strcmp(src, "kVFT_Equals")) { dst = kVFT_Equals; }
		if(!strcmp(src, "kVFT_NotEquals")) { dst = kVFT_NotEquals; }
		if(!strcmp(src, "kVFT_GreaterThan")) { dst = kVFT_GreaterThan; }
		if(!strcmp(src, "kVFT_GreaterThanEquals")) { dst = kVFT_GreaterThanEquals; }
		if(!strcmp(src, "kVFT_Matches")) { dst = kVFT_Matches; }
		if(!strcmp(src, "kVFT_And")) { dst = kVFT_And; }
		if(!strcmp(src, "kVFT_Or")) { dst = kVFT_Or; }
		if(!strcmp(src, "kVFT_Not")) { dst = kVFT_Not; }
		if(!strcmp(src, "kVFT_Contains")) { dst = kVFT_Contains; }
		if(!strcmp(src, "kVFT_StartsWith")) { dst = kVFT_StartsWith; }
		if(!strcmp(src, "kVFT_EndsWith")) { dst = kVFT_EndsWith; }
		if(!strcmp(src, "kVFT_DeltaMillisecondsAbsolute")) { dst = kVFT_DeltaMillisecondsAbsolute; }
		if(!strcmp(src, "kVFT_DeltaMillisecondsViewRelative")) { dst = kVFT_DeltaMillisecondsViewRelative; }
		if(!strcmp(src, "kVFT_Filename")) { dst = kVFT_Filename; }
		if(!strcmp(src, "kVFT_Thread")) { dst = kVFT_Thread; }
		if(!strcmp(src, "kVFT_PIEInstance")) { dst = kVFT_PIEInstance; }
		if(!strcmp(src, "kVFT_Category")) { dst = kVFT_Category; }
		if(!strcmp(src, "kVFT_Verbosity")) { dst = kVFT_Verbosity; }
		if(!strcmp(src, "kVFT_Text")) { dst = kVFT_Text; }
		if(!strcmp(src, "kVFT_Number")) { dst = kVFT_Number; }
		if(!strcmp(src, "kVFT_Count")) { dst = kVFT_Count; }
	}
	return dst;
}

//////////////////////////////////////////////////////////////////////////

const char *string_from_configColorUsage(const configColorUsage src)
{
	switch(src) {
		case kConfigColors_Full: return "kConfigColors_Full"; break;
		case kConfigColors_BgAsFg: return "kConfigColors_BgAsFg"; break;
		case kConfigColors_NoBg: return "kConfigColors_NoBg"; break;
		case kConfigColors_None: return "kConfigColors_None"; break;
		case kConfigColors_Count: return "kConfigColors_Count"; break;
	}
	return "";
}

const char *string_from_viewTileMode_t(const viewTileMode_t src)
{
	switch(src) {
		case kViewTileMode_Auto: return "kViewTileMode_Auto"; break;
		case kViewTileMode_PreferColumns: return "kViewTileMode_PreferColumns"; break;
		case kViewTileMode_PreferRows: return "kViewTileMode_PreferRows"; break;
		case kViewTileMode_Columns: return "kViewTileMode_Columns"; break;
		case kViewTileMode_Rows: return "kViewTileMode_Rows"; break;
		case kViewTileMode_None: return "kViewTileMode_None"; break;
		case kViewTileMode_Count: return "kViewTileMode_Count"; break;
	}
	return "";
}

const char *string_from_recording_tab_t(const recording_tab_t src)
{
	switch(src) {
		case kRecordingTab_Internal: return "kRecordingTab_Internal"; break;
		case kRecordingTab_External: return "kRecordingTab_External"; break;
		case kRecordingTab_Count: return "kRecordingTab_Count"; break;
	}
	return "";
}

const char *string_from_recording_sort_t(const recording_sort_t src)
{
	switch(src) {
		case kRecordingSort_StartTime: return "kRecordingSort_StartTime"; break;
		case kRecordingSort_Application: return "kRecordingSort_Application"; break;
		case kRecordingSort_Count: return "kRecordingSort_Count"; break;
	}
	return "";
}

const char *string_from_recording_group_t(const recording_group_t src)
{
	switch(src) {
		case kRecordingGroup_None: return "kRecordingGroup_None"; break;
		case kRecordingGroup_Application: return "kRecordingGroup_Application"; break;
		case kRecordingGroup_Count: return "kRecordingGroup_Count"; break;
	}
	return "";
}

const char *string_from_recording_type_t(const recording_type_t src)
{
	switch(src) {
		case kRecordingType_Normal: return "kRecordingType_Normal"; break;
		case kRecordingType_ExistingFile: return "kRecordingType_ExistingFile"; break;
		case kRecordingType_MainLog: return "kRecordingType_MainLog"; break;
		case kRecordingType_ExternalFile: return "kRecordingType_ExternalFile"; break;
		case kRecordingType_Count: return "kRecordingType_Count"; break;
	}
	return "";
}

const char *string_from_tag_visibility_t(const tag_visibility_t src)
{
	switch(src) {
		case kTagVisibility_Normal: return "kTagVisibility_Normal"; break;
		case kTagVisibility_AlwaysVisible: return "kTagVisibility_AlwaysVisible"; break;
		case kTagVisibility_AlwaysHidden: return "kTagVisibility_AlwaysHidden"; break;
		case kTagVisibility_Count: return "kTagVisibility_Count"; break;
	}
	return "";
}

const char *string_from_styleColor_e(const styleColor_e src)
{
	switch(src) {
		case kStyleColor_kBBColor_Default: return "kStyleColor_kBBColor_Default"; break;
		case kStyleColor_kBBColor_Evergreen_Black: return "kStyleColor_kBBColor_Evergreen_Black"; break;
		case kStyleColor_kBBColor_Evergreen_Red: return "kStyleColor_kBBColor_Evergreen_Red"; break;
		case kStyleColor_kBBColor_Evergreen_Green: return "kStyleColor_kBBColor_Evergreen_Green"; break;
		case kStyleColor_kBBColor_Evergreen_Yellow: return "kStyleColor_kBBColor_Evergreen_Yellow"; break;
		case kStyleColor_kBBColor_Evergreen_Blue: return "kStyleColor_kBBColor_Evergreen_Blue"; break;
		case kStyleColor_kBBColor_Evergreen_Cyan: return "kStyleColor_kBBColor_Evergreen_Cyan"; break;
		case kStyleColor_kBBColor_Evergreen_Pink: return "kStyleColor_kBBColor_Evergreen_Pink"; break;
		case kStyleColor_kBBColor_Evergreen_White: return "kStyleColor_kBBColor_Evergreen_White"; break;
		case kStyleColor_kBBColor_Evergreen_LightBlue: return "kStyleColor_kBBColor_Evergreen_LightBlue"; break;
		case kStyleColor_kBBColor_Evergreen_Orange: return "kStyleColor_kBBColor_Evergreen_Orange"; break;
		case kStyleColor_kBBColor_Evergreen_LightBlueAlt: return "kStyleColor_kBBColor_Evergreen_LightBlueAlt"; break;
		case kStyleColor_kBBColor_Evergreen_OrangeAlt: return "kStyleColor_kBBColor_Evergreen_OrangeAlt"; break;
		case kStyleColor_kBBColor_Evergreen_MediumBlue: return "kStyleColor_kBBColor_Evergreen_MediumBlue"; break;
		case kStyleColor_kBBColor_Evergreen_Amber: return "kStyleColor_kBBColor_Evergreen_Amber"; break;
		case kStyleColor_kBBColor_UE4_Black: return "kStyleColor_kBBColor_UE4_Black"; break;
		case kStyleColor_kBBColor_UE4_DarkRed: return "kStyleColor_kBBColor_UE4_DarkRed"; break;
		case kStyleColor_kBBColor_UE4_DarkGreen: return "kStyleColor_kBBColor_UE4_DarkGreen"; break;
		case kStyleColor_kBBColor_UE4_DarkBlue: return "kStyleColor_kBBColor_UE4_DarkBlue"; break;
		case kStyleColor_kBBColor_UE4_DarkYellow: return "kStyleColor_kBBColor_UE4_DarkYellow"; break;
		case kStyleColor_kBBColor_UE4_DarkCyan: return "kStyleColor_kBBColor_UE4_DarkCyan"; break;
		case kStyleColor_kBBColor_UE4_DarkPurple: return "kStyleColor_kBBColor_UE4_DarkPurple"; break;
		case kStyleColor_kBBColor_UE4_DarkWhite: return "kStyleColor_kBBColor_UE4_DarkWhite"; break;
		case kStyleColor_kBBColor_UE4_Red: return "kStyleColor_kBBColor_UE4_Red"; break;
		case kStyleColor_kBBColor_UE4_Green: return "kStyleColor_kBBColor_UE4_Green"; break;
		case kStyleColor_kBBColor_UE4_Blue: return "kStyleColor_kBBColor_UE4_Blue"; break;
		case kStyleColor_kBBColor_UE4_Yellow: return "kStyleColor_kBBColor_UE4_Yellow"; break;
		case kStyleColor_kBBColor_UE4_Cyan: return "kStyleColor_kBBColor_UE4_Cyan"; break;
		case kStyleColor_kBBColor_UE4_Purple: return "kStyleColor_kBBColor_UE4_Purple"; break;
		case kStyleColor_kBBColor_UE4_White: return "kStyleColor_kBBColor_UE4_White"; break;
		case kStyleColor_ActiveSession: return "kStyleColor_ActiveSession"; break;
		case kStyleColor_InactiveSession: return "kStyleColor_InactiveSession"; break;
		case kStyleColor_LogLevel_VeryVerbose: return "kStyleColor_LogLevel_VeryVerbose"; break;
		case kStyleColor_LogLevel_Verbose: return "kStyleColor_LogLevel_Verbose"; break;
		case kStyleColor_LogLevel_Log: return "kStyleColor_LogLevel_Log"; break;
		case kStyleColor_LogLevel_Display: return "kStyleColor_LogLevel_Display"; break;
		case kStyleColor_LogLevel_Warning: return "kStyleColor_LogLevel_Warning"; break;
		case kStyleColor_LogLevel_Error: return "kStyleColor_LogLevel_Error"; break;
		case kStyleColor_LogLevel_Fatal: return "kStyleColor_LogLevel_Fatal"; break;
		case kStyleColor_Multiline: return "kStyleColor_Multiline"; break;
		case kStyleColor_LogBackground_Normal: return "kStyleColor_LogBackground_Normal"; break;
		case kStyleColor_LogBackground_NormalAlternate0: return "kStyleColor_LogBackground_NormalAlternate0"; break;
		case kStyleColor_LogBackground_NormalAlternate1: return "kStyleColor_LogBackground_NormalAlternate1"; break;
		case kStyleColor_LogBackground_Bookmarked: return "kStyleColor_LogBackground_Bookmarked"; break;
		case kStyleColor_LogBackground_BookmarkedAlternate0: return "kStyleColor_LogBackground_BookmarkedAlternate0"; break;
		case kStyleColor_LogBackground_BookmarkedAlternate1: return "kStyleColor_LogBackground_BookmarkedAlternate1"; break;
		case kStyleColor_ResizeNormal: return "kStyleColor_ResizeNormal"; break;
		case kStyleColor_ResizeHovered: return "kStyleColor_ResizeHovered"; break;
		case kStyleColor_ResizeActive: return "kStyleColor_ResizeActive"; break;
		case kStyleColor_MessageBoxBackground0: return "kStyleColor_MessageBoxBackground0"; break;
		case kStyleColor_MessageBoxBackground1: return "kStyleColor_MessageBoxBackground1"; break;
		case kStyleColor_TextShadow: return "kStyleColor_TextShadow"; break;
		case kStyleColor_Count: return "kStyleColor_Count"; break;
	}
	return "";
}

const char *string_from_vfilter_type_e(const vfilter_type_e src)
{
	switch(src) {
		case kVF_Standard: return "kVF_Standard"; break;
		case kVF_SQL: return "kVF_SQL"; break;
		case kVF_Legacy: return "kVF_Legacy"; break;
		case kVF_Count: return "kVF_Count"; break;
	}
	return "";
}

const char *string_from_vfilter_token_type_e(const vfilter_token_type_e src)
{
	switch(src) {
		case kVFT_Invalid: return "kVFT_Invalid"; break;
		case kVFT_OpenParen: return "kVFT_OpenParen"; break;
		case kVFT_CloseParen: return "kVFT_CloseParen"; break;
		case kVFT_String: return "kVFT_String"; break;
		case kVFT_LessThan: return "kVFT_LessThan"; break;
		case kVFT_LessThanEquals: return "kVFT_LessThanEquals"; break;
		case kVFT_Equals: return "kVFT_Equals"; break;
		case kVFT_NotEquals: return "kVFT_NotEquals"; break;
		case kVFT_GreaterThan: return "kVFT_GreaterThan"; break;
		case kVFT_GreaterThanEquals: return "kVFT_GreaterThanEquals"; break;
		case kVFT_Matches: return "kVFT_Matches"; break;
		case kVFT_And: return "kVFT_And"; break;
		case kVFT_Or: return "kVFT_Or"; break;
		case kVFT_Not: return "kVFT_Not"; break;
		case kVFT_Contains: return "kVFT_Contains"; break;
		case kVFT_StartsWith: return "kVFT_StartsWith"; break;
		case kVFT_EndsWith: return "kVFT_EndsWith"; break;
		case kVFT_DeltaMillisecondsAbsolute: return "kVFT_DeltaMillisecondsAbsolute"; break;
		case kVFT_DeltaMillisecondsViewRelative: return "kVFT_DeltaMillisecondsViewRelative"; break;
		case kVFT_Filename: return "kVFT_Filename"; break;
		case kVFT_Thread: return "kVFT_Thread"; break;
		case kVFT_PIEInstance: return "kVFT_PIEInstance"; break;
		case kVFT_Category: return "kVFT_Category"; break;
		case kVFT_Verbosity: return "kVFT_Verbosity"; break;
		case kVFT_Text: return "kVFT_Text"; break;
		case kVFT_Number: return "kVFT_Number"; break;
		case kVFT_Count: return "kVFT_Count"; break;
	}
	return "";
}

//////////////////////////////////////////////////////////////////////////
