// Copyright (c) Matt Campbell
// MIT license (see License.txt)

// AUTOGENERATED FILE - DO NOT EDIT

// clang-format off

#include "mc_imgui_structs_generated.h"
#include "bb_assert.h"
#include "bb_array.h"
#include "str.h"
#include "va.h"

#include "fonts.h"
#include "sb.h"
#include "sdict.h"
#include "theme_config.h"
#include "uuid_rfc4122/sysdep.h"

#include <string.h>


void fontConfig_reset(fontConfig_t *val)
{
	if(val) {
		sb_reset(&val->path);
	}
}
fontConfig_t fontConfig_clone(const fontConfig_t *src)
{
	fontConfig_t dst = { BB_EMPTY_INITIALIZER };
	if(src) {
		dst.enabled = src->enabled;
		dst.size = src->size;
		dst.path = sb_clone(&src->path);
	}
	return dst;
}

void fontConfigs_reset(fontConfigs_t *val)
{
	if(val) {
		for(u32 i = 0; i < val->count; ++i) {
			fontConfig_reset(val->data + i);
		}
		bba_free(*val);
	}
}
fontConfigs_t fontConfigs_clone(const fontConfigs_t *src)
{
	fontConfigs_t dst = { BB_EMPTY_INITIALIZER };
	if(src) {
		for(u32 i = 0; i < src->count; ++i) {
			if(bba_add_noclear(dst, 1)) {
				bba_last(dst) = fontConfig_clone(src->data + i);
			}
		}
	}
	return dst;
}

void color_config_reset(color_config_t *val)
{
	if(val) {
	}
}
color_config_t color_config_clone(const color_config_t *src)
{
	color_config_t dst = { BB_EMPTY_INITIALIZER };
	if(src) {
		dst.colorName = src->colorName;
		dst.r = src->r;
		dst.g = src->g;
		dst.b = src->b;
		dst.a = src->a;
		dst.bTextShadows = src->bTextShadows;
		for(u32 i = 0; i < BB_ARRAYSIZE(src->pad); ++i) {
			dst.pad[i] = src->pad[i];
		}
	}
	return dst;
}

void colors_config_reset(colors_config_t *val)
{
	if(val) {
		for(u32 i = 0; i < val->count; ++i) {
			color_config_reset(val->data + i);
		}
		bba_free(*val);
	}
}
colors_config_t colors_config_clone(const colors_config_t *src)
{
	colors_config_t dst = { BB_EMPTY_INITIALIZER };
	if(src) {
		for(u32 i = 0; i < src->count; ++i) {
			if(bba_add_noclear(dst, 1)) {
				bba_last(dst) = color_config_clone(src->data + i);
			}
		}
	}
	return dst;
}

void theme_config_reset(theme_config_t *val)
{
	if(val) {
		colors_config_reset(&val->colors);
	}
}
theme_config_t theme_config_clone(const theme_config_t *src)
{
	theme_config_t dst = { BB_EMPTY_INITIALIZER };
	if(src) {
		dst.colors = colors_config_clone(&src->colors);
	}
	return dst;
}
